import assert from 'node:assert/strict';
import {test,before,after,beforeEach} from 'node:test';
import express from 'express';
import type {Server} from 'node:http';
import type {AddressInfo} from 'node:net';
import {adminRouter} from '../../routes/adminApi.js';
import {AuthStore} from '../../db/authStore.js';
import {ReferralStore} from '../../db/referralStore.js';
import {OrdersStore} from '../../db/ordersStore.js';
import {WaitlistStore} from '../../db/waitlistStore.js';
import {AdminAuditStore} from '../../db/adminAuditStore.js';
let server:Server;let base:string;
before(async()=>{delete process.env.DATABASE_URL;process.env.NODE_ENV='test';const app=express();app.use(express.json());app.use('/api/admin',adminRouter);
  server=await new Promise<Server>(resolve=>{const running=app.listen(0,'127.0.0.1',()=>resolve(running));});base=`http://127.0.0.1:${(server.address() as AddressInfo).port}/api/admin`;});
after(async()=>{await new Promise<void>((resolve,reject)=>server.close(error=>error?reject(error):resolve()));});
beforeEach(async()=>{AuthStore._clearDevStore();ReferralStore._clearDevStore();OrdersStore.clearDevStore();WaitlistStore._clearDevStore();AdminAuditStore._clearDevStore();
  for(const [id,role] of [['admin','admin'],['customer','customer']] as const){await AuthStore.createUser({id,name:id,email:`${id}@example.com`,phone:null,passwordHash:'SECRET_PASSWORD',role,status:'active'});await AuthStore.createSession(id,`${id}-token`,false);}});
const request=(path:string,token='admin-token',method='GET',body?:unknown)=>fetch(base+path,{method,headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});
test('all new admin routes and rule routes reject customer sessions',async()=>{for(const path of ['/referrals/overview','/referrals/leaderboard','/referrals/ledger','/referrals/policy','/referrals/referrers/customer','/referrals/rules'])assert.equal((await request(path,'customer-token')).status,403);
  assert.equal((await request('/referrals/referrers/customer/status','customer-token','PATCH',{enabled:false,confirm:true})).status,403);
  assert.equal((await request('/referrals/rules','customer-token','POST',{service_type:'data',reward_minor:50})).status,403);});
test('unauthenticated admin access returns 401',async()=>{assert.equal((await fetch(base+'/referrals/overview')).status,401);});
test('admin endpoints validate date pagination sort and ledger filters with HTTP 400',async()=>{for(const path of ['/referrals/leaderboard?limit=999','/referrals/overview?period=custom&start=bad&end=2026-10-03','/referrals/ledger?stage=invalid'])assert.equal((await request(path)).status,400);});
test('rule endpoints return validation warnings and confirmation errors',async()=>{
  assert.equal((await request('/referrals/rules','admin-token','POST',{service_type:'data',reward_minor:-1})).status,400);
  assert.equal((await request('/referrals/rules','admin-token','POST',{service_type:'data',reward_minor:50,enabled:true})).status,400);
  const saved=await request('/referrals/rules','admin-token','POST',{service_type:'data',reward_minor:50,enabled:true,confirmEnable:true});assert.equal(saved.status,200);const data=await saved.json();assert.equal(data.rule.effectiveStatus,'Active');assert.ok(data.warnings.length);assert.ok(!('level2_reward_minor' in data.rule));
});
test('admin suspension endpoint authenticates confirms and returns exact changed state',async()=>{await ReferralStore.getOrCreateProfile('customer');
  assert.equal((await request('/referrals/referrers/customer/status','admin-token','PATCH',{enabled:false})).status,400);
  const result=await (await request('/referrals/referrers/customer/status','admin-token','PATCH',{enabled:false,confirm:true})).json();assert.equal(result.changed,true);assert.equal(result.profile.enabled,false);
  const repeat=await (await request('/referrals/referrers/customer/status','admin-token','PATCH',{enabled:false,confirm:true})).json();assert.equal(repeat.changed,false);
});
test('customer drawer response exposes safe Earn summary and no profile creation',async()=>{let data=await (await request('/users/customer')).json();assert.equal(data.earn,null);assert.ok(!JSON.stringify(data).includes('SECRET_PASSWORD'));
  await ReferralStore.getOrCreateProfile('customer');data=await (await request('/users/customer')).json();assert.equal(typeof data.earn.code,'string');assert.ok(!('user_id' in data.earn));assert.equal(data.earn.approvedRewardsMinor,0);
});
test('policy endpoint is read only and normal admin GET does not activate rules',async()=>{const response=await (await request('/referrals/policy')).json();assert.equal(response.readOnly,true);assert.ok(response.policy.every((r:any)=>r.status==='missing'));assert.equal((await ReferralStore.getAllRules()).length,0);
  assert.equal((await request('/referrals/policy/apply','admin-token','POST',{})).status,404);
});
