import assert from 'node:assert/strict';
import {test,beforeEach} from 'node:test';
import {AuthStore} from '../../db/authStore.js';
import {OrdersStore} from '../../db/ordersStore.js';
import {ReferralStore} from '../../db/referralStore.js';
import {AdminEarnStore} from '../../db/adminEarnStore.js';
import {AdminAuditStore} from '../../db/adminAuditStore.js';
import {ReferralService} from '../../services/referralService.js';
import {parseEarnQuery,EarnInputError} from '../../services/adminEarnQuery.js';
import {saveAdminRewardRule,recommendedPolicyStatus} from '../../services/adminEarnControls.js';
import {STANDARD_DATA_REFERRAL_POLICY} from '../../config/dataReferralRewardPolicy.js';
import type {OrderRecord} from '../../types/orders.js';

let sequence=0;
const all=()=>parseEarnQuery({period:'all'});
const delay=()=>new Promise(resolve=>setTimeout(resolve,5));
async function user(id:string,name=id){return AuthStore.createUser({id,name,email:`${id}@example.com`,phone:'0241111111',passwordHash:'NEVER_EXPOSE_PASSWORD',role:'customer',status:'active'});}
async function owner(id='owner'){await user(id);return ReferralStore.getOrCreateProfile(id);}
async function bind(id='buyer',referrer='owner'){await user(id);const profile=await ReferralStore.findProfileByUserId(referrer);return ReferralStore.bindAttributionToUser({referredUserId:id,referrerUserId:referrer,sourceCode:profile!.referral_code});}
function fixture(extra:Partial<OrderRecord>={}):OrderRecord{const id=`order_${++sequence}`;const at=new Date(Date.now()-1000+sequence).toISOString();return{id,user_id:'buyer',referrer_user_id:'owner',public_reference:`MH-${id}`,
  customer_name:'Buyer',customer_email:'buyer@example.com',customer_phone:'0241111111',recipient_phone:'0241111111',network:'mtn',service_type:'data',product_id:'data',product_name_snapshot:'Data',bundle_size_snapshot:'1GB',amount:1000,currency:'GHS',status:'delivered',payment_provider:'paystack',payment_reference:`pay_${id}`,payment_status:'success',supplier_provider:null,supplier_order_id:null,supplier_response:null,supplier_cost_minor:700,supplier_offer_ref:null,supplier_last_checked_at:null,failure_reason:null,created_at:at,updated_at:at,paid_at:at,submitted_at:at,delivered_at:at,...extra};}
async function purchase(extra:Partial<OrderRecord>={}){const item=fixture(extra);await OrdersStore.createOrder(item);return item;}
async function ledger(order:OrderRecord,status:'pending'|'approved'|'reversed'='approved',minor=50){return ReferralStore.createLedgerEntry({referrer_user_id:order.referrer_user_id!,referred_user_id:order.user_id!,referral_attribution_id:null,order_id:order.id,marketplace_product_id:null,service_type:order.service_type||'data',reward_rule_id:null,network_level:1,reward_stage:'acquisition',amount_minor:minor,currency:'GHS',status,reason:'Safe fixture',idempotency_key:`fixture:${order.id}`,reversal_of_id:null,approved_at:order.delivered_at,rejected_at:null,reversed_at:status==='reversed'?new Date().toISOString():null,metadata_json:{secret:'NEVER_EXPOSE_METADATA'}});}
beforeEach(async()=>{process.env.NODE_ENV='test';delete process.env.DATABASE_URL;sequence=0;AuthStore._clearDevStore();OrdersStore.clearDevStore();ReferralStore._clearDevStore();AdminAuditStore._clearDevStore();await owner();await bind();for(const rule of STANDARD_DATA_REFERRAL_POLICY)await ReferralStore.createOrUpdateRule(rule);});

test('leaderboard ranks authoritative conversions and ties deterministically',async()=>{await owner('other');await bind('buyer2','other');await purchase();await purchase();await purchase({user_id:'buyer2',referrer_user_id:'other'});const result=await AdminEarnStore.leaderboard(all());assert.equal(result.items[0].userId,'owner');assert.equal(result.items[0].firstConversions,1);assert.equal(result.items[0].repeatConversions,1);assert.equal(result.items[0].rank,1);});
test('date filter excludes outside revenue but lifetime history makes period purchase recurring',async()=>{await purchase({created_at:'2020-01-01T00:00:00Z',delivered_at:'2020-01-01T00:00:00Z',paid_at:'2020-01-01T00:00:00Z'});await purchase();const row=(await AdminEarnStore.leaderboard(parseEarnQuery({period:'30d'}))).items[0];assert.equal(row.firstConversions,0);assert.equal(row.repeatConversions,1);assert.equal(row.deliveredRevenueMinor,1000);assert.equal(row.lifetimeReferredCustomers,1);});
test('server pagination returns bounded rows and correct total/rank',async()=>{await owner('b');await owner('c');const result=await AdminEarnStore.leaderboard(parseEarnQuery({period:'all',page:'2',limit:'1'}));assert.equal(result.total,3);assert.equal(result.items.length,1);assert.equal(result.items[0].rank,2);const empty=await AdminEarnStore.leaderboard(parseEarnQuery({period:'all',page:'10',limit:'1'}));assert.equal(empty.total,3);assert.deepEqual(empty.items,[]);});
test('search by referral code is case insensitive and literal',async()=>{const profile=await ReferralStore.findProfileByUserId('owner');const result=await AdminEarnStore.leaderboard(parseEarnQuery({period:'all',q:profile!.referral_code.toLowerCase()}));assert.equal(result.total,1);assert.equal(result.items[0].userId,'owner');assert.equal((await AdminEarnStore.leaderboard(parseEarnQuery({period:'all',q:'%'}))).total,0);});
test('paid delivered and reward aggregates do not multiply each other',async()=>{const first=await purchase();await purchase({status:'paid',delivered_at:null});await purchase({status:'refunded'});await ledger(first);const pending=await purchase();await ledger(pending,'pending',20);const reversed=await purchase();await ledger(reversed,'reversed',10);const m=(await AdminEarnStore.overview(all())).metrics;assert.equal(m.paidRevenueMinor,4000);assert.equal(m.deliveredRevenueMinor,3000);assert.equal(m.approvedRewardsMinor,50);assert.equal(m.pendingRewardsMinor,20);assert.equal(m.reversedRewardsMinor,10);assert.equal(m.rewardExpenseMinor,50);assert.equal(m.grossMarginMinor,900);});
test('unknown supplier costs are excluded from estimated gross margin',async()=>{await purchase({supplier_cost_minor:null});await purchase();const m=(await AdminEarnStore.overview(all())).metrics;assert.equal(m.costKnownOrders,1);assert.equal(m.grossMarginMinor,300);});
test('zero traffic never divides by zero',async()=>{await purchase();const row=(await AdminEarnStore.leaderboard(all())).items[0];assert.equal(row.conversionRate,0);assert.ok(Number.isFinite(row.conversionRate));});
test('global unique visitors deduplicate across profiles and ignore transient keys',async()=>{await owner('other');for(const id of ['owner','other']){const p=await ReferralStore.findProfileByUserId(id);await ReferralStore.recordClick({profileId:p!.id,referrerUserId:id,referralCode:p!.referral_code,visitorKey:'same-visitor'});}const p=await ReferralStore.findProfileByUserId('owner');await ReferralStore.recordClick({profileId:p!.id,referrerUserId:'owner',referralCode:p!.referral_code,visitorKey:'vk_transient_x'});const m=(await AdminEarnStore.overview(all())).metrics;assert.equal(m.uniqueVisitors,1);assert.equal(m.rawClicks,3);});
test('drill-down is scoped, bounded and never exposes unsafe metadata',async()=>{await owner('other');await bind('buyer2','other');await ledger(await purchase());await ledger(await purchase({user_id:'buyer2',referrer_user_id:'other'}));const detail=await AdminEarnStore.detail('owner',all());assert.equal(detail!.customers.total,1);assert.equal(detail!.customers.items[0].id,'buyer');assert.equal(detail!.ledger.total,1);assert.ok(!JSON.stringify(detail).includes('NEVER_EXPOSE'));assert.equal(await AdminEarnStore.detail('unknown',all()),null);});
test('ledger combines status service stage referrer order and date filters',async()=>{const first=await purchase();await ledger(first);await ledger(await purchase(),'reversed');const q=parseEarnQuery({period:'all',status:'approved',service:'data',stage:'acquisition',referrer:'owner',order:first.public_reference});const result=await AdminEarnStore.ledger(q);assert.equal(result.total,1);assert.equal(result.items[0].orderReference,first.public_reference);assert.ok(!('metadata_json' in result.items[0]));});
test('disabled rule can be explicitly enabled and audited',async()=>{await saveAdminRewardRule('admin',{id:'custom',service_type:'data',reward_minor:60,enabled:false});const result=await saveAdminRewardRule('admin',{id:'custom',enabled:true,confirmEnable:true});assert.equal(result.rule.enabled,true);const actions=(await AdminAuditStore.findRecent()).map(e=>e.action);assert.ok(actions.includes('referral_rule_created'));assert.ok(actions.includes('referral_rule_enabled'));});
test('enabled rule can be disabled and audited without ledger rewriting',async()=>{await ledger(await purchase());await saveAdminRewardRule('admin',{id:'standard_data_acquisition_v1',enabled:false});assert.equal((await ReferralStore.getAllRules()).find(r=>r.id==='standard_data_acquisition_v1')!.enabled,false);assert.equal((await AdminEarnStore.overview(all())).metrics.approvedRewardsMinor,50);assert.ok((await AdminAuditStore.findRecent()).some(e=>e.action==='referral_rule_disabled'));});
test('invalid server rule values remain rejected',async()=>{await assert.rejects(saveAdminRewardRule('admin',{service_type:'data',reward_minor:-1}));await assert.rejects(saveAdminRewardRule('admin',{service_type:'data',reward_minor:10,purchase_stage:'invalid'}));});
test('enabled money impacting saves require explicit confirmation',async()=>{await assert.rejects(saveAdminRewardRule('admin',{service_type:'data',reward_minor:20,enabled:true}),EarnInputError);});
test('recommended policy reports missing disabled enabled and conflicting configs without changing them',async()=>{assert.ok((await recommendedPolicyStatus()).every(r=>r.status==='enabled'));await saveAdminRewardRule('admin',{id:'standard_data_acquisition_v1',enabled:false});assert.equal((await recommendedPolicyStatus())[0].status,'disabled');await saveAdminRewardRule('admin',{id:'standard_data_acquisition_v1',reward_minor:99});assert.equal((await recommendedPolicyStatus())[0].status,'differs');ReferralStore._clearDevStore();assert.ok((await recommendedPolicyStatus()).every(r=>r.status==='missing'));assert.equal((await ReferralStore.getAllRules()).length,0);});
test('suspension rejects new referral captures',async()=>{const p=await ReferralStore.findProfileByUserId('owner');await ReferralStore.setProfileEnabled('owner',false,'admin');const r=await ReferralService.captureVisitorReferral({code:p!.referral_code,visitorKey:'new-visitor'});assert.equal(r.valid,false);assert.equal(await ReferralStore.countClicksByReferrer('owner'),0);});
test('suspension rejects explicit and direct new bindings',async()=>{const p=await ReferralStore.findProfileByUserId('owner');await ReferralStore.setProfileEnabled('owner',false,'admin');await user('new-buyer');const r=await ReferralService.resolveReferralContextForOrder({userId:'new-buyer',explicitCode:p!.referral_code});assert.equal(r.referrerUserId,null);assert.equal((await ReferralStore.bindAttributionToUser({referredUserId:'new-buyer',referrerUserId:'owner',sourceCode:p!.referral_code})).attribution,null);});
test('lifetime bound customer cannot bypass suspended profile rewards',async()=>{await ReferralStore.setProfileEnabled('owner',false,'admin');const item=await purchase({referrer_user_id:null});assert.equal(await ReferralService.processOrderReward(item),null);});
test('suspension preserves attribution and existing earned ledger entries',async()=>{const item=await purchase();const earned=await ReferralService.processOrderReward(item);const before=await ReferralStore.findAttributionByReferredUserId('buyer');await ReferralStore.setProfileEnabled('owner',false,'admin');assert.deepEqual(await ReferralStore.findAttributionByReferredUserId('buyer'),before);assert.deepEqual(await ReferralStore.findLedgerById(earned!.id),earned);assert.equal((await ReferralService.processOrderReward(item))!.id,earned!.id);});
test('resume permits future eligible rewards with the same code',async()=>{const code=(await ReferralStore.findProfileByUserId('owner'))!.referral_code;await ReferralStore.setProfileEnabled('owner',false,'admin');await delay();await ReferralStore.setProfileEnabled('owner',true,'admin');await delay();const item=await purchase({delivered_at:new Date().toISOString()});assert.ok(await ReferralService.processOrderReward(item));assert.equal((await ReferralStore.findProfileByUserId('owner'))!.referral_code,code);});
test('resume does not backpay an order skipped during suspension even delivered before it',async()=>{const item=await purchase();await ReferralStore.setProfileEnabled('owner',false,'admin');assert.equal(await ReferralService.processOrderReward(item),null);await delay();await ReferralStore.setProfileEnabled('owner',true,'admin');assert.equal(await ReferralService.processOrderReward(item),null);});
test('resume does not backpay a suspended-period order first processed after resume',async()=>{await ReferralStore.setProfileEnabled('owner',false,'admin');await delay();const at=new Date().toISOString();const item=await purchase({delivered_at:at});await delay();await ReferralStore.setProfileEnabled('owner',true,'admin');assert.equal(await ReferralService.processOrderReward(item),null);});
test('multiple suspend/resume periods stay enforced',async()=>{await ReferralStore.setProfileEnabled('owner',false);await delay();const first=await purchase({delivered_at:new Date().toISOString()});await delay();await ReferralStore.setProfileEnabled('owner',true);await delay();await ReferralStore.setProfileEnabled('owner',false);await delay();const second=await purchase({delivered_at:new Date().toISOString()});await delay();await ReferralStore.setProfileEnabled('owner',true);assert.equal(await ReferralService.processOrderReward(first),null);assert.equal(await ReferralService.processOrderReward(second),null);});
test('self-referral remains blocked after resume',async()=>{await ReferralStore.setProfileEnabled('owner',false);await ReferralStore.setProfileEnabled('owner',true);assert.equal(await ReferralService.processOrderReward(await purchase({user_id:'owner'})),null);});
test('customer summary has an explicit safe shape and does not create missing profiles',async()=>{const summary=await AdminEarnStore.customerSummary('owner');assert.deepEqual(Object.keys(summary!).sort(),['approvedRewardsMinor','code','enabled','peopleReferred','uniqueVisitors'].sort());assert.equal(await AdminEarnStore.customerSummary('buyer'),null);assert.equal(await ReferralStore.findProfileByUserId('buyer'),null);});
test('suspend resume mutations write distinct audit records and repeated state is idempotent',async()=>{await ReferralStore.setProfileEnabled('owner',false,'admin');await ReferralStore.setProfileEnabled('owner',false,'admin');await ReferralStore.setProfileEnabled('owner',true,'admin');const actions=(await AdminAuditStore.findRecent()).map(e=>e.action);assert.equal(actions.filter(a=>a==='referral_profile_suspended').length,1);assert.equal(actions.filter(a=>a==='referral_profile_resumed').length,1);});
test('giveaway exclusions remove disabled suspended and zero-conversion accounts',async()=>{await owner('zero');await owner('disabled');await purchase();await AuthStore.updateUserStatus('owner','disabled');const r=await AdminEarnStore.leaderboard(parseEarnQuery({period:'all',excludeDisabled:'true',excludeSuspended:'true',excludeZero:'true'}));assert.equal(r.total,0);});
test('custom dates include end date and reject malformed reversed ranges and unbounded pages',()=>{const q=parseEarnQuery({period:'custom',start:'2026-10-01',end:'2026-10-03'});assert.equal(q.range.end,'2026-10-04T00:00:00.000Z');for(const bad of [{period:'custom',start:'2026-02-30',end:'2026-03-01'},{period:'custom',start:'2026-10-03',end:'2026-10-01'},{limit:'1000'},{sort:'sql-injection'},{status:'bad'}])assert.throws(()=>parseEarnQuery(bad),EarnInputError);});

test('suspended captured first touch cannot be replaced by a competing checkout code',async()=>{const original=await ReferralStore.findProfileByUserId('owner');const other=await owner('other');
  await ReferralService.captureVisitorReferral({code:original!.referral_code,visitorKey:'captured-guest'});await user('fresh-user');await ReferralStore.setProfileEnabled('owner',false);
  const context=await ReferralService.resolveReferralContextForOrder({userId:'fresh-user',visitorKey:'captured-guest',explicitCode:other.referral_code});assert.equal(context.referrerUserId,'owner');
  assert.equal(await ReferralStore.findAttributionByReferredUserId('fresh-user'),null);assert.equal((await ReferralStore.findAttributionByVisitorKey('captured-guest'))!.referrer_user_id,'owner');
});
test('pre-attribution non-referred orders do not enter referral revenue history',async()=>{await purchase({referrer_user_id:null,user_id:'buyer',created_at:'2000-01-01T00:00:00Z',delivered_at:'2000-01-01T00:00:00Z',paid_at:'2000-01-01T00:00:00Z'});assert.equal((await AdminEarnStore.overview(all())).metrics.qualifyingOrders,0);});

test('guest checkout binding does not bypass referral cycle rejection',async()=>{const profile=await ReferralStore.getOrCreateProfile('buyer');await ReferralService.captureVisitorReferral({code:profile.referral_code,visitorKey:'cycle-guest'});const context=await ReferralService.resolveReferralContextForOrder({userId:'owner',visitorKey:'cycle-guest'});assert.equal(context.referrerUserId,null);assert.equal(await ReferralStore.findAttributionByReferredUserId('owner'),null);});
test('recommended policy reports nonstandard activation windows as differing',async()=>{await ReferralStore.createOrUpdateRule({...STANDARD_DATA_REFERRAL_POLICY[0],starts_at:'2030-01-01T00:00:00Z'});assert.equal((await recommendedPolicyStatus())[0].status,'differs');});
