import assert from 'node:assert/strict';
import {test,before,after,beforeEach,afterEach} from 'node:test';
import {readFileSync} from 'node:fs';
import crypto from 'node:crypto';
import express from 'express';
import type {Server} from 'node:http';
import type {AddressInfo} from 'node:net';
import {validateAfaPayload,normalizeGhanaCard,GHANA_REGIONS,afaStatusLabel} from '../../../shared/afa.js';
import {encryptAfaPayload,decryptAfaPayload} from '../../services/afaEncryption.js';
import {AfaStore} from '../../db/afaStore.js';
import {OrdersStore} from '../../db/ordersStore.js';
import {AuthStore} from '../../db/authStore.js';
import {AdminAuditStore} from '../../db/adminAuditStore.js';
import {AfaService,parseAfaPriceMinor} from '../../services/afaService.js';
import {FulfilmentService} from '../../services/fulfilmentService.js';
import {PaystackServerService} from '../../services/paystackService.js';
import {SuccessBizHubClient} from '../successBizHub/client.js';
import {SuccessBizHubProvider} from '../successBizHub/provider.js';
import {apiRouter,handlePaystackWebhook} from '../../routes/api.js';
import {adminRouter} from '../../routes/adminApi.js';
import {toSafePublicOrder,type OrderRecord} from '../../types/orders.js';
import {ReferralService} from '../../services/referralService.js';

const env={...process.env}, originalFetch=globalThis.fetch, originalProvider=AfaService.provider;
const originalInitialize=PaystackServerService.initializeTransaction, originalVerify=PaystackServerService.verifyTransaction;
const payload={name:'Synthetic AFA Customer',phone:'0249116309',idNumber:'GHA-202501234-5',location:'Accra',region:'Greater Accra',dateOfBirth:'1990-02-12'};
let server:Server,base:string,sequence=0,posts=0,gets=0,initialization:any;
const reply=(status='registered',priceMinor:any='1500',publicId='AFA_FIXTURE')=>({success:true,data:{publicId,status,phone:payload.phone,priceMinor}});
function fixture(status:OrderRecord['status']='pending_payment'):OrderRecord {
  const id=`afa_fixture_${++sequence}`,now=new Date().toISOString();
  return {id,user_id:'customer',public_reference:`MH-${id}`,customer_name:'Customer',customer_email:'receipt@example.com',customer_phone:'+233249116309',recipient_phone:'+233249116309',network:'mtn',service_type:'afa',product_id:'afa-registration',product_name_snapshot:'AFA Registration',bundle_size_snapshot:'MTN AFA Registration',amount:2500,currency:'GHS',status,payment_provider:'paystack',payment_reference:`pay_${id}`,payment_status:status==='pending_payment'?'pending':'success',supplier_provider:'success_biz_hub',supplier_order_id:null,supplier_response:null,supplier_cost_minor:null,supplier_offer_ref:null,supplier_last_checked_at:null,failure_reason:null,created_at:now,updated_at:now,paid_at:status==='pending_payment'?null:now,submitted_at:null,delivered_at:null};
}
async function saved(status:OrderRecord['status']='pending_payment') {const order=fixture(status);await AfaStore.create(order,payload);return order;}
async function request(path:string,method='GET',body?:unknown,token='customer-token') {
  return originalFetch(base+'/api'+path,{method,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})},...(body===undefined?{}:{body:JSON.stringify(body)})});
}
const checkout=()=>request('/afa/payments/initialize','POST',{...payload,consent:true,customerEmail:'receipt@example.com',amount:1});
function liveMockMode(){process.env.NODE_ENV='development';} // All network calls remain intercepted below.
before(async()=>{const app=express();app.use(express.json());app.use('/api',apiRouter);app.use('/api/admin',adminRouter);server=await new Promise(resolve=>{const s=app.listen(0,'127.0.0.1',()=>resolve(s));});base=`http://127.0.0.1:${(server.address() as AddressInfo).port}`;});
after(async()=>{await new Promise<void>(resolve=>server.close(()=>resolve()));});
beforeEach(async()=>{
  process.env.NODE_ENV='test';delete process.env.DATABASE_URL;delete process.env.MYSTERY_TEST_DATABASE_OPT_IN;
  process.env.AFA_PII_ENCRYPTION_KEY='ab'.repeat(32);process.env.AFA_SERVICE_ENABLED='true';process.env.AFA_RETAIL_PRICE_MINOR='2500';process.env.APP_URL='https://fixture.example';
  process.env.PAYSTACK_SECRET_KEY='sk_live_fixture';process.env.SUCCESS_BIZ_HUB_API_KEY=`fixture_${++sequence}`;process.env.SUCCESS_BIZ_HUB_FULFILLMENT_ENABLED='true';
  OrdersStore.clearDevStore();AfaStore.clearTestStore();AuthStore._clearDevStore();AdminAuditStore._clearDevStore();posts=0;gets=0;initialization=null;
  globalThis.fetch=async()=>{throw new Error('Unexpected external request: test blocked it');};
  AfaService.provider={client:{isConfigured:()=>true,isFulfillmentEnabled:()=>true},checkAfaAvailable:async()=>({available:true,status:'available'}),placeAfaRegistration:async()=>{posts++;return reply();},getAfaStatus:async()=>{gets++;return reply();}} as unknown as SuccessBizHubProvider;
  PaystackServerService.initializeTransaction=async params=>{initialization=params;return {success:true,reference:params.reference,authorizationUrl:'https://checkout.paystack.com/fixture'};};
  PaystackServerService.verifyTransaction=async reference=>({reference,isVerified:true,status:'success',amountPesewas:2500,currency:'GHS'});
  for(const role of ['customer','admin'] as const){await AuthStore.createUser({id:role,name:role,email:`${role}@example.com`,phone:null,passwordHash:'fixture-only',role});await AuthStore.createSession(role,`${role}-token`);}
});
afterEach(()=>{AfaService.provider=originalProvider;PaystackServerService.initializeTransaction=originalInitialize;PaystackServerService.verifyTransaction=originalVerify;globalThis.fetch=originalFetch;for(const key of Object.keys(process.env))if(!(key in env))delete process.env[key];Object.assign(process.env,env);});

test('canonical Ghana Card normalization',()=>assert.equal(normalizeGhanaCard(' gha 202501234 5 '),payload.idNumber));
test('valid payload uses local supplier phone and optional occupation is omitted',()=>assert.deepEqual(validateAfaPayload({...payload,phone:'+233249116309'}),payload));
for(const [field,value] of [['idNumber','GHA-123-5'],['idNumber',''],['name',''],['name','x'.repeat(129)],['location',''],['location','x'.repeat(129)],['region',''],['region','Unknown'],['dateOfBirth','2100-01-01'],['dateOfBirth','1990-02-30'],['dateOfBirth','12/02/1990'],['dateOfBirth','0000-01-01'],['phone','1234'],['occupation','x'.repeat(129)]] as const) {
  test(`rejects invalid ${field}: ${String(value).slice(0,18)}`,()=>assert.throws(()=>validateAfaPayload({...payload,[field]:value})));
}
test('all 16 regions accepted',()=>{assert.equal(GHANA_REGIONS.length,16);for(const region of GHANA_REGIONS)assert.equal(validateAfaPayload({...payload,region}).region,region);});
test('ported Ghana number is not rejected solely by prefix',()=>assert.equal(validateAfaPayload({...payload,phone:'0201234567'}).phone,'0201234567'));
test('valid leap date accepted without an invented minimum age',()=>assert.equal(validateAfaPayload({...payload,dateOfBirth:'2024-02-29'}).dateOfBirth,'2024-02-29'));
test('encryption round trip with random IV and no plaintext',()=>{const a=encryptAfaPayload('one',payload),b=encryptAfaPayload('one',payload);assert.notEqual(a,b);assert.ok(!a.includes(payload.idNumber));assert.ok(!a.includes(payload.dateOfBirth));assert.deepEqual(decryptAfaPayload('one',a),payload);});
test('encryption rejects wrong order binding',()=>assert.throws(()=>decryptAfaPayload('other',encryptAfaPayload('one',payload))));
test('encryption rejects tampered ciphertext',()=>{const v=JSON.parse(encryptAfaPayload('one',payload));v.data=Buffer.from('tampered').toString('base64');assert.throws(()=>decryptAfaPayload('one',JSON.stringify(v)));});
test('missing encryption key fails closed',async()=>{delete process.env.AFA_PII_ENCRYPTION_KEY;assert.throws(()=>encryptAfaPayload('one',payload));assert.equal((await AfaService.publicConfig()).available,false);});
for(const value of ['15.5','GH₵15',-1,NaN,Infinity,Number.MAX_SAFE_INTEGER+1,null])test(`invalid cost ${String(value)} never rounds into a charge`,()=>assert.equal(parseAfaPriceMinor(value),null));
test('supplier pesewas remain pesewas',()=>assert.equal(parseAfaPriceMinor('1500'),1500));
for(const value of ['','0','-1','1.5','abc'])test(`invalid retail configuration ${value} blocks availability`,async()=>{process.env.AFA_RETAIL_PRICE_MINOR=value;assert.equal((await AfaService.publicConfig()).available,false);});
test('disabled AFA blocks availability',async()=>{process.env.AFA_SERVICE_ENABLED='false';assert.equal((await AfaService.publicConfig()).available,false);});

test('supplier POST has exact fields, x-api-key, no price or phoneNumber',async()=>{let captured:any;globalThis.fetch=async(url,options)=>{captured={url,options};return new Response(JSON.stringify(reply()));};await new SuccessBizHubClient().createAfa({...payload,price:1,phoneNumber:'wrong'} as any);assert.match(String(captured.url),/\/v2\/afa$/);assert.equal(captured.options.method,'POST');assert.equal(captured.options.headers['x-api-key'],process.env.SUCCESS_BIZ_HUB_API_KEY);assert.deepEqual(JSON.parse(captured.options.body),payload);});
test('supplier occupation included only when supplied',async()=>{globalThis.fetch=async(_url,options)=>{assert.equal(JSON.parse(options!.body as string).occupation,'Teacher');return new Response(JSON.stringify(reply()));};await new SuccessBizHubClient().createAfa({...payload,occupation:'Teacher'});});
test('supplier GET uses encoded AFA identifier',async()=>{globalThis.fetch=async(url)=>{assert.match(String(url),/\/afa\/AFA_a%2Fb$/);return new Response(JSON.stringify(reply()));};assert.equal((await new SuccessBizHubClient().getAfa('AFA_a/b')).data!.status,'registered');});
for(const status of [403,429,500])test(`nested HTTP ${status} error is sanitized`,async()=>{globalThis.fetch=async()=>new Response(JSON.stringify({success:false,error:{code:'PERMISSION_DENIED',message:payload.idNumber}}),{status});await assert.rejects(new SuccessBizHubClient().createAfa(payload),(e:any)=>e.statusCode===status&&e.code==='PERMISSION_DENIED'&&!JSON.stringify(e).includes(payload.idNumber)&&!e.message.includes(payload.idNumber));});
for(const [permission,available,expected] of [[true,true,'available'],[false,true,'permission_missing'],[true,false,'unavailable']] as const)test(`discovery permission=${permission} available=${available}`,async()=>{globalThis.fetch=async()=>new Response(JSON.stringify({success:true,data:{keyPermissions:{afa:permission},services:[{id:'afa',keyGranted:permission,available}]}}));assert.equal((await new SuccessBizHubProvider().checkAfaAvailable()).status,expected);});
test('discovery errors fail closed',async()=>assert.equal((await new SuccessBizHubProvider().checkAfaAvailable()).available,false));
test('discovery is cached and concurrent requests coalesce',async()=>{let calls=0;globalThis.fetch=async()=>{calls++;return new Response(JSON.stringify({success:true,data:{keyPermissions:{afa:true},services:[{id:'afa',available:true}]}}));};const client=new SuccessBizHubClient();await Promise.all([client.getAfaServices(),client.getAfaServices()]);await client.getAfaServices();assert.equal(calls,1);process.env.SUCCESS_BIZ_HUB_API_KEY='different-fixture';await client.getAfaServices();assert.equal(calls,2);});

test('concurrent duplicate registration reserves one phone',async()=>{const results=await Promise.allSettled([AfaStore.create(fixture(),payload),AfaStore.create(fixture(),payload)]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);});
test('active registration blocks repurchase',async()=>{await saved();await assert.rejects(AfaStore.create(fixture(),payload),/active or completed/);});
test('latch cannot be claimed before successful payment',async()=>{const order=await saved();assert.equal(await AfaStore.claimSubmission(order.id),false);assert.equal((await AfaStore.find(order.id))!.submission_attempted_at,null);});
test('concurrent durable claims have one winner',async()=>{const order=await saved('queued');assert.equal((await Promise.all(Array.from({length:20},()=>AfaStore.claimSubmission(order.id)))).filter(Boolean).length,1);});
test('no dispatch before payment',async()=>{await AfaService.submit(await saved());assert.equal(posts,0);});
test('test payment never spends supplier money',async()=>{await FulfilmentService.processPaidOrder((await saved()).payment_reference,new Date().toISOString());assert.equal(posts,0);});
test('verified payment dispatches once, stores supplier cost/id and purges payload',async()=>{const order=await saved();liveMockMode();await Promise.all([FulfilmentService.processPaidOrder(order.payment_reference,new Date().toISOString()),FulfilmentService.processPaidOrder(order.payment_reference,new Date().toISOString())]);const updated=await OrdersStore.findOrder(order.id);assert.equal(posts,1);assert.equal(updated!.status,'delivered');assert.ok(updated!.delivered_at);assert.equal(updated!.supplier_order_id,'AFA_FIXTURE');assert.equal(updated!.supplier_cost_minor,1500);assert.equal(updated!.amount,2500);assert.equal((await AfaStore.find(order.id))!.encrypted_payload,null);await assert.rejects(AfaStore.create(fixture(),payload),/active or completed/);});
for(const failure of ['timeout','500','malformed'])test(`${failure} acceptance remains latched and manual review, never resubmitted`,async()=>{const order=await saved('queued');liveMockMode();AfaService.provider.placeAfaRegistration=async()=>{posts++;if(failure==='malformed')return {success:true} as any;throw Object.assign(new Error('private supplier content'),failure==='500'?{statusCode:500}:{isTimeout:true});};await AfaService.submit(order);await AfaService.submit((await OrdersStore.findOrder(order.id))!);assert.equal(posts,1);assert.equal((await OrdersStore.findOrder(order.id))!.manual_review,true);assert.ok((await AfaStore.find(order.id))!.encrypted_payload);assert.ok(!(await OrdersStore.findOrder(order.id))!.supplier_response!.includes('private supplier content'));});
test('known publicId polls instead of posting',async()=>{const order=await saved('queued');await AfaStore.supplierState(order.id,'AFA_FIXTURE','processing');await AfaService.submit(order);assert.equal(posts,0);assert.equal(gets,1);assert.equal((await OrdersStore.findOrder(order.id))!.status,'delivered');});
test('refresh recovers ID stored before order write and ignores Data status endpoint',async()=>{const order=await saved('queued');await AfaStore.supplierState(order.id,'AFA_FIXTURE','processing');await FulfilmentService.refreshOrderStatusIfDue(order,true);assert.equal(posts,0);assert.equal(gets,1);assert.equal((await OrdersStore.findOrder(order.id))!.supplier_order_id,'AFA_FIXTURE');});
test('saved publicId survives a failed local generic order update',async()=>{const order=await saved('queued'),original=OrdersStore.saveSupplierSubmission;OrdersStore.saveSupplierSubmission=async()=>{throw new Error('fixture local failure');};try{await assert.rejects(AfaService.applySupplierResult(order,reply('processing')));}finally{OrdersStore.saveSupplierSubmission=original;}assert.equal((await AfaStore.find(order.id))!.supplier_public_id,'AFA_FIXTURE');await AfaService.refresh(order);assert.equal(posts,0);assert.equal(gets,1);});
test('crash after latch without publicId becomes manual review on recovery',async()=>{const order=await saved('queued');await AfaStore.claimSubmission(order.id);(await AfaStore.find(order.id))!.submission_attempted_at=new Date(Date.now()-60_000).toISOString();await AfaService.refresh(order);assert.equal(posts,0);assert.equal((await OrdersStore.findOrder(order.id))!.manual_review,true);});
test('status poll is throttled even when forced',async()=>{const order=await saved('queued');await AfaService.applySupplierResult(order,reply('processing'));AfaService.provider.getAfaStatus=async()=>{gets++;return reply('processing');};const current=(await OrdersStore.findOrder(order.id))!;await Promise.all([AfaService.refresh(current),AfaService.refresh(current)]);assert.equal(gets,1);});
test('unknown status is nonterminal and needs review',async()=>{const order=await saved('queued');await AfaService.applySupplierResult(order,reply('unexpected'));assert.equal((await OrdersStore.findOrder(order.id))!.status,'processing');assert.equal((await OrdersStore.findOrder(order.id))!.manual_review,true);});
test('mismatched phone cannot mark registered',async()=>{const order=await saved('queued');const response=reply();response.data.phone='0201234567';await AfaService.applySupplierResult(order,response);assert.equal((await OrdersStore.findOrder(order.id))!.status,'processing');assert.equal((await OrdersStore.findOrder(order.id))!.manual_review,true);});
test('mismatched publicId cannot overwrite known supplier identity',async()=>{const order=await saved('queued');await AfaService.applySupplierResult(order,reply('processing'));await assert.rejects(AfaService.applySupplierResult((await OrdersStore.findOrder(order.id))!,reply('registered','1500','AFA_OTHER')));assert.equal((await OrdersStore.findOrder(order.id))!.supplier_order_id,'AFA_FIXTURE');});
test('invalid supplier cost retains retail and flags review',async()=>{const order=await saved('queued');await AfaService.applySupplierResult(order,reply('processing','15.50'));const result=(await OrdersStore.findOrder(order.id))!;assert.equal(result.supplier_cost_minor,null);assert.equal(result.amount,2500);assert.equal(result.manual_review,true);});
for(const status of ['failed','refunded','cancelled','expired'] as const)test(`${status} purges sensitive data and releases duplicate block`,async()=>{const order=await saved('queued');await OrdersStore.updateOrderStatus(order.id,status);assert.equal((await AfaStore.find(order.id))!.encrypted_payload,null);await AfaStore.create(fixture(),payload);});
test('refund pending preserves encrypted evidence for manual reconciliation',async()=>{const order=await saved('queued');await AfaService.applySupplierResult(order,reply('rejected'));assert.equal((await OrdersStore.findOrder(order.id))!.status,'refund_pending');assert.ok((await AfaStore.find(order.id))!.encrypted_payload);});
test('terminal reconciliation repairs missed purge after crash',async()=>{const order=await saved();await OrdersStore.createOrder({...order,status:'delivered'});await AfaStore.reconcileTerminalPayloads();assert.equal((await AfaStore.find(order.id))!.encrypted_payload,null);assert.equal((await AfaStore.find(order.id))!.purchase_blocked,true);});
test('data supplier webhook cannot deliver AFA',async()=>{const order=await saved('queued');await AfaService.applySupplierResult(order,reply('processing'));await OrdersStore.processSupplierWebhookEvent('afa-ignore','order.status.updated',{secret:payload.idNumber},[{supplierOrderId:'AFA_FIXTURE',status:'delivered',response:JSON.stringify(payload)}]);assert.equal((await OrdersStore.findOrder(order.id))!.status,'processing');});
test('AFA does not activate wildcard referral reward policies',async()=>assert.equal(await ReferralService.processOrderReward({...fixture('delivered'),referrer_user_id:'referrer'}),null));

test('registration API requires authentication',async()=>assert.equal((await request('/afa/payments/initialize','POST',payload,'')).status,401));
test('API requires consent before payment',async()=>{assert.equal((await request('/afa/payments/initialize','POST',payload)).status,400);assert.equal(initialization,null);});
test('unavailable supplier blocks payment',async()=>{AfaService.provider.checkAfaAvailable=async()=>({available:false,status:'unavailable'});assert.equal((await checkout()).status,503);assert.equal(initialization,null);});
test('API rejects oversized body before storing an order',async()=>assert.equal((await request('/afa/payments/initialize','POST',{...payload,consent:true,extra:'x'.repeat(9000)})).status,413));
test('API ignores browser price and snapshots canonical receipt email',async()=>{const response=await checkout();assert.equal(response.status,200);const result=await response.json(),order=(await OrdersStore.findOrder(result.orderRef))!;assert.equal(order.amount,2500);assert.equal(order.customer_email,'receipt@example.com');assert.equal(initialization.email,'receipt@example.com');assert.equal(initialization.amountPesewas,2500);assert.equal(initialization.callbackUrl,'https://fixture.example/afa');assert.equal(posts,0);});
test('Paystack and audit metadata contain no Ghana Card or DOB',async()=>{await checkout();assert.deepEqual(Object.keys(initialization.metadata).sort(),['product_id','public_reference','service_type']);const logs=JSON.stringify(await AdminAuditStore.findRecent(50));for(const secret of [payload.idNumber,payload.dateOfBirth]){assert.ok(!JSON.stringify(initialization).includes(secret));assert.ok(!logs.includes(secret));}});
test('public order and admin details never expose full identity payload',async()=>{const order=await saved();const publicJson=JSON.stringify(toSafePublicOrder(order));const response=await request(`/admin/orders/${order.public_reference}`,'GET',undefined,'admin-token');assert.equal(response.status,200);const data=await response.json(),adminJson=JSON.stringify(data);assert.equal(data.order.afa_registration.maskedIdNumber,'GHA-******234-5');for(const secret of [payload.idNumber,payload.dateOfBirth,'encrypted_payload','authTag']){assert.ok(!publicJson.includes(secret));assert.ok(!adminJson.includes(secret));}});
test('customer cannot use admin AFA refresh',async()=>{const order=await saved();assert.equal((await request(`/admin/orders/${order.public_reference}/refresh`,'POST',{})).status,403);});
test('admin refresh uses AFA GET and masked details',async()=>{const order=await saved('queued');await AfaService.applySupplierResult(order,reply('processing'));const response=await request(`/admin/orders/${order.public_reference}/refresh`,'POST',{},'admin-token');assert.equal(response.status,200);assert.equal(gets,1);assert.equal(posts,0);assert.ok((await response.json()).order.afa_registration.sensitivePayloadPurgedAt);});
test('admin cannot manually invent registered status',async()=>{const order=await saved('queued');assert.equal((await request(`/admin/orders/${order.public_reference}/status`,'PATCH',{status:'delivered'},'admin-token')).status,400);});
test('generic payment endpoint cannot bypass authenticated AFA validation',async()=>assert.equal((await request('/payments/initialize','POST',{serviceType:'afa',productId:'afa-registration'},'')).status,400));
test('wrong payment amount never dispatches',async()=>{const order=await saved();liveMockMode();PaystackServerService.verifyTransaction=async reference=>({reference,isVerified:true,status:'success',amountPesewas:1,currency:'GHS'});assert.equal((await request(`/payments/verify/${order.payment_reference}`)).status,400);assert.equal(posts,0);assert.equal((await OrdersStore.findOrder(order.id))!.payment_status,'pending');});
test('unverified payment never dispatches',async()=>{const order=await saved();liveMockMode();PaystackServerService.verifyTransaction=async reference=>({reference,isVerified:false,status:'pending',amountPesewas:2500,currency:'GHS'});assert.equal((await (await request(`/payments/verify/${order.payment_reference}`)).json()).verified,false);assert.equal(posts,0);});
test('verified API payment completes AFA once',async()=>{const order=await saved();liveMockMode();assert.equal((await request(`/payments/verify/${order.payment_reference}`)).status,200);await request(`/payments/verify/${order.payment_reference}`);assert.equal(posts,1);});
test('duplicate signed Paystack webhooks dispatch once',async()=>{const order=await saved();liveMockMode();const body={event:'charge.success',data:{reference:order.payment_reference,status:'success',amount:2500,currency:'GHS'}},rawBody=Buffer.from(JSON.stringify(body)),signature=crypto.createHmac('sha512','sk_live_fixture').update(rawBody).digest('hex');const req={body,rawBody,headers:{'x-paystack-signature':signature}} as any;const res={status(){return this;},json(){return this;}} as any;await Promise.all([handlePaystackWebhook(req,res),handlePaystackWebhook(req,res)]);assert.equal(posts,1);});
test('customer Orders list includes AFA safely',async()=>{const order=await saved('processing');const response=await request('/orders/my-orders');const json=await response.json();assert.equal(json.orders[0].service_type,'afa');assert.ok(!JSON.stringify(json).includes(payload.idNumber));assert.equal(json.orders[0].public_reference,order.public_reference);});
test('safe public availability exposes no supplier credentials',async()=>{const json=JSON.stringify(await (await request('/afa/config','GET',undefined,'')).json());assert.ok(!json.includes(process.env.SUCCESS_BIZ_HUB_API_KEY!));assert.ok(!json.includes(process.env.AFA_PII_ENCRYPTION_KEY!));});
test('initialization failure cancels and purges, without supplier POST',async()=>{PaystackServerService.initializeTransaction=async params=>{initialization=params;return {success:false,reference:params.reference};};assert.equal((await checkout()).status,503);const order=(await OrdersStore.findOrder(initialization.reference))!;assert.equal(order.status,'cancelled');assert.equal((await AfaStore.find(order.id))!.encrypted_payload,null);assert.equal(posts,0);});

const source=(file:string)=>readFileSync(new URL('../../../'+file,import.meta.url),'utf8');
test('public AFA page, auth continuation and memory-only form are wired',()=>{const code=source('src/components/services/AfaRegistrationPage.tsx');assert.match(code,/openAuth\('login'[\s\S]*setRegistering\(true\)/);assert.doesNotMatch(code,/localStorage|sessionStorage|indexedDB/);assert.match(code,/type=\{field==='dateOfBirth'\?'date'/);assert.match(code,/aria-invalid/);assert.match(code,/config\?\.retailPriceGhc/);});
test('More Services and route target AFA',()=>{assert.match(source('src/data/services.ts'),/targetPage:'afa'/);assert.match(source('src/utils/routing.ts'),/afa: '\/afa'/);assert.match(source('src/components/services/MoreServicesPage.tsx'),/getAfaConfig/);});
test('customer labels distinguish registration, payment and review',()=>{assert.equal(afaStatusLabel('delivered'),'Registered');assert.equal(afaStatusLabel('queued'),'Payment Confirmed');assert.equal(afaStatusLabel('queued',true),'Needs Attention');assert.equal(afaStatusLabel('refund_pending'),'Refund Pending');});
test('admin filter and masked AFA details are present',()=>{const code=source('src/components/admin/sections/AdminOrdersSection.tsx');assert.match(code,/value="afa"/);assert.match(code,/maskedIdNumber/);assert.doesNotMatch(code,/dateOfBirth|encrypted_payload/);});
test('unpaid AFA appears as Awaiting Payment in customer history',async()=>{const order=await saved();const result=await (await request('/orders/my-orders')).json();assert.equal(result.orders[0].public_reference,order.public_reference);assert.equal(afaStatusLabel(result.orders[0].status),'Awaiting Payment');});
test('admin system reports safe AFA permission state',async()=>{AfaService.provider.checkAfaAvailable=async()=>({available:false,status:'permission_missing'});const response=await request('/admin/system','GET',undefined,'admin-token');assert.equal(response.status,200);const result=await response.json();assert.equal(result.system.components.afa.status,'permission_missing');assert.ok(!JSON.stringify(result).includes(process.env.SUCCESS_BIZ_HUB_API_KEY!));});
for(const statusCode of [403,429])test(`supplier HTTP ${statusCode} creates refund review without retry`,async()=>{const order=await saved('queued');liveMockMode();AfaService.provider.placeAfaRegistration=async()=>{posts++;throw Object.assign(new Error('sensitive supplier rejection'),{statusCode});};await AfaService.submit(order);await AfaService.submit((await OrdersStore.findOrder(order.id))!);assert.equal(posts,1);assert.equal((await OrdersStore.findOrder(order.id))!.status,'refund_pending');assert.equal((await OrdersStore.findOrder(order.id))!.manual_review,true);});
test('phone mismatch does not record successful registration timestamp',async()=>{const order=await saved('queued');const response=reply();response.data.phone='0201234567';await AfaService.applySupplierResult(order,response);assert.equal((await AfaStore.find(order.id))!.registered_at,null);assert.ok((await AfaStore.find(order.id))!.encrypted_payload);});
test('AFA info form clears identity fields when the signed-in account changes',()=>{const code=source('src/components/services/AfaRegistrationPage.tsx');assert.match(code,/\[user\?\.id\]/);assert.match(code,/idNumber:'',dateOfBirth:''/);});
test('background active-order query includes incomplete AFA publicId persistence',async()=>{const order=await saved('queued');await AfaStore.supplierState(order.id,'AFA_FIXTURE','processing');assert.ok((await OrdersStore.getActiveSupplierOrders()).some(o=>o.id===order.id));});
