import assert from 'node:assert/strict';
import { test,before,after,beforeEach,mock } from 'node:test';
import express from 'express';
import type {Server} from 'node:http';
import type {AddressInfo} from 'node:net';
import { apiRouter } from '../../routes/api.js';
import { adminRouter } from '../../routes/adminApi.js';
import { MarketplaceStore } from '../../db/marketplaceStore.js';
import { MarketplaceControlStore } from '../../db/marketplaceControlStore.js';
import { AuthStore } from '../../db/authStore.js';
import { AdminAuditStore } from '../../db/adminAuditStore.js';
import { OrdersStore } from '../../db/ordersStore.js';
import { ReferralStore } from '../../db/referralStore.js';
import { PaystackServerService } from '../../services/paystackService.js';
import { marketplaceFulfilment } from '../../services/marketplaceCheckoutPolicy.js';
import { extractProductHeuristically,sanitizeExtractionResult,parseSupplierAdvertWithAi,groundAiExtraction } from '../../services/marketplaceAiImporter.js';
import { toPublicMarketplaceProduct,toAdminMarketplaceProduct,CATEGORY_LABELS } from '../../types/marketplace.js';
import { toSafePublicOrder,toAdminOrderDetails } from '../../types/orders.js';
import { productReadiness,whatsappLink } from '../../../shared/marketplacePolicy.js';
import { MARKETPLACE_FLEXIBILITY_SCHEMA } from '../../db/marketplaceFlexibilitySchema.js';
let server:Server,base:string;
before(async()=>{assert.equal(process.env.DATABASE_URL,undefined,'Isolated runner must remove inherited DB URL');assert.equal(process.env.NODE_ENV,'test');const app=express();app.use(express.json());app.use('/api',apiRouter);app.use('/api/admin',adminRouter);server=await new Promise<Server>(resolve=>{const running=app.listen(0,'127.0.0.1',()=>resolve(running));});base=`http://127.0.0.1:${(server.address() as AddressInfo).port}`;});
after(async()=>{await new Promise<void>(resolve=>server.close(()=>resolve()));});
beforeEach(async()=>{mock.restoreAll();MarketplaceStore._clearInMemoryStore();MarketplaceControlStore.resetMemory();AuthStore._clearDevStore();AdminAuditStore._clearDevStore();OrdersStore.clearDevStore();ReferralStore._clearDevStore();for(const role of ['admin','customer'] as const){await AuthStore.createUser({id:role,name:role,email:`${role}@example.com`,phone:null,passwordHash:'synthetic-unused-hash',role});await AuthStore.createSession(role,`${role}-token`);}mock.method(PaystackServerService,'initializeTransaction',async(p:any)=>({success:true,reference:p.reference,authorizationUrl:'https://checkout.paystack.com/isolated-fixture'}));});
const request=(path:string,method='GET',body?:unknown,token:string|null='admin-token')=>fetch(`${base}/api${path}`,{method,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})},...(body!==undefined?{body:JSON.stringify(body)}:{})});
const input=(extra:Record<string,unknown>={})=>({name:'Test Product',category:'digital_products',productKind:'digital',priceType:'fixed',priceGhc:199,availability:'available',fulfilmentMode:'digital_delivery',...extra});
async function create(extra:Record<string,unknown>={}){const response=await request('/admin/marketplace/products','POST',input(extra));assert.equal(response.status,201,JSON.stringify(await response.clone().json()));return (await response.json()).product;}
const action=(id:string,name:string,body:unknown={})=>request(`/admin/marketplace/products/${id}/${name}`,'POST',body);
async function raw(extra:Record<string,unknown>={}){const product=await create(extra);return (await MarketplaceStore.getProductById(product.id))!;}
const checkout=(p:any,extra:Record<string,unknown>={})=>request('/payments/initialize','POST',{serviceType:'marketplace',productId:p.id,customerName:'Fixture Customer',phone:'0241234567',email:'fixture@example.com',fulfilmentMethod:p.fulfilmentMode||'digital_delivery',...extra},null);
const pickup=[{id:'loc_fixture',name:'Fixture Hub',city:'Accra',area:'Central',active:true}];
for (const [kind,mode] of [['physical','delivery'],['digital','digital_delivery'],['service','manual_activation']]) test(`${kind} referral reward settles only after successful payment and completion, once`,async()=>{
  await AuthStore.createUser({id:'referrer',name:'Referrer',email:'referrer@example.com',phone:null,passwordHash:'synthetic-unused',role:'customer'});
  await ReferralStore.getOrCreateProfile('referrer');
  const p=await create({productKind:kind,fulfilmentMode:mode,published:true,confirmWarnings:true,referralRewardMinor:150});
  assert.equal((await checkout(p,kind==='physical'?{deliveryCity:'Accra',deliveryArea:'Central'}:{})).status,200);
  const order=OrdersStore.adminDevOrders()[0];order.referrer_user_id='referrer';order.user_id='customer';
  assert.equal(ReferralStore.adminDevSnapshot().ledger.length,0);
  await OrdersStore.markOrderPaid(order.payment_reference,new Date().toISOString());
  assert.equal(ReferralStore.adminDevSnapshot().ledger.length,0);
  await OrdersStore.updateMarketplaceStatus(order.id,'completed');
  await OrdersStore.updateMarketplaceStatus(order.id,'completed');
  const ledger=ReferralStore.adminDevSnapshot().ledger;assert.equal(ledger.length,1);assert.equal(ledger[0].amount_minor,150);assert.equal(ledger[0].marketplace_product_id,p.id);
  await action(p.id,'duplicate');assert.equal(ReferralStore.adminDevSnapshot().ledger.length,1);
});

test('legacy record projects physical with existing pickup/delivery defaults',async()=>{const p=await raw();delete p.product_kind;assert.equal(toPublicMarketplaceProduct(p).productKind,'physical');});
for(const [kind,mode] of [['physical','both'],['digital','digital_delivery'],['service','manual_activation']])test(`create ${kind} persists kind and defaults to draft`,async()=>{const p=await create({productKind:kind,fulfilmentMode:mode});assert.equal(p.productKind,kind);assert.equal(p.published,false);assert.equal((await MarketplaceStore.getProductById(p.id))!.product_kind,kind);});
test('invalid product kind rejected',async()=>{assert.equal((await request('/admin/marketplace/products','POST',input({productKind:'download'}))).status,400);});
for(const [kind,mode] of [['physical','pickup'],['physical','delivery'],['physical','both'],['digital','digital_delivery'],['digital','manual_activation'],['service','manual_activation'],['service','inquiry_only']])test(`${kind} accepts ${mode}`,async()=>{assert.equal((await create({productKind:kind,fulfilmentMode:mode})).fulfilmentMode,mode);});
for(const [kind,mode] of [['digital','pickup'],['digital','both'],['service','delivery'],['service','digital_delivery'],['physical','manual_activation']])test(`${kind} rejects ${mode}`,async()=>{assert.equal((await request('/admin/marketplace/products','POST',input({productKind:kind,fulfilmentMode:mode}))).status,400);});
test('existing categories seeded with all legacy slugs',async()=>{assert.deepEqual(new Set((await MarketplaceControlStore.getCategories()).map(c=>c.slug)),new Set(Object.keys(CATEGORY_LABELS).filter(s=>s!=='all')));});
test('admin creates a category without code deployment',async()=>{const res=await request('/admin/marketplace/categories','POST',{slug:'business_services',label:'Business Services'});assert.equal(res.status,201);assert.equal((await create({category:'business_services',productKind:'service',fulfilmentMode:'manual_activation'})).categoryLabel,'Business Services');assert.equal((await MarketplaceStore.getAdminProducts())[0].categoryLabel,'Business Services');});
test('category rename changes public and admin authoritative labels',async()=>{const p=await create({published:true,confirmWarnings:true});await request('/admin/marketplace/categories/digital_products','PATCH',{label:'Subscriptions'});assert.equal((await MarketplaceStore.getPublicProductBySlug(p.slug))!.categoryLabel,'Subscriptions');assert.equal((await MarketplaceStore.getAdminProducts())[0].categoryLabel,'Subscriptions');});
test('deactivated category disappears from public filters but existing products remain accessible',async()=>{const p=await create({published:true,confirmWarnings:true});assert.equal((await request('/admin/marketplace/categories/digital_products','PATCH',{active:false})).status,200);const data=await (await request('/marketplace/categories')).json();assert.ok(!data.categories.some((c:any)=>c.slug==='digital_products'));assert.ok(await MarketplaceStore.getPublicProductBySlug(p.slug));});
test('duplicate category slug returns safe conflict',async()=>{assert.equal((await request('/admin/marketplace/categories','POST',{slug:'digital_products',label:'Conflict'})).status,409);});
test('category creation requires a nonempty display label before persistence',async()=>{for(const label of [undefined,'   ']){const response=await request('/admin/marketplace/categories','POST',{slug:'missing_label',label});assert.equal(response.status,400);}assert.ok(!(await MarketplaceControlStore.getCategories()).some(c=>c.slug==='missing_label'));});
test('category ordering persists',async()=>{await request('/admin/marketplace/categories/digital_products','PATCH',{sortOrder:0});assert.equal((await MarketplaceControlStore.getCategories()).find(c=>c.slug==='digital_products')!.sort_order,0);});
test('old unknown category falls back to readable slug',async()=>{const p=await raw();p.category='legacy_supplies';assert.equal(toPublicMarketplaceProduct(p).categoryLabel,'legacy_supplies');});
test('new products cannot select inactive categories',async()=>{await request('/admin/marketplace/categories/digital_products','PATCH',{active:false});assert.equal((await request('/admin/marketplace/products','POST',input())).status,400);});
test('category hard deletion has no endpoint',async()=>{assert.equal((await request('/admin/marketplace/categories/digital_products','DELETE')).status,404);});
for(const [advert,kind,category] of [['HP Business Laptop GH₵3700','physical','laptops_computers'],['Software license GH₵199','digital','business_software'],['200GB cloud storage\nGH₵199\n3 months','digital','digital_products'],['Registration service GH₵50','service','digital_products']])test(`AI classifies explicit ${advert.split('\n')[0]}`,()=>{const p=extractProductHeuristically(advert);assert.equal(p.productKind,kind);assert.equal(p.category,category);assert.ok(!('published' in p));});
test('unknown advert has no laptop fallback or invented fulfilment',()=>{const p=extractProductHeuristically('Unspecified item');assert.equal(p.productKind,null);assert.equal(p.category,null);assert.equal(p.fulfilmentMode,null);assert.equal(p.priceGhc,null);assert.ok(p.warnings.length);});
test('AI classification prefers actual product over incidental software or activation text',()=>{assert.equal(extractProductHeuristically('Business Laptop\nSoftware licence included').productKind,'physical');assert.equal(extractProductHeuristically('Cloud storage subscription\nManual activation').productKind,'digital');});
test('AI result removes invented pricing, variants and unsupported account requirements',()=>{const extracted=sanitizeExtractionResult({name:'Cloud',productKind:'digital',category:'digital_products',priceGhc:999,detectedPriceOptions:[{label:'Invented option',priceGhc:999}],fulfilmentIdentifierLabel:'Account email',fulfilmentIdentifierRequired:true});const grounded=groundAiExtraction(extracted,'200GB cloud storage\nGH₵199\n3 months');assert.equal(grounded.priceGhc,null);assert.equal(grounded.priceType,'quote');assert.equal(grounded.detectedPriceOptions.length,0);assert.equal(grounded.fulfilmentIdentifierRequired,false);assert.ok(grounded.warnings.some(w=>w.includes('Unsupported')));});
test('AI preserves cents and avoids treating capacity/duration as price',()=>{assert.equal(extractProductHeuristically('200GB cloud storage\nGH₵199.50\n3 months').priceGhc,199.50);assert.equal(extractProductHeuristically('200GB cloud storage 3 months').priceGhc,null);});
test('AI explicitly supplied dynamic category is accepted; unsupported removed',()=>{assert.equal(sanitizeExtractionResult({category:'business_services'},[{slug:'business_services',label:'Services'}]).category,'business_services');assert.equal(sanitizeExtractionResult({category:'fake'}).category,null);});
test('AI active categories respond to administrator changes at parse time',async()=>{await MarketplaceControlStore.saveCategory({slug:'business_services',label:'Services'},'admin');assert.equal((await parseSupplierAdvertWithAi('Registration service')).category,'business_services');await MarketplaceControlStore.saveCategory({active:false},'admin','business_services');assert.notEqual((await parseSupplierAdvertWithAi('Registration service')).category,'business_services');});
test('AI contains no fabricated image URL, auto-publication or default hardware specifications',()=>{const p=extractProductHeuristically('200GB cloud storage GH₵199');assert.ok(!('imageUrl' in p));assert.ok(!('published' in p));assert.ok(p.specs.every(s=>!(/Ryzen|DDR4|NVMe/.test(s.value))));});
test('AI credential suggestion removed',()=>{const p=sanitizeExtractionResult({productKind:'digital',category:'digital_products',fulfilmentIdentifierLabel:'Account password',fulfilmentIdentifierRequired:true});assert.equal(p.fulfilmentIdentifierLabel,null);assert.equal(p.fulfilmentIdentifierRequired,false);});
test('draft product cannot be retrieved by public slug or list',async()=>{const p=await create();assert.equal((await request('/marketplace/products/'+p.slug)).status,404);assert.equal((await MarketplaceStore.getPublicProducts()).length,0);});
test('duplicate copies safe content with unique ID/slug, no history, draft and unfeatured',async()=>{const p=await create({published:true,featured:true,confirmWarnings:true,adminNote:'Internal margin'});const a=await (await action(p.id,'duplicate')).json(),b=await (await action(p.id,'duplicate')).json();assert.notEqual(a.product.id,p.id);assert.notEqual(a.product.id,b.product.id);assert.notEqual(a.product.slug,b.product.slug);assert.equal(a.product.published,false);assert.equal(a.product.featured,false);assert.equal(a.product.archived,false);assert.equal((await MarketplaceStore.getProductById(p.id))!.published,true);assert.equal((await MarketplaceControlStore.listInquiries()).total,0);assert.equal((await OrdersStore.adminDevOrders()).length,0);});
test('restore archived product stays draft',async()=>{const p=await create({published:true,confirmWarnings:true});await action(p.id,'archive');const restored=await (await action(p.id,'restore')).json();assert.equal(restored.product.archived,false);assert.equal(restored.product.published,false);assert.equal(await MarketplaceStore.getPublicProductBySlug(p.slug),null);});
test('internal notes absent from public API but admin can read them',async()=>{const p=await create({published:true,confirmWarnings:true,adminNote:'Private supplier'});const pub=await (await request('/marketplace/products/'+p.slug)).json();assert.ok(!JSON.stringify(pub).includes('Private supplier'));assert.equal((await MarketplaceStore.getAdminProducts())[0].adminNote,'Private supplier');});
test('readiness blocks impossible physical direct purchase',()=>{assert.ok(productReadiness({name:'Laptop',category:'laptops_computers',productKind:'physical',priceType:'fixed',priceMinor:10000,fulfilmentMode:'pickup',pickupLocations:[]}).blockers.some(b=>b.includes('pickup')));});
test('missing image yields warning without blocker',()=>{const ready=productReadiness({name:'Subscription',category:'digital_products',productKind:'digital',priceType:'fixed',priceMinor:19900,fulfilmentMode:'digital_delivery'});assert.equal(ready.blockers.length,0);assert.ok(ready.warnings.includes('No product image.'));});
test('publish warnings require explicit confirmation',async()=>{const p=await create();assert.equal((await action(p.id,'publish')).status,409);assert.equal((await action(p.id,'publish',{confirmWarnings:true})).status,200);});
test('publishing draft missing category is blocked even when warnings confirmed',async()=>{const p=await create({category:''});assert.equal((await action(p.id,'publish',{confirmWarnings:true})).status,400);});
test('published PATCH cannot bypass readiness and category checks',async()=>{const p=await create({published:true,confirmWarnings:true});assert.equal((await request(`/admin/marketplace/products/${p.id}`,'PATCH',{priceMinor:0,confirmWarnings:true})).status,400);assert.equal((await MarketplaceStore.getProductById(p.id))!.price_minor,19900);});
test('sort control persists; renaming preserves existing URL',async()=>{const p=await create({published:true,confirmWarnings:true});await request(`/admin/marketplace/products/${p.id}`,'PATCH',{sortOrder:5,name:'Renamed Subscription',confirmWarnings:true});const raw=await MarketplaceStore.getProductById(p.id);assert.equal(raw!.sort_order,5);assert.equal(raw!.slug,p.slug);assert.ok(await MarketplaceStore.getPublicProductBySlug(p.slug));});
test('feature, unfeature, archive, publish, unpublish all retain expected public filtering',async()=>{const p=await create();await action(p.id,'publish',{confirmWarnings:true});await action(p.id,'feature');assert.equal((await MarketplaceStore.getPublicProducts({featured:true})).length,1);await action(p.id,'unfeature');assert.equal((await MarketplaceStore.getPublicProducts({featured:true})).length,0);await action(p.id,'unpublish');assert.equal((await MarketplaceStore.getPublicProducts()).length,0);await action(p.id,'publish',{confirmWarnings:true});await action(p.id,'archive');assert.equal((await MarketplaceStore.getPublicProducts()).length,0);});
test('digital checkout requires neither pickup nor delivery address',async()=>{const p=await create({published:true,confirmWarnings:true});const response=await checkout(p);assert.equal(response.status,200);const orders=await OrdersStore.adminDevOrders();assert.equal(orders[0].fulfilment_method,'digital_delivery');assert.equal(orders[0].delivery_city,null);assert.equal(orders[0].pickup_location_id,null);assert.equal(orders[0].supplier_provider,'manual_supplier');assert.equal(orders[0].status,'pending_payment');});
test('service manual activation supports payment and remains manual',async()=>{const p=await create({productKind:'service',fulfilmentMode:'manual_activation',published:true,confirmWarnings:true});assert.equal((await checkout(p)).status,200);assert.equal((await OrdersStore.adminDevOrders())[0].supplier_order_id,null);});
test('inquiry-only service cannot create a payment order',async()=>{const p=await create({productKind:'service',fulfilmentMode:'inquiry_only',published:true,confirmWarnings:true});assert.equal(p.purchaseEnabled,false);assert.equal((await checkout(p)).status,400);assert.equal((await OrdersStore.adminDevOrders()).length,0);});
test('digital identifier is required server-side and length limited',async()=>{const p=await create({fulfilmentIdentifierLabel:'Account email',fulfilmentIdentifierRequired:true,published:true,confirmWarnings:true});assert.equal((await checkout(p)).status,400);assert.equal((await checkout(p,{fulfilmentIdentifier:'a'.repeat(201)})).status,400);assert.equal((await checkout(p,{fulfilmentIdentifier:'account@example.com'})).status,200);});
for(const label of ['Account password','One-time code','Security PIN','Account pass.word'])test(`credential collection configuration rejected: ${label}`,async()=>{assert.equal((await request('/admin/marketplace/products','POST',input({fulfilmentIdentifierLabel:label}))).status,400);});
test('external password field rejected at checkout',async()=>{const p=await create({published:true,confirmWarnings:true});assert.equal((await checkout(p,{password:'do-not-store'})).status,400);assert.equal((await OrdersStore.adminDevOrders()).length,0);});
test('digital checkout rejects forged physical method',async()=>{const p=await create({published:true,confirmWarnings:true});assert.equal((await checkout(p,{fulfilmentMethod:'delivery',deliveryCity:'Accra',deliveryArea:'Central'})).status,400);});
test('physical pickup payment stores configured location snapshot',async()=>{const p=await create({productKind:'physical',fulfilmentMode:'pickup',pickupLocations:pickup,published:true,confirmWarnings:true});assert.equal((await checkout(p,{fulfilmentMethod:'pickup',pickupLocationId:'loc_fixture'})).status,200);assert.match((await OrdersStore.adminDevOrders())[0].pickup_location_snapshot!,/Fixture Hub/);});
test('physical delivery payment still requires city and area',async()=>{const p=await create({productKind:'physical',fulfilmentMode:'delivery',published:true,confirmWarnings:true});assert.equal((await checkout(p,{fulfilmentMethod:'delivery'})).status,400);assert.equal((await checkout(p,{fulfilmentMethod:'delivery',deliveryCity:'Accra',deliveryArea:'Central'})).status,200);});
test('inactive pickup location rejected',async()=>{const p=await raw({productKind:'physical',fulfilmentMode:'pickup',pickupLocations:pickup.map(l=>({...l,active:false}))});assert.throws(()=>marketplaceFulfilment(p,{fulfilmentMethod:'pickup',pickupLocationId:'loc_fixture'}));});
test('variant controls authoritatively price Paystack, ignoring client amount',async()=>{const p=await create({published:true,confirmWarnings:true,variants:[{id:'three_months',name:'3 months',priceMinor:19900,active:true}]});assert.equal((await checkout(p,{variantId:'bad',amount:1})).status,400);assert.equal((await checkout(p,{variantId:'three_months',amount:1})).status,200);const orders=await OrdersStore.adminDevOrders();assert.equal(orders[0].amount,19900);assert.equal(orders[0].variant_snapshot,'3 months');assert.equal((PaystackServerService.initializeTransaction as any).mock.calls[0].arguments[0].amountPesewas,19900);});
test('order snapshot remains immutable after product changes and identifiers are admin-only',async()=>{const p=await create({published:true,confirmWarnings:true,fulfilmentIdentifierLabel:'Account email',fulfilmentIdentifierRequired:true,purchaseNote:'Original terms'});await checkout(p,{fulfilmentIdentifier:'account@example.com'});await request(`/admin/marketplace/products/${p.id}`,'PATCH',{purchaseNote:'New terms',fulfilmentIdentifierLabel:'Username',confirmWarnings:true});const order=(await OrdersStore.adminDevOrders())[0];assert.equal(order.marketplace_context!.purchaseNote,'Original terms');assert.equal(order.marketplace_context!.identifierLabel,'Account email');assert.equal(toAdminOrderDetails(order).marketplace_context!.identifierValue,'account@example.com');assert.ok(!JSON.stringify(toSafePublicOrder(order)).includes('account@example.com'));});
async function inquiry(name='Inquiry Fixture'){return MarketplaceStore.createInquiry({productName:name,customerName:'Fixture Customer',customerPhone:'0241234567',message:'Need a subscription',budget:'GH₵199'});}
test('customer inquiry appears in admin inbox',async()=>{const res=await request('/marketplace/inquiries','POST',{productName:'Fixture Cloud',customerName:'Fixture Customer',customerPhone:'0241234567',message:'Availability?'},null);assert.equal(res.status,200);const list=await (await request('/admin/marketplace/inquiries')).json();assert.equal(list.total,1);assert.equal(list.inquiries[0].product_name,'Fixture Cloud');});
test('inquiry status filters, contact timestamp and resolved status work',async()=>{const row=await inquiry();await request('/admin/marketplace/inquiries/'+row.id,'PATCH',{status:'contacted'});const contacted=await MarketplaceControlStore.listInquiries({status:'contacted'});assert.equal(contacted.total,1);assert.ok(contacted.inquiries[0].contacted_at);await request('/admin/marketplace/inquiries/'+row.id,'PATCH',{status:'resolved'});assert.equal((await MarketplaceControlStore.listInquiries({status:'resolved'})).total,1);assert.equal((await MarketplaceControlStore.listInquiries({status:'new'})).total,0);});
test('inquiry notes persist and do not modify product or public payload',async()=>{const p=await create({published:true,confirmWarnings:true});const row=await inquiry();const before=JSON.stringify(await MarketplaceStore.getPublicProductBySlug(p.slug));await request('/admin/marketplace/inquiries/'+row.id,'PATCH',{adminNote:'Private follow up'});assert.equal((await MarketplaceControlStore.listInquiries()).inquiries[0].admin_note,'Private follow up');assert.equal(JSON.stringify(await MarketplaceStore.getPublicProductBySlug(p.slug)),before);});
test('inquiry search/product filters and pagination return correct total',async()=>{const p=await create();await MarketplaceStore.createInquiry({productId:p.id,productName:'Cloud Subscription'});await inquiry('Laptop');assert.equal((await MarketplaceControlStore.listInquiries({search:'cloud'})).total,1);assert.equal((await MarketplaceControlStore.listInquiries({productId:p.id})).total,1);const page=await MarketplaceControlStore.listInquiries({page:2,pageSize:1});assert.equal(page.total,2);assert.equal(page.inquiries.length,1);});
test('inquiries can be closed and reopened; first contact time retained',async()=>{const row=await inquiry();await MarketplaceControlStore.updateInquiry(row.id,{status:'contacted'},'admin');const original=(await MarketplaceControlStore.listInquiries()).inquiries[0].contacted_at;await MarketplaceControlStore.updateInquiry(row.id,{status:'closed'},'admin');await MarketplaceControlStore.updateInquiry(row.id,{status:'new'},'admin');assert.equal((await MarketplaceControlStore.listInquiries()).inquiries[0].contacted_at,original);});
test('invalid inquiry status or pagination rejected',async()=>{const row=await inquiry();assert.equal((await request('/admin/marketplace/inquiries/'+row.id,'PATCH',{status:'paid'})).status,400);assert.equal((await request('/admin/marketplace/inquiries?page=-1')).status,400);});
test('enum values must be strings rather than coercible arrays',async()=>{for(const [field,value] of [['productKind','digital'],['priceType','fixed'],['availability','available']])assert.equal((await request('/admin/marketplace/products','POST',input({[field]:[value]}))).status,400);const row=await inquiry();assert.equal((await request('/admin/marketplace/inquiries/'+row.id,'PATCH',{status:['contacted']})).status,400);assert.equal(sanitizeExtractionResult({productKind:['digital'],availability:['in_stock']}).productKind,null);});
for(const path of ['/admin/marketplace/products','/admin/marketplace/categories','/admin/marketplace/inquiries'])test(`RBAC protects ${path}`,async()=>{assert.equal((await request(path,'GET',undefined,null)).status,401);assert.equal((await request(path,'GET',undefined,'customer-token')).status,403);});
test('RBAC protects inquiry and category mutation',async()=>{const row=await inquiry();assert.equal((await request('/admin/marketplace/inquiries/'+row.id,'PATCH',{status:'contacted'},'customer-token')).status,403);assert.equal((await request('/admin/marketplace/categories','POST',{slug:'private',label:'Private'},'customer-token')).status,403);});
test('WhatsApp action only builds valid Ghana phone link, no message',()=>{assert.equal(whatsappLink('024 123 4567'),'https://wa.me/233241234567');assert.equal(whatsappLink('+233241234567'),'https://wa.me/233241234567');assert.equal(whatsappLink('bad'),null);assert.equal(whatsappLink('123'),null);});
test('metrics include product kinds, needs review, new inquiries and original counters',async()=>{await create();await create({productKind:'physical',fulfilmentMode:'both'});await create({productKind:'service',fulfilmentMode:'manual_activation'});await inquiry();const metrics=(await (await request('/admin/marketplace/metrics')).json()).metrics;assert.equal(metrics.total,3);assert.equal(metrics.drafts,3);assert.equal(metrics.digital,1);assert.equal(metrics.physical,1);assert.equal(metrics.service,1);assert.equal(metrics.newInquiries,1);assert.equal(metrics.needsReview,3);});
test('duplicate, restore, categories and inquiry changes audit without notes or identifiers',async()=>{const p=await create({adminNote:'Never audit this private note'});const row=await inquiry();await action(p.id,'duplicate');await action(p.id,'archive');await action(p.id,'restore');await MarketplaceControlStore.saveCategory({label:'Updated label'},'admin','digital_products');await MarketplaceControlStore.updateInquiry(row.id,{status:'contacted',adminNote:'Never audit this inquiry note'},'admin');const logs=await AdminAuditStore.findRecent(100);for(const action of ['marketplace_product_duplicated','marketplace_product_restored','marketplace_category_updated','marketplace_inquiry_updated'])assert.ok(logs.some(l=>l.action===action));assert.ok(!JSON.stringify(logs).includes('Never audit'));});
for(const [field,value] of [['imageUrl','javascript:alert(1)'],['priceGhc',-1],['priceGhc','199'],['availability','fake'],['sortOrder',-1],['fulfilmentIdentifierLabel','<b>Email</b>'],['adminNote','a'.repeat(1001)]])test(`server rejects invalid ${field}`,async()=>{assert.equal((await request('/admin/marketplace/products','POST',input({[field as string]:value}))).status,400);});
test('repeatable schema is additive, preserves seed edits and historical orders',()=>{assert.match(MARKETPLACE_FLEXIBILITY_SCHEMA,/ON CONFLICT \(slug\) DO NOTHING/);assert.match(MARKETPLACE_FLEXIBILITY_SCHEMA,/product_kind.*DEFAULT 'physical'/);assert.match(MARKETPLACE_FLEXIBILITY_SCHEMA,/marketplace_context JSONB/);assert.ok(!/DROP|DELETE FROM|UPDATE orders|UPDATE marketplace_products/.test(MARKETPLACE_FLEXIBILITY_SCHEMA));});
import { MARKETPLACE_LIMITS } from '../../../shared/marketplaceLimits.js';
const hardeningVariants=[{id:'entry',name:'8GB / 256GB',priceMinor:360000,active:true},{id:'middle',name:'16GB / 512GB',priceMinor:410000,active:true},{id:'premium',name:'32GB / 1TB',priceMinor:490000,active:true}];
test('hardening: public From price uses cheapest valid active option while admin retains base',async()=>{const p=await raw({priceGhc:9999,variants:[...hardeningVariants,{id:'inactive',name:'Unavailable',priceMinor:100,active:false}]});const pub=toPublicMarketplaceProduct(p);assert.equal(pub.priceType,'starting_at');assert.equal(pub.priceMinor,360000);assert.match(pub.priceDisplay,/From.*3,600/);assert.equal(toAdminMarketplaceProduct(p).priceMinor,999900);});
test('hardening: stale or foreign variant fails before order or payment initialization',async()=>{const p=await create({published:true,confirmWarnings:true,variants:hardeningVariants});for(const variantId of ['deleted','other_product_option'])assert.equal((await checkout(p,{variantId})).status,400);assert.equal((await OrdersStore.adminDevOrders()).length,0);assert.equal((PaystackServerService.initializeTransaction as any).mock.calls.length,0);});
test('hardening: inactive variant cannot be purchased',async()=>{const p=await create({published:true,confirmWarnings:true,variants:hardeningVariants.map(v=>({...v,active:v.id!=='middle'}))});assert.equal((await checkout(p,{variantId:'middle'})).status,400);assert.equal((await OrdersStore.adminDevOrders()).length,0);});
test('hardening: no active option never falls back to base price',async()=>{const p=await create({published:true,confirmWarnings:true,variants:hardeningVariants.map(v=>({...v,active:false}))});assert.equal((await checkout(p)).status,400);assert.equal(toPublicMarketplaceProduct((await MarketplaceStore.getProductById(p.id))!).purchaseEnabled,false);assert.equal((await OrdersStore.adminDevOrders()).length,0);});
test('hardening: physical selection snapshots product, option and authoritative price',async()=>{const p=await create({productKind:'physical',fulfilmentMode:'delivery',published:true,confirmWarnings:true,variants:hardeningVariants});assert.equal((await checkout(p,{fulfilmentMethod:'delivery',deliveryCity:'Accra',deliveryArea:'Central',variantId:'middle',priceMinor:1,amount:1})).status,200);const o=(await OrdersStore.adminDevOrders())[0];assert.equal(o.product_id,p.id);assert.equal(o.variant_id,'middle');assert.equal(o.variant_snapshot,'16GB / 512GB');assert.equal(o.amount,410000);assert.equal((PaystackServerService.initializeTransaction as any).mock.calls[0].arguments[0].amountPesewas,410000);});
test('hardening: digital duration option stores no physical fulfilment columns',async()=>{const p=await create({published:true,confirmWarnings:true,variants:[{id:'annual',name:'12 months',priceMinor:29900}]});assert.equal((await checkout(p,{variantId:'annual'})).status,200);const o=(await OrdersStore.adminDevOrders())[0];assert.equal(o.variant_snapshot,'12 months');assert.equal(o.amount,29900);assert.equal(o.delivery_area,null);assert.equal(o.pickup_location_id,null);});
test('hardening: inquiry-only save and update turn direct purchase off in storage',async()=>{const p=await create({productKind:'service',fulfilmentMode:'inquiry_only',purchaseEnabled:true});assert.equal((await MarketplaceStore.getProductById(p.id))!.purchase_enabled,false);await request('/admin/marketplace/products/'+p.id,'PATCH',{purchaseEnabled:true});assert.equal((await MarketplaceStore.getProductById(p.id))!.purchase_enabled,false);});
for(const [field,limit] of [['name',MARKETPLACE_LIMITS.productName],['badge',MARKETPLACE_LIMITS.badge],['availabilityLabel',MARKETPLACE_LIMITS.availabilityLabel]] as const){
 test(`hardening: ${field} at PostgreSQL boundary persists`,async()=>{const p=await create({[field]:'x'.repeat(limit)});const saved=(await MarketplaceStore.getProductById(p.id))!;assert.equal((saved as any)[field==='availabilityLabel'?'availability_label':field].length,limit);});
 test(`hardening: ${field} one over boundary returns safe 400`,async()=>{const res=await request('/admin/marketplace/products','POST',input({[field]:'x'.repeat(limit+1)}));assert.equal(res.status,400);assert.equal((await MarketplaceStore.getAdminProducts()).length,0);});
}
for(const [field,limit] of [['variantId',MARKETPLACE_LIMITS.variantId],['pickupId',MARKETPLACE_LIMITS.pickupId]] as const){
 test(`hardening: ${field} exact boundary persists through checkout`,async()=>{const id='x'.repeat(limit);const p=await create({productKind:'physical',fulfilmentMode:'pickup',published:true,confirmWarnings:true,pickupLocations:[{...pickup[0],id:field==='pickupId'?id:'hub'}],variants:[{id:field==='variantId'?id:'option',name:'Option',priceMinor:10000}]});assert.equal((await checkout(p,{fulfilmentMethod:'pickup',pickupLocationId:field==='pickupId'?id:'hub',variantId:field==='variantId'?id:'option'})).status,200);const o=(await OrdersStore.adminDevOrders())[0];assert.equal((o as any)[field==='variantId'?'variant_id':'pickup_location_id'],id);});
 test(`hardening: ${field} one over boundary rejected before persistence`,async()=>{const extra=field==='variantId'?{variants:[{id:'x'.repeat(limit+1),name:'Option',priceMinor:10000}]}:{pickupLocations:[{...pickup[0],id:'x'.repeat(limit+1)}]};assert.equal((await request('/admin/marketplace/products','POST',input(extra))).status,400);});
}
test('hardening: delivery area 128 persists; 129 rejected without order',async()=>{const p=await create({productKind:'physical',fulfilmentMode:'delivery',published:true,confirmWarnings:true});assert.equal((await checkout(p,{fulfilmentMethod:'delivery',deliveryCity:'Accra',deliveryArea:'x'.repeat(129)})).status,400);assert.equal((await OrdersStore.adminDevOrders()).length,0);assert.equal((await checkout(p,{fulfilmentMethod:'delivery',deliveryCity:'Accra',deliveryArea:'x'.repeat(128)})).status,200);assert.equal((await OrdersStore.adminDevOrders())[0].delivery_area!.length,128);});
test('hardening: inquiry name 255 persists; 256 rejects cleanly',async()=>{await MarketplaceStore.createInquiry({productName:'x'.repeat(255)});await assert.rejects(MarketplaceStore.createInquiry({productName:'x'.repeat(256)}),/255/);assert.equal((await MarketplaceControlStore.listInquiries()).total,1);});
test('hardening: maximum name duplicate and repeated duplication remain bounded with unique slugs',async()=>{const p=await create({name:'x'.repeat(256),priceGhc:9999,variants:hardeningVariants});const first=(await (await action(p.id,'duplicate')).json()).product;const second=(await (await action(first.id,'duplicate')).json()).product;assert.equal(first.name.length,256);assert.equal(second.name.length,256);assert.match(first.name,/^Copy of /);assert.match(second.name,/^Copy of Copy of /);assert.notEqual(first.slug,p.slug);assert.notEqual(second.slug,first.slug);assert.equal(first.priceMinor,999900);assert.equal(first.published,false);});
test('hardening: AI draft text also respects storage label and badge boundaries',()=>{const draft=sanitizeExtractionResult({name:'x'.repeat(300),badge:'b'.repeat(100),availabilityLabel:'a'.repeat(150)});assert.equal(draft.name.length,256);assert.equal(draft.badge!.length,64);assert.equal(draft.availabilityLabel!.length,64);});
test('hardening: malformed stored options do not turn into a base-price purchase',async()=>{const p=await create({published:true,confirmWarnings:true});const original=(await MarketplaceStore.getProductById(p.id))!;for(const variants of ['[{"id":"broken","name":"Broken","priceMinor":"19900"}]','not-json']){const record={...original,variants};assert.equal(toPublicMarketplaceProduct(record).purchaseEnabled,false);assert.equal(toPublicMarketplaceProduct(record).priceMinor,null);mock.method(MarketplaceStore,'getProductById',async()=>record);assert.equal((await checkout(p)).status,400);mock.restoreAll();}assert.equal((await OrdersStore.adminDevOrders()).length,0);});
test('hardening: long valid product and option names fit legacy order columns without losing full context',async()=>{const p=await create({name:'n'.repeat(256),published:true,confirmWarnings:true,variants:[{id:'long_option',name:'v'.repeat(150),priceMinor:19900}]});assert.equal((await checkout(p,{variantId:'long_option'})).status,200);const order=(await OrdersStore.adminDevOrders())[0];assert.equal(order.product_name_snapshot.length,MARKETPLACE_LIMITS.orderProductName);assert.equal(order.bundle_size_snapshot.length,MARKETPLACE_LIMITS.orderOptionLabel);assert.equal(order.variant_snapshot!.length,150);assert.equal(order.marketplace_context!.productName,'n'.repeat(256));});
import {initializePaymentOnServer,InitializeMarketplacePaymentRequest} from '../../../src/services/apiClient.js';
for (const [kind,mode] of [['physical','delivery'],['digital','digital_delivery'],['service','manual_activation']] as const) {
  for (const authenticated of [false,true]) {
    test(`integration cleanup: ${authenticated?'authenticated':'guest'} ${kind} checkout carries canonical receipt email end to end`,async()=>{
      const p=await create({productKind:kind,fulfilmentMode:mode,published:true,confirmWarnings:true});
      const originalFetch=globalThis.fetch;
      let submitted:any,headers:any;
      mock.method(globalThis,'fetch',(url:any,options:any)=>{
        if(String(url).endsWith('/api/payments/initialize')){
          submitted=JSON.parse(options.body);headers=options.headers;
          // Always target this isolated server, including with an inherited frontend API URL.
          return originalFetch(`${base}/api/payments/initialize`,options);
        }
        assert.ok(String(url).startsWith(base+'/'),'Unexpected external request in isolated test');
        return originalFetch(url,options);
      });
      const payload:InitializeMarketplacePaymentRequest={serviceType:'marketplace',productId:p.id,phone:'0241234567',customerName:'Synthetic Customer',customerEmail:'buyer@example.com',fulfilmentMethod:mode,...(kind==='physical'?{deliveryCity:'Accra',deliveryArea:'Central'}:{})};
      const result=await initializePaymentOnServer(payload,authenticated?'customer-token':null);
      assert.equal(result.success,true);
      assert.equal(submitted.customerEmail,'buyer@example.com');
      assert.equal(Object.hasOwn(submitted,'email'),false);
      assert.equal(headers.Authorization,authenticated?'Bearer customer-token':undefined);
      const order=(await OrdersStore.adminDevOrders())[0];
      assert.equal(order.customer_email,'buyer@example.com');
      assert.equal(order.user_id,authenticated?'customer':null);
      assert.equal((order.marketplace_context!.customerContact as any).email,'buyer@example.com');
      assert.equal(toAdminOrderDetails(order).customer_email,'buyer@example.com');
      const payment=(PaystackServerService.initializeTransaction as any).mock.calls[0].arguments[0];
      assert.equal(payment.email,'buyer@example.com');
      assert.equal(payment.metadata.service_type,'marketplace');
      assert.ok(!order.customer_email.endsWith('@customer.mysteryhub.site'));
    });
  }
}
test('integration cleanup: deployed Marketplace email alias is normalized and trimmed',async()=>{
  const p=await create({published:true,confirmWarnings:true});
  assert.equal((await checkout(p,{email:'  legacy@example.com  '})).status,200);
  assert.equal((await OrdersStore.adminDevOrders())[0].customer_email,'legacy@example.com');
  assert.equal((PaystackServerService.initializeTransaction as any).mock.calls[0].arguments[0].email,'legacy@example.com');
});
test('integration cleanup: canonical customerEmail takes precedence over legacy alias',async()=>{
  const p=await create({published:true,confirmWarnings:true});
  assert.equal((await checkout(p,{customerEmail:'canonical@example.com',email:'legacy@example.com'})).status,200);
  assert.equal((await OrdersStore.adminDevOrders())[0].customer_email,'canonical@example.com');
  assert.equal((PaystackServerService.initializeTransaction as any).mock.calls[0].arguments[0].email,'canonical@example.com');
});
test('integration cleanup: Paystack adapter forwards customer email in actual gateway request body',async()=>{
  mock.restoreAll();
  const previousKey=process.env.PAYSTACK_SECRET_KEY;
  process.env.PAYSTACK_SECRET_KEY='isolated-test-key-not-a-credential';
  let outgoing:any;
  mock.method(globalThis,'fetch',async(url:any,options:any)=>{
    assert.equal(url,'https://api.paystack.co/transaction/initialize');
    outgoing=JSON.parse(options.body);
    return new Response(JSON.stringify({status:true,data:{authorization_url:'https://checkout.paystack.com/isolated',access_code:'isolated',reference:'isolated-reference'}}),{status:200,headers:{'Content-Type':'application/json'}});
  });
  try {
    const result=await PaystackServerService.initializeTransaction({email:'buyer@example.com',amountPesewas:19900,reference:'isolated-reference',metadata:{service_type:'marketplace'}});
    assert.equal(result.success,true);
    assert.equal(outgoing.email,'buyer@example.com');
    assert.equal(outgoing.metadata.service_type,'marketplace');
    assert.equal(Object.hasOwn(outgoing,'customerEmail'),false);
  } finally {
    if(previousKey===undefined)delete process.env.PAYSTACK_SECRET_KEY;else process.env.PAYSTACK_SECRET_KEY=previousKey;
  }
});
