import assert from 'node:assert/strict';
import { test, before, after, beforeEach } from 'node:test';
import express from 'express';
import type { Server } from 'node:http';
import type { AddressInfo } from 'node:net';
import React from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import { readFileSync } from 'node:fs';
import { randomUUID } from 'node:crypto';
import { websiteRouter, handlePublicSiteBySlug } from '../../routes/websiteApi.js';
import { adminWebsiteRouter } from '../../routes/websiteFreeApi.js';
import { WebsiteStore } from '../../db/websiteStore.js';
import { WebsiteAssetStore } from '../../db/websiteAssetStore.js';
import { WebsiteAnalyticsStore, validateWebsiteAnalytics } from '../../db/websiteAnalyticsStore.js';
import { WebsiteCloudinary, cloudinarySignature, websiteMediaLimits } from '../../services/websiteCloudinary.js';
import { AuthStore } from '../../db/authStore.js';
import { AdminAuditStore } from '../../db/adminAuditStore.js';
import { createWebsiteComposition, SECTION_REGISTRY, websiteTemplateItemFields } from '../../../src/config/websiteBuilder.js';
import { websiteImageUrl } from '../../../src/config/websiteMedia.js';
import { WEBSITE_TEMPLATES } from '../../../src/data/templates.js';
import { getTemplateById, mergeSiteWithTemplate, renderTemplateLayout } from '../../../src/utils/templateRendererUtils.js';
import { websiteSocialUrl } from '../../../src/components/website/SiteContactDetails.js';
import { SafeImage } from '../../../src/components/website/SafeImage.js';
import { validateWebsiteContentPatch } from '../../services/websiteValidation.js';

let server:Server,base:string;
let resourceChanges:Record<string,unknown>, inspected:string[], destroyed:string[], providerFailure:boolean, deleteFailure:boolean;
const originalInspect=WebsiteCloudinary.inspect, originalDestroy=WebsiteCloudinary.destroy;
const envNames=['CLOUDINARY_CLOUD_NAME','CLOUDINARY_API_KEY','CLOUDINARY_API_SECRET','WEBSITE_FREE_MAX_ASSETS','WEBSITE_IMAGE_MAX_BYTES'];
const originalEnv=Object.fromEntries(envNames.map(name=>[name,process.env[name]]));
before(async()=>{
  assert.equal(process.env.NODE_ENV,'test');assert.equal(process.env.DATABASE_URL,undefined);
  WebsiteCloudinary.inspect=async(publicId)=>{inspected.push(publicId);if(providerFailure)throw new Error('Mock provider failed');return {public_id:publicId,resource_type:'image',type:'upload',format:'png',bytes:6000,width:640,height:480,secure_url:'https://malicious.example/not-trusted',version:7,...resourceChanges} as any;};
  WebsiteCloudinary.destroy=async(publicId)=>{destroyed.push(publicId);if(deleteFailure)throw new Error('Mock cleanup failed');};
  const app=express();app.use(express.json());app.use('/api/websites',websiteRouter);app.get('/api/public/sites/:slug',handlePublicSiteBySlug);app.use('/api/admin/website-builder',adminWebsiteRouter);
  server=await new Promise<Server>(resolve=>{const running=app.listen(0,'127.0.0.1',()=>resolve(running));});base=`http://127.0.0.1:${(server.address() as AddressInfo).port}`;
});
after(async()=>{WebsiteCloudinary.inspect=originalInspect;WebsiteCloudinary.destroy=originalDestroy;for(const name of envNames){if(originalEnv[name]===undefined)delete process.env[name];else process.env[name]=originalEnv[name];}await new Promise<void>(resolve=>server.close(()=>resolve()));});
beforeEach(async()=>{
  WebsiteStore.clearDevStore();WebsiteAssetStore.clearDevStore();WebsiteAnalyticsStore.clearDevStore();AuthStore._clearDevStore();
  process.env.CLOUDINARY_CLOUD_NAME='fixture-cloud';process.env.CLOUDINARY_API_KEY='fixture-key';process.env.CLOUDINARY_API_SECRET='fixture-secret';delete process.env.WEBSITE_FREE_MAX_ASSETS;delete process.env.WEBSITE_IMAGE_MAX_BYTES;
  resourceChanges={};inspected=[];destroyed=[];providerFailure=false;deleteFailure=false;
  for(const [id,role] of [['owner','customer'],['other','customer'],['admin','admin']] as const){await AuthStore.createUser({id,name:`${id} name`,email:`${id}@example.com`,phone:null,passwordHash:'fixture-hash',role,status:'active'});await AuthStore.createSession(id,`${id}-token`,false);}
});
const request=(path:string,method='GET',body?:unknown,token?:string)=>fetch(base+'/api/'+path,{method,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})},...(body===undefined?{}:{body:JSON.stringify(body)})});
const create=(userId='owner',template='tmpl-start-blank')=>WebsiteStore.createSite(userId,{template_id:template,name:'Ama Studio'});
const intent=async(siteId:string,token='owner-token',body:unknown={filename:'shop.png',mime:'image/png',bytes:6000})=>request(`websites/${siteId}/assets/upload-intent`,'POST',body,token);
const uploaded=async(siteId:string)=>{const {intent:reserved}=await (await intent(siteId)).json();const response=await request(`websites/${siteId}/assets/${reserved.assetId}/finalize`,'POST',{},'owner-token');assert.equal(response.status,200);return (await response.json()).asset;};
const event=(name:any='website_builder_viewed',metadata:any={source:'builder'},visitorId=randomUUID(),sessionId=randomUUID())=>({event:name,metadata,visitorId,sessionId});

test('test worker uses isolated memory with all provider mutations mocked',()=>{assert.equal(process.env.DATABASE_URL,undefined);assert.equal(process.env.NODE_ENV,'test');assert.notEqual(WebsiteCloudinary.inspect,originalInspect);assert.notEqual(WebsiteCloudinary.destroy,originalDestroy);});
test('signed parameters have deterministic documented SHA256 signature',()=>{assert.equal(cloudinarySignature({timestamp:'1',public_id:'sample'},'secret'),'b18479656cf9188ce3c9d9f7d7b2e97475a1123932017d1c8d3ea1a96c5819c0');});
test('upload intent controls namespace, formats, replay and short provider expiry',async()=>{const {site}=await create();const response=await intent(site.id);assert.equal(response.status,201);const data=await response.json();assert.equal(data.intent.parameters.public_id,`mysteryhub/websites/${site.id}/${data.intent.assetId}`);assert.equal(data.intent.parameters.overwrite,'false');assert.equal(data.intent.parameters.allowed_formats,'jpg,png,webp');assert.equal(data.intent.parameters.folder,undefined);assert.equal(data.intent.parameters.asset_folder,undefined);const remaining=Number(data.intent.parameters.timestamp)*1000+3600_000-Date.now();assert.ok(remaining>590_000 && remaining<=600_000);assert.ok(!JSON.stringify(data).includes('fixture-secret'));});
for(const token of [undefined,'bad-token','other-token'])test(`upload-intent rejects unauthenticated/non-owner ${token || 'guest'}`,async()=>{const {site}=await create();assert.equal((await request(`websites/${site.id}/assets/upload-intent`,'POST',{filename:'pic.jpg',mime:'image/jpeg',bytes:6000},token)).status,token==='other-token'?403:401);assert.equal((await WebsiteAssetStore.all()).length,0);});
for(const mime of ['image/svg+xml','video/mp4','image/gif','application/pdf','text/html'])test(`unsupported ${mime} rejected before reservation`,async()=>{const {site}=await create();assert.equal((await intent(site.id,'owner-token',{filename:'pic',mime,bytes:6000})).status,400);assert.equal((await WebsiteAssetStore.all()).length,0);});
for(const input of [{filename:'../../secret.png',mime:'image/png',bytes:1},{filename:'x.png',mime:'image/png',bytes:-1},{filename:'x.png',mime:'image/png',bytes:1.5},{filename:'x.png',mime:'image/png',bytes:1,publicId:'someone-else'},{filename:'x'.repeat(151),mime:'image/png',bytes:1}])test(`invalid intent ${JSON.stringify(input).slice(0,70)} rejected`,async()=>{const {site}=await create();assert.equal((await intent(site.id,'owner-token',input)).status,400);});
test('claimed oversize fails with 413 before provider call',async()=>{const {site}=await create();assert.equal((await intent(site.id,'owner-token',{filename:'large.png',mime:'image/png',bytes:8*1024*1024+1})).status,413);assert.equal(inspected.length,0);});
test('concurrent intents cannot bypass configured site limit',async()=>{process.env.WEBSITE_FREE_MAX_ASSETS='2';const {site}=await create();const results=await Promise.all(Array.from({length:7},()=>intent(site.id)));assert.equal(results.filter(r=>r.status===201).length,2);assert.equal(results.filter(r=>r.status===409).length,5);assert.equal((await WebsiteAssetStore.all()).length,2);});
test('unconfigured media returns truthful unavailable and no reserved/fake-ready asset',async()=>{delete process.env.CLOUDINARY_API_SECRET;const {site}=await create();assert.equal((await intent(site.id)).status,503);const list=await (await request(`websites/${site.id}/assets`,undefined,undefined,'owner-token')).json();assert.equal(list.configured,false);assert.deepEqual(list.assets,[]);assert.equal((await WebsiteAssetStore.all()).length,0);});
test('environment limit overrides are bounded and shared in listing',async()=>{process.env.WEBSITE_FREE_MAX_ASSETS='5';process.env.WEBSITE_IMAGE_MAX_BYTES='1048576';assert.deepEqual(websiteMediaLimits(),{maxAssets:5,maxBytes:1048576});process.env.WEBSITE_FREE_MAX_ASSETS='-1';process.env.WEBSITE_IMAGE_MAX_BYTES='999999999';assert.deepEqual(websiteMediaLimits(),{maxAssets:20,maxBytes:8388608});});
test('finalization independently verifies resource and reconstructs trusted original/optimized URL',async()=>{const {site}=await create();const asset=await uploaded(site.id);assert.equal(asset.status,'ready');assert.equal(asset.bytes,6000);assert.equal(asset.width,640);assert.equal(asset.height,480);assert.ok(asset.secure_url.startsWith('https://res.cloudinary.com/fixture-cloud/image/upload/v7/mysteryhub/websites/'));assert.ok(asset.delivery_url.includes('f_auto,q_auto,c_limit,w_1200/'));assert.equal(inspected[0],asset.public_id);assert.ok(!JSON.stringify(asset).includes('malicious.example'));assert.equal(asset.signature,undefined);});
for(const changes of [{resource_type:'video'},{type:'private'},{format:'svg'},{public_id:'arbitrary-id'},{width:0},{height:1e9},{version:-1},{bytes:-1}])test(`invalid verified provider resource ${JSON.stringify(changes)} never becomes ready`,async()=>{const {site}=await create();const {intent:upload}=await (await intent(site.id)).json();resourceChanges=changes;const response=await request(`websites/${site.id}/assets/${upload.assetId}/finalize`,'POST',{},'owner-token');assert.equal(response.status,400);assert.notEqual((await WebsiteAssetStore.find(upload.assetId))?.status,'ready');assert.equal(destroyed[0],upload.parameters.public_id);});
test('provider-reported actual oversize fails with 413 and expected-ID cleanup',async()=>{const {site}=await create();const {intent:upload}=await (await intent(site.id)).json();resourceChanges={bytes:8*1024*1024+1};assert.equal((await request(`websites/${site.id}/assets/${upload.assetId}/finalize`,'POST',{},'owner-token')).status,413);assert.equal(destroyed[0],upload.parameters.public_id);});
test('client finalization URL/bytes/publicId tampering rejected without inspecting resource',async()=>{const {site}=await create();const {intent:upload}=await (await intent(site.id)).json();assert.equal((await request(`websites/${site.id}/assets/${upload.assetId}/finalize`,'POST',{url:'https://evil.test',publicId:'arbitrary',bytes:1},'owner-token')).status,400);assert.equal(inspected.length,0);});
test('provider unavailable never marks asset ready and finalization can retry safely',async()=>{const {site}=await create();const {intent:upload}=await (await intent(site.id)).json();providerFailure=true;assert.equal((await request(`websites/${site.id}/assets/${upload.assetId}/finalize`,'POST',{},'owner-token')).status,503);assert.equal((await WebsiteAssetStore.find(upload.assetId))?.status,'pending');providerFailure=false;assert.equal((await request(`websites/${site.id}/assets/${upload.assetId}/finalize`,'POST',{},'owner-token')).status,200);});
test('concurrent duplicate finalization returns one stable ready asset',async()=>{const {site}=await create();const {intent:upload}=await (await intent(site.id)).json();const responses=await Promise.all(Array.from({length:3},()=>request(`websites/${site.id}/assets/${upload.assetId}/finalize`,'POST',{},'owner-token')));for(const response of responses)assert.equal(response.status,200);assert.equal((await WebsiteAssetStore.list(site.id,'owner')).length,1);});
test('expired finalization performs no provider call; reservation lasts through replay grace',async()=>{process.env.WEBSITE_FREE_MAX_ASSETS='1';const {site}=await create();const {intent:upload}=await (await intent(site.id)).json();const oldNow=Date.now;try{Date.now=()=>oldNow()+11*60_000;assert.equal((await request(`websites/${site.id}/assets/${upload.assetId}/finalize`,'POST',{},'owner-token')).status,409);assert.equal((await intent(site.id)).status,409);assert.equal(inspected.length,0);}finally{Date.now=oldNow;}});
test('expired orphan maintenance sweeps only tracked IDs after capability expiry',async()=>{const {site}=await create();const {intent:upload}=await (await intent(site.id)).json();const oldNow=Date.now;try{Date.now=()=>oldNow()+16*60_000;assert.deepEqual(await WebsiteAssetStore.cleanupCandidates(),{attempted:1,cleaned:1});assert.equal(destroyed[0],upload.parameters.public_id);assert.equal((await WebsiteAssetStore.find(upload.assetId))?.status,'deleted');}finally{Date.now=oldNow;}});
for(const action of ['list','finalize','delete'])test(`cross-owner asset ${action} blocked`,async()=>{const {site}=await create();const asset=await uploaded(site.id);const path=`websites/${site.id}/assets${action==='list'?'':`/${asset.id}${action==='finalize'?'/finalize':''}`}`;assert.equal((await request(path,action==='list'?'GET':action==='finalize'?'POST':'DELETE',action==='finalize'?{}:undefined,'other-token')).status,403);assert.equal(destroyed.length,0);});
test('cross-site managed asset attachment fails while external legacy URL is retained',async()=>{const {site}=await create();const asset=await uploaded(site.id);const other=await create('other');await assert.rejects(()=>WebsiteStore.updateSite(other.site.id,'other',{content:{heroImage:asset.secure_url}}),/verified image/);await WebsiteStore.updateSite(other.site.id,'other',{content:{heroImage:'https://images.example.com/legacy.jpg'}});assert.equal((await WebsiteStore.findSiteById(other.site.id))?.content_json.heroImage,'https://images.example.com/legacy.jpg');});
test('unfinalized managed URL cannot be attached through create/update',async()=>{const {site}=await create();const {intent:upload}=await (await intent(site.id)).json();const url=`https://res.cloudinary.com/fixture-cloud/image/upload/v7/${upload.parameters.public_id}.png`;await assert.rejects(()=>WebsiteStore.updateSite(site.id,'owner',{content:{heroImage:url}}));await assert.rejects(()=>WebsiteStore.createSite('other',{template_id:'tmpl-start-blank',name:'Other',content:{heroImage:url}}));});
test('ready asset reuses same-site image without duplicate provider upload',async()=>{const {site}=await create();const asset=await uploaded(site.id);const composition=createWebsiteComposition(['header','hero','gallery','footer']);composition.sections[2].data.items=[{title:'Shop',image:asset.secure_url}];await WebsiteStore.updateSite(site.id,'owner',{content:{heroImage:asset.secure_url,logoUrl:asset.secure_url,composition}});assert.equal((await WebsiteAssetStore.list(site.id,'owner')).length,1);});
for(const published of [false,true])test(`asset in-use deletion blocked for ${published?'published':'draft'} hero/item/section references`,async()=>{const {site}=await create();const asset=await uploaded(site.id);const composition=createWebsiteComposition(['header','gallery','footer']);composition.sections[1].enabled=false;composition.sections[1].data.items=[{title:'Shop',image:asset.secure_url}];await WebsiteStore.updateSite(site.id,'owner',{content:{composition}});if(published)await WebsiteStore.publishSite(site.id,'owner');const response=await request(`websites/${site.id}/assets/${asset.id}`,'DELETE',undefined,'owner-token');assert.equal(response.status,409);assert.ok((await response.json()).error.includes('gallery item'));assert.equal(destroyed.length,0);});
test('unused image deletion uses only persisted public ID and retains replay cleanup tombstone',async()=>{const {site}=await create();const asset=await uploaded(site.id);const response=await request(`websites/${site.id}/assets/${asset.id}`,'DELETE',undefined,'owner-token');assert.equal(response.status,200);assert.deepEqual(await WebsiteAssetStore.list(site.id,'owner'),[]);assert.equal(destroyed[0],asset.public_id);assert.equal((await WebsiteAssetStore.find(asset.id))?.status,'deleting');});
test('deleting image cannot be reattached; double-delete is safe',async()=>{const {site}=await create();const asset=await uploaded(site.id);await WebsiteAssetStore.delete(site.id,'owner',asset.id);await assert.rejects(()=>WebsiteStore.updateSite(site.id,'owner',{content:{heroImage:asset.secure_url}}));await WebsiteAssetStore.delete(site.id,'owner',asset.id);assert.equal((await WebsiteAssetStore.list(site.id,'owner')).length,0);});
test('provider-delete failure leaves durable cleanup state, never a selectable asset',async()=>{const {site}=await create();const asset=await uploaded(site.id);deleteFailure=true;assert.equal(await WebsiteAssetStore.delete(site.id,'owner',asset.id),false);assert.equal((await WebsiteAssetStore.find(asset.id))?.status,'deleting');assert.deepEqual(await WebsiteAssetStore.list(site.id,'owner'),[]);});
test('concurrent creation returns exactly one Free site',async()=>{const results=await Promise.all(Array.from({length:10},()=>create()));assert.equal(new Set(results.map(r=>r.site.id)).size,1);assert.equal(results.filter(r=>!r.alreadyExists).length,1);});
test('deletion requires independent typed confirmation and ownership',async()=>{const {site}=await create();for(const [token,confirmation,status] of [['owner-token','wrong',400],['other-token',site.slug,403],['bad-token',site.slug,401]] as const)assert.equal((await request(`websites/${site.id}`,'DELETE',{confirmation},token)).status,status);assert.ok(await WebsiteStore.findSiteById(site.id));});
test('confirmed deletion invalidates public route, releases Free slot, preserves customer and unrelated site',async()=>{const {site}=await create();await create('other');const account=await AuthStore.findUserById('owner');const asset=await uploaded(site.id);await WebsiteStore.publishSite(site.id,'owner');assert.equal((await request(`public/sites/${site.slug}`)).status,200);deleteFailure=true;const response=await request(`websites/${site.id}`,'DELETE',{confirmation:site.slug},'owner-token');assert.equal(response.status,200);assert.equal((await response.json()).cleanupPending,true);assert.equal((await request(`public/sites/${site.slug}`)).status,404);assert.equal((await WebsiteAssetStore.find(asset.id))?.website_id,null);assert.deepEqual(await AuthStore.findUserById('owner'),account);assert.equal((await WebsiteStore.findSitesByUserId('other')).length,1);assert.notEqual((await create()).site.id,site.id);});
test('public projection excludes ownership/session/provider fields and drafts remain private',async()=>{const {site}=await create();assert.equal((await request(`public/sites/${site.slug}`)).status,404);await WebsiteStore.publishSite(site.id,'owner');const publicSite=(await (await request(`public/sites/${site.slug}`)).json()).site;for(const key of ['user_id','owner','password_hash','sessionToken','assets','signature'])assert.equal(publicSite[key],undefined);await WebsiteStore.unpublishSite(site.id,'owner');assert.equal((await request(`public/sites/${site.slug}`)).status,404);});
for(const published of [false,true])test(`change template preserves identity/core/media and valid target sections on ${published?'published':'draft'}`,async()=>{const {site}=await create();const asset=await uploaded(site.id);const saved=await WebsiteStore.updateSite(site.id,'owner',{content:{businessName:'Ama real business',heroImage:asset.secure_url,logoUrl:asset.secure_url,whatsapp:'0241111111',email:'ama@example.com',ctaLabel:'Message Ama',ctaTarget:'https://example.com/contact',social:{instagram:'ama.studio'}},settings:{primaryColor:'#123456',accentColor:'#abcdef'}});if(published)await WebsiteStore.publishSite(site.id,'owner');const before=(await WebsiteStore.findSiteById(site.id))!;const response=await request(`websites/${site.id}/change-template`,'POST',{targetTemplateId:'tmpl-buka-bistro',confirmed:true,expectedUpdatedAt:before.updated_at},'owner-token');assert.equal(response.status,200);const changed=(await response.json()).site;for(const key of ['id','slug','user_id','status'] as const)assert.equal(changed[key],before[key]);for(const key of ['businessName','heroImage','logoUrl','whatsapp','email','ctaLabel','ctaTarget','social'] as const)assert.deepEqual(changed.content_json[key],saved!.content_json[key]);assert.deepEqual(changed.settings_json,before.settings_json);assert.equal((await WebsiteAssetStore.list(site.id,'owner')).length,1);assert.equal((await create()).alreadyExists,true);assert.equal(changed.content_json.composition.sections[0].type,'header');assert.equal(changed.content_json.composition.sections.at(-1).type,'footer');});
test('template migration keeps compatible section data/variants without injecting unsupported structures',async()=>{const {site}=await create();const composition=createWebsiteComposition(['header','hero','services','faq','footer']);composition.sections[1].variant='split';composition.sections[2].data.items=[{title:'Real service',text:'Details'}];await WebsiteStore.updateSite(site.id,'owner',{content:{composition}});const changed=await WebsiteStore.changeTemplate(site.id,'owner','tmpl-legon-consult');assert.deepEqual(changed.content_json.composition?.sections.find(s=>s.type==='services')?.data.items,composition.sections[2].data.items);assert.equal(changed.content_json.composition?.sections.find(s=>s.type==='hero')?.variant,'split');assert.ok(!changed.content_json.composition?.sections.some(s=>s.type==='faq'));for(const section of changed.content_json.composition!.sections)assert.ok((SECTION_REGISTRY[section.type].variants as readonly string[]).includes(section.variant));});
for(const body of [{targetTemplateId:'bad',confirmed:true},{targetTemplateId:'tmpl-buka-bistro',confirmed:false},{targetTemplateId:'tmpl-buka-bistro',confirmed:true,composition:{sections:[]}},{targetTemplateId:'tmpl-start-blank',confirmed:true}])test(`invalid template action is nonmutating ${JSON.stringify(body)}`,async()=>{const {site}=await create();const response=await request(`websites/${site.id}/change-template`,'POST',{expectedUpdatedAt:site.updated_at,...body},'owner-token');assert.equal(response.status,400);assert.deepEqual(await WebsiteStore.findSiteById(site.id),site);});
test('cross-owner migration blocked and stale save/change protected under concurrency',async()=>{const {site}=await create();assert.equal((await request(`websites/${site.id}/change-template`,'POST',{targetTemplateId:'tmpl-buka-bistro',confirmed:true,expectedUpdatedAt:site.updated_at},'other-token')).status,403);await WebsiteStore.updateSite(site.id,'owner',{content:{tagline:'New edit'}});assert.equal((await request(`websites/${site.id}/change-template`,'POST',{targetTemplateId:'tmpl-buka-bistro',confirmed:true,expectedUpdatedAt:site.updated_at},'owner-token')).status,409);assert.equal((await request(`websites/${site.id}`,'PATCH',{expectedUpdatedAt:site.updated_at,content:{tagline:'Stale edit'}},'owner-token')).status,409);assert.equal((await WebsiteStore.findSiteById(site.id))?.content_json.tagline,'New edit');});
test('two same-revision migrations cannot both overwrite',async()=>{const {site}=await create();const responses=await Promise.all(['tmpl-buka-bistro','tmpl-legon-consult'].map(targetTemplateId=>request(`websites/${site.id}/change-template`,'POST',{targetTemplateId,confirmed:true,expectedUpdatedAt:site.updated_at},'owner-token')));assert.deepEqual(responses.map(r=>r.status).sort(),[200,409]);});
test('all editor fields pass route/save/reload/publish/public-render roundtrip',async()=>{
  const {site}=await create();const asset=await uploaded(site.id);
  const composition=createWebsiteComposition(['header','hero','about','gallery','contact','location','footer']);
  composition.sections[1].variant='split';composition.sections[1].data={heading:'Edited hero',body:'Edited hero body',image:asset.secure_url,alt:'Shop banner',ctaLabel:'Hero action',ctaUrl:'https://example.com/hero'};
  composition.sections[2].data={heading:'Our real story',body:'Custom about body',ctaLabel:'About action',ctaUrl:'#contact-4'};
  composition.sections[3].data={heading:'Real gallery',body:'Gallery body',image:asset.secure_url,items:[{title:'Real item',text:'Item text',price:'GH₵42',image:asset.secure_url}]};
  const content={businessName:'Ama real name',tagline:'Real tagline',aboutText:'Real about',location:'Cape Coast real location',phone:'0241111111',whatsapp:'0552222222',email:'ama@example.com',heroImage:asset.secure_url,logoUrl:asset.secure_url,ctaLabel:'Talk to Ama',ctaTarget:'https://example.com/ama',social:{instagram:'ama',facebook:'ama.page',tiktok:'ama'},composition,items:[{id:'real-item',name:'Item name',desc:'Description',category:'Real category',price:'42',tag:'Popular',image:asset.secure_url}],stats:[{label:'Projects',value:'12'}],features:['Real feature']};
  const settings={primaryColor:'#123456',accentColor:'#abcdef',backgroundColor:'#fedcba'};
  const response=await request(`websites/${site.id}`,'PATCH',{name:'Actual project',content,settings,expectedUpdatedAt:site.updated_at},'owner-token');assert.equal(response.status,200);
  const loaded=(await (await request(`websites/${site.id}`,'GET',undefined,'owner-token')).json()).site;assert.deepEqual(loaded.content_json,content);assert.equal(loaded.name,'Actual project');assert.equal(loaded.settings_json.backgroundColor,'#fedcba');
  await request(`websites/${site.id}/publish`,'POST',{},'owner-token');const publicSite=(await (await request(`public/sites/${site.slug}`)).json()).site;assert.deepEqual(publicSite.content,content);
  const html=renderToStaticMarkup(renderTemplateLayout(mergeSiteWithTemplate(getTemplateById(publicSite.template_id),publicSite.content,publicSite.settings)));
  for(const text of ['Ama real name','Edited hero','Edited hero body','Our real story','Custom about body','Real gallery','Gallery body','Real item','Item text','GH₵42','Cape Coast real location','ama@example.com','0241111111','0552222222','Hero action','https://example.com/hero','About action','#123456','#abcdef','#fedcba'])assert.ok(html.includes(text),text);
  assert.ok(html.includes('logo'));assert.ok(html.includes('loading="lazy"'));assert.ok(html.includes('loading="eager"'));
});
test('legacy layouts render saved contacts/logo/social/CTA/colors and external image',async()=>{const {site}=await create('owner','tmpl-buka-bistro');const content={phone:'0241111111',whatsapp:'0552222222',email:'ama@example.com',logoUrl:'https://example.com/logo.png',heroImage:'https://example.com/hero.jpg',ctaLabel:'Contact Ama',ctaTarget:'https://example.com/action',social:{instagram:'ama',facebook:'ama',tiktok:'ama'}};await WebsiteStore.updateSite(site.id,'owner',{content,settings:{primaryColor:'#123456',accentColor:'#abcdef',backgroundColor:'#fedcba'}});const saved=(await WebsiteStore.findSiteById(site.id))!;const html=renderToStaticMarkup(renderTemplateLayout(mergeSiteWithTemplate(getTemplateById(saved.template_id),saved.content_json,saved.settings_json)));for(const text of ['0241111111','0552222222','ama@example.com','https://example.com/logo.png','https://example.com/hero.jpg','Contact Ama','https://example.com/action','instagram.com/ama','facebook.com/ama','tiktok.com/@ama','#123456','#abcdef','#fedcba'])assert.ok(html.includes(text),text);assert.ok(html.includes('--website-primary'));});
test('cleared business lists never resurrect template items including reseller fallback',async()=>{const {site}=await create('owner','tmpl-data-reseller');await WebsiteStore.updateSite(site.id,'owner',{content:{items:[],features:[],stats:[]}});const saved=(await WebsiteStore.findSiteById(site.id))!;const merged=mergeSiteWithTemplate(getTemplateById(saved.template_id),saved.content_json);assert.deepEqual(merged.items,[]);assert.deepEqual(merged.stats,[]);assert.deepEqual(merged.features,[]);const html=renderToStaticMarkup(renderTemplateLayout(merged));assert.ok(!html.includes('sample-mtn'));assert.ok(!html.includes('1GB Non-Expiry'));});
test('Cloudinary optimization preserves original and leaves external URLs unchanged',()=>{const original='https://res.cloudinary.com/fixture-cloud/image/upload/v7/mysteryhub/websites/site-1/asset-1.png';assert.ok(websiteImageUrl(original,400).includes('f_auto,q_auto,c_limit,w_400/'));assert.ok(websiteImageUrl(original,99999).includes('w_1600'));for(const url of ['https://example.com/res.cloudinary.com/pic.jpg','https://example.com/pic.jpg','/image.png','https://res.cloudinary.com/demo/image/upload/f_auto,q_auto/v1/image.jpg'])assert.equal(websiteImageUrl(url),url);const html=renderToStaticMarkup(React.createElement(SafeImage,{src:original,alt:'Shop',className:'aspect-square'}));assert.ok(html.includes('w_800'));assert.ok(html.includes('aspect-square'));});
for(const content of [{email:'bad-email'},{phone:'call me'},{whatsapp:'123'},{heroImage:'javascript:alert(1)'},{logoUrl:'//evil.test/image'},{ctaTarget:'javascript:alert(1)'},{stats:[{label:'<script>',value:'1'}]},{features:['<img>']},{items:[{name:'good',image:'data:image/svg+xml,bad'}]},{tagline:'x'.repeat(151)},{social:{instagram:'javascript:alert(1)'}}])test(`unsafe/oversized editor patch fails atomically ${Object.keys(content)[0]}`,async()=>{const {site}=await create();assert.equal((await request(`websites/${site.id}`,'PATCH',{content},'owner-token')).status,400);assert.deepEqual((await WebsiteStore.findSiteById(site.id))?.content_json,site.content_json);});
test('social helper never turns unsafe URL/username into active links',()=>{assert.equal(websiteSocialUrl('instagram','https://evil.test'), '');assert.equal(websiteSocialUrl('instagram','javascript:alert(1)'), '');assert.equal(websiteSocialUrl('tiktok','@ama'),'https://www.tiktok.com/@ama');});
for(const input of [event('website_created'),event('unknown_event'),event('website_builder_viewed',{email:'secret@example.com'}),event('website_builder_viewed',{templateId:'fake'}),{...event(),visitorId:'fingerprint'},event('website_builder_viewed',{source:'https://example.com/?token=secret'}),{...event(),metadata:{source:'builder',notes:'x'.repeat(900)}}])test(`analytics strict allowlist rejects ${JSON.stringify(input).slice(0,70)}`,async()=>{assert.throws(()=>validateWebsiteAnalytics(input));assert.equal((await request('websites/analytics','POST',input)).status,400);assert.equal((await WebsiteAnalyticsStore.events(null)).length,0);});
test('anonymous analytics use random UUIDs; authenticated event attribution is server-resolved',async()=>{const input=event();assert.equal((await request('websites/analytics','POST',input)).status,202);assert.equal((await request('websites/analytics','POST',event(), 'owner-token')).status,202);const events=await WebsiteAnalyticsStore.events(null);assert.equal(events[0].user_id,null);assert.equal(events[0].visitor_id,input.visitorId);assert.equal(events[1].user_id,'owner');assert.deepEqual(Object.keys(events[0].metadata_json),['source']);});
for(const authorization of ['Bearer bad-token','Basic fake','Bearer'])test(`invalid supplied analytics credential ${authorization} does not downgrade to guest`,async()=>{const response=await fetch(`${base}/api/websites/analytics`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:authorization},body:JSON.stringify(event())});assert.equal(response.status,401);assert.equal((await WebsiteAnalyticsStore.events(null)).length,0);});
test('editor analytics require authenticated ownership and cannot expose another site',async()=>{const {site}=await create();assert.equal((await request('websites/analytics','POST',event('website_editor_opened',{siteId:site.id}))).status,401);assert.equal((await request('websites/analytics','POST',event('website_editor_opened',{siteId:site.id}),'other-token')).status,403);assert.equal((await request('websites/analytics','POST',event('website_editor_opened',{siteId:site.id}),'owner-token')).status,202);});
test('server records authoritative lifecycle actions, client cannot fabricate them',async()=>{const response=await request('websites','POST',{templateId:'tmpl-start-blank',name:'Site'},'owner-token');const {site}=await response.json();await request(`websites/${site.id}/publish`,'POST',{},'owner-token');await request(`websites/${site.id}/unpublish`,'POST',{},'owner-token');const current=(await WebsiteStore.findSiteById(site.id))!;await request(`websites/${site.id}/change-template`,'POST',{targetTemplateId:'tmpl-legon-consult',confirmed:true,expectedUpdatedAt:current.updated_at},'owner-token');await request(`websites/${site.id}`,'DELETE',{confirmation:site.slug},'owner-token');assert.deepEqual((await WebsiteAnalyticsStore.events(null)).map(e=>e.event_name),['website_created','website_published','website_unpublished','website_template_changed','website_deleted']);});
test('analytics persistence failure cannot prevent successful website creation',async()=>{const original=WebsiteAnalyticsStore.action;try{WebsiteAnalyticsStore.action=async()=>{};assert.equal((await request('websites','POST',{templateId:'tmpl-start-blank'},'owner-token')).status,201);}finally{WebsiteAnalyticsStore.action=original;}});
for(const token of [undefined,'owner-token','bad-token'])test(`admin summary/inspection/moderation reject ${token || 'guest'}`,async()=>{const {site}=await create();for(const [path,method,body] of [['admin/website-builder','GET',undefined],[`admin/website-builder/${site.id}`,'GET',undefined],[`admin/website-builder/${site.id}/force-unpublish`,'POST',{confirmation:site.slug}]] as const)assert.equal((await request(path,method,body,token)).status,token==='owner-token'?403:401);});
test('Admin summary has actual counts, search/status/template filters and safe owner projection',async()=>{const first=await create();await create('other','tmpl-legon-consult');await WebsiteStore.publishSite(first.site.id,'owner');await uploaded(first.site.id);const response=await request('admin/website-builder?range=all&search=Ama&status=published&template=tmpl-start-blank','GET',undefined,'admin-token');assert.equal(response.status,200);const summary=await response.json();assert.deepEqual(summary.metrics,{total:2,draft:1,published:1,free:2});assert.equal(summary.total,1);assert.equal(summary.sites[0].ownerName,'owner name');assert.equal(summary.sites[0].assetCount,1);assert.equal(summary.sites[0].publicUrl,`/sites/${first.site.slug}`);for(const value of ['fixture-secret','fixture-key','fixture-hash','owner-token','owner@example.com'])assert.ok(!JSON.stringify(summary).includes(value));});
test('funnel distinguishes unique visitors from repeated events and ordered matched conversions',async()=>{const visitor=randomUUID(),session=randomUUID();await WebsiteAnalyticsStore.ingest(event('website_builder_viewed',{},visitor,session));await WebsiteAnalyticsStore.ingest(event('website_builder_viewed',{},visitor,session),'owner');await WebsiteAnalyticsStore.ingest(event('website_template_previewed',{templateId:'tmpl-start-blank'},visitor,session),'owner');await WebsiteAnalyticsStore.ingest(event('website_template_previewed',{templateId:'tmpl-start-blank'},visitor,session),'owner');await WebsiteAnalyticsStore.ingest(event('website_build_started',{templateId:'tmpl-start-blank'},visitor,session),'owner');const {site}=await create();await WebsiteAnalyticsStore.action('website_created','owner',site.id,site.template_id);await WebsiteAnalyticsStore.action('website_published','owner',site.id,site.template_id);await WebsiteAnalyticsStore.action('website_published','owner',site.id,site.template_id);const summary=await WebsiteAnalyticsStore.summary({range:'all'});assert.equal(summary.funnel.uniqueVisitors,1);assert.equal(summary.funnel.previews,2);assert.equal(summary.funnel.published,2);assert.equal(summary.funnel.startToCreate,100);assert.equal(summary.funnel.createToPublish,100);assert.equal(summary.templates.find(t=>t.templateId==='tmpl-start-blank')?.previews,2);});
test('date ranges filter analytics and metrics without inventing template rankings',async()=>{const oldNow=Date.now;try{Date.now=()=>oldNow()-40*86400_000;await WebsiteAnalyticsStore.ingest(event());}finally{Date.now=oldNow;}const summary=await WebsiteAnalyticsStore.summary({range:'7'});assert.equal(summary.metrics.total,0);assert.equal(summary.funnel.uniqueVisitors,0);assert.equal((await WebsiteAnalyticsStore.summary({range:'90'})).funnel.uniqueVisitors,1);assert.deepEqual(summary.templates,[]);assert.equal(summary.funnel.startToCreate,null);assert.equal(summary.funnel.createToPublish,null);});
for(const query of ['range=365','limit=101','offset=-1','status=deleted','template=fake'])test(`Admin filters ${query} rejected`,async()=>{assert.equal((await request(`admin/website-builder?${query}`,'GET',undefined,'admin-token')).status,400);});
test('force-unpublish requires confirmation, preserves all owner content and records safe audit',async()=>{const {site}=await create();await WebsiteStore.publishSite(site.id,'owner');const before=(await WebsiteStore.findSiteById(site.id))!;assert.equal((await request(`admin/website-builder/${site.id}/force-unpublish`,'POST',{confirmation:'wrong'},'admin-token')).status,400);assert.equal((await request(`admin/website-builder/${site.id}/force-unpublish`,'POST',{confirmation:site.slug},'admin-token')).status,200);const after=(await WebsiteStore.findSiteById(site.id))!;assert.equal(after.status,'draft');assert.deepEqual(after.content_json,before.content_json);assert.equal((await request(`public/sites/${site.slug}`)).status,404);const audit=(await AdminAuditStore.findRecent()).find(a=>a.entity_id===site.id && a.action==='website_admin_unpublished');assert.ok(audit);assert.equal(audit.admin_user_id,'admin');assert.deepEqual(JSON.parse(audit.metadata_safe_json!),{previousStatus:'published'});});
test('admin draft inspection never offers a public URL',async()=>{const {site}=await create();const response=await request(`admin/website-builder/${site.id}`,'GET',undefined,'admin-token');assert.equal(response.status,200);assert.equal((await response.json()).site.publicUrl,null);});
test('frontend library uses canonical request/finalize and no unsigned preset or credentials',()=>{const client=readFileSync('src/services/apiClient.ts','utf8'),library=readFileSync('src/components/website/editor/WebsiteImageField.tsx','utf8');assert.ok(client.includes('filename:file.name,mime:file.type,bytes:file.size'));assert.ok(client.includes("data.append('signature',intent.signature)"));assert.ok(client.includes("data.append('file',file)"));assert.ok(!library.includes('CLOUDINARY_API_SECRET'));assert.ok(!client.includes('upload_preset'));assert.ok(library.includes('Retry image verification'));assert.ok(library.includes('dialog.current?.showModal()'));});
test('schema.sql and repeatable initialization share additive assets/analytics schema',()=>{const schema=readFileSync('server/db/schema.sql','utf8').replaceAll('\r\n','\n'),source=readFileSync('server/db/websiteFreeSchema.ts','utf8').split('`')[1];assert.ok(schema.includes(source));assert.ok(readFileSync('server/db/connection.ts','utf8').includes("name: 'website_free_media_analytics', sql: WEBSITE_FREE_SCHEMA"));assert.ok(source.includes('ON DELETE SET NULL'));assert.ok(source.includes('public_id VARCHAR(255) NOT NULL UNIQUE'));assert.ok(!source.includes('DROP TABLE'));});

for(const extension of ['jpeg','avif','webp'])test(`foreign managed image cannot bypass ownership with ${extension} delivery`,async()=>{
  const {site}=await create();const asset=await uploaded(site.id);const other=await create('other');
  const url=asset.secure_url!.replace('/image/upload/','/image/upload/f_auto,w_400/').replace(/\.png$/,`.${extension}`);
  await assert.rejects(()=>WebsiteStore.updateSite(other.site.id,'other',{content:{heroImage:url}}),/verified image/);
});

test('in-flight finalization cannot revive an asset/site deleted during provider inspection',async()=>{
  const {site}=await create();const {intent:upload}=await (await intent(site.id)).json();
  const inspect=WebsiteCloudinary.inspect;let release!:(value:any)=>void;
  let inspectedResolve!:()=>void;const started=new Promise<void>(resolve=>{inspectedResolve=resolve;});
  try {
    WebsiteCloudinary.inspect=async()=>{inspectedResolve();return new Promise(resolve=>{release=resolve;});};
    const result=WebsiteAssetStore.finalize(site.id,'owner',upload.assetId);
    await started;await WebsiteStore.deleteSite(site.id,'owner');
    release({public_id:upload.parameters.public_id,resource_type:'image',type:'upload',format:'png',bytes:1,width:1,height:1,version:1});
    await assert.rejects(result,/Website not found/);
    assert.equal((await WebsiteAssetStore.find(upload.assetId))?.website_id,null);
    assert.equal((await WebsiteAssetStore.find(upload.assetId))?.status,'deleting');
  } finally {WebsiteCloudinary.inspect=inspect;}
});

for(const key of ['templateId','template_id'])test(`generic update cannot bypass confirmed migration via ${key}`,async()=>{
  const {site}=await create();assert.equal((await request(`websites/${site.id}`,'PATCH',{[key]:'tmpl-buka-bistro'},'owner-token')).status,400);
  assert.equal((await WebsiteStore.findSiteById(site.id))?.template_id,site.template_id);
});

test('Admin inspection returns exact project even when another project name contains its ID',async()=>{
  const {site}=await create();const other=await create('other');await WebsiteStore.updateSite(other.site.id,'other',{name:site.id});
  const response=await request(`admin/website-builder/${site.id}`,'GET',undefined,'admin-token');assert.equal(response.status,200);assert.equal((await response.json()).site.id,site.id);
});

test('in-memory persistence isolates caller-owned arrays like PostgreSQL JSON',async()=>{
  const {site}=await create();const items=[{id:'one',name:'Real item'}];await WebsiteStore.updateSite(site.id,'owner',{content:{items}});
  items[0].name='Mutated caller';assert.equal((await WebsiteStore.findSiteById(site.id))?.content_json.items?.[0].name,'Real item');
});

test('Cloudinary resource HTTP adapter uses expected encoded ID, server credentials and bounded timeout',async()=>{
  const originalFetch=globalThis.fetch;const publicId='mysteryhub/websites/site_fixture/asset_fixture';
  try {globalThis.fetch=async(url,options)=>{
    assert.equal(String(url),`https://api.cloudinary.com/v1_1/fixture-cloud/resources/image/upload/${encodeURIComponent(publicId)}`);
    assert.deepEqual(options?.headers,{Authorization:`Basic ${Buffer.from('fixture-key:fixture-secret').toString('base64')}`});
    assert.ok(options?.signal instanceof AbortSignal);
    return new Response(JSON.stringify({public_id:publicId}),{status:200});
  };assert.equal((await originalInspect(publicId)).public_id,publicId);}finally{globalThis.fetch=originalFetch;}
});

for(const kind of ['rejection','timeout','invalid-json'])test(`provider inspection ${kind} returns a safe retry error`,async()=>{
  const originalFetch=globalThis.fetch;
  try {globalThis.fetch=async()=>{if(kind==='timeout')throw new Error('fixture-secret / sensitive provider details');return new Response(kind==='invalid-json'?'invalid':'fixture-secret',{status:kind==='rejection'?403:200});};
    await assert.rejects(()=>originalInspect('expected-id'),error=>{assert.equal((error as any).status,503);assert.ok(!String(error).includes('fixture-secret'));return true;});
  }finally{globalThis.fetch=originalFetch;}
});

for(const result of ['ok','not found'])test(`Cloudinary destroy ${result} signs only expected ID and invalidation`,async()=>{
  const originalFetch=globalThis.fetch;const publicId='mysteryhub/websites/site_fixture/asset_fixture';
  try {globalThis.fetch=async(url,options)=>{
    assert.equal(String(url),'https://api.cloudinary.com/v1_1/fixture-cloud/image/destroy');assert.equal(options?.method,'POST');
    const body=options?.body as URLSearchParams;
    assert.equal(body.get('public_id'),publicId);assert.equal(body.get('invalidate'),'true');assert.equal(body.get('api_key'),'fixture-key');
    assert.equal(body.get('signature'),cloudinarySignature({public_id:publicId,timestamp:body.get('timestamp')!,invalidate:'true'},'fixture-secret'));
    assert.ok(options?.signal instanceof AbortSignal);return new Response(JSON.stringify({result}),{status:200});
  };await originalDestroy(publicId);}finally{globalThis.fetch=originalFetch;}
});

test('provider deletion errors do not leak credentials or response body',async()=>{
  const originalFetch=globalThis.fetch;
  try {globalThis.fetch=async()=>new Response(JSON.stringify({error:'fixture-secret'}),{status:500});
    await assert.rejects(()=>originalDestroy('expected-id'),error=>{assert.equal((error as any).status,503);assert.ok(!String(error).includes('fixture-secret'));return true;});
  }finally{globalThis.fetch=originalFetch;}
});

test('compositional footer renders configured safe social links',async()=>{
  const {site}=await create();await WebsiteStore.updateSite(site.id,'owner',{content:{social:{instagram:'ama.studio'}}});
  const saved=(await WebsiteStore.findSiteById(site.id))!;
  const html=renderToStaticMarkup(renderTemplateLayout(mergeSiteWithTemplate(getTemplateById(saved.template_id),saved.content_json)));
  assert.ok(html.includes('https://www.instagram.com/ama.studio'));assert.ok(html.includes('rel="noopener noreferrer"'));
});

for (const template of WEBSITE_TEMPLATES.filter(template=>!template.composition && template.layoutType!=='reseller')) test(`saved ${template.id} item fields survive storage, publish and actual public rendering`,async()=>{
  const {site}=await create('owner',template.id);
  const item={id:'fixture-item',name:'FixtureItemName',price:'FixturePrice',category:'FixtureCategory',tag:'FixtureTag',desc:'FixtureDescription',image:'https://images.example.com/fixture-item.png'};
  const save=await request(`websites/${site.id}`,'PATCH',{content:{items:[item]},settings:{primaryColor:'#123456',accentColor:'#abcdef',backgroundColor:'#fedcba'}},'owner-token');
  assert.equal(save.status,200);
  assert.equal((await request(`websites/${site.id}/publish`,'POST',{},'owner-token')).status,200);
  const response=await request(`public/sites/${site.slug}`);assert.equal(response.status,200);
  const published=(await response.json()).site;
  const html=renderToStaticMarkup(renderTemplateLayout(mergeSiteWithTemplate(getTemplateById(published.template_id),published.content,published.settings)));
  for(const field of websiteTemplateItemFields(template.id))assert.ok(html.includes(item[field]),`${template.id}: editable ${field} must appear in the real renderer`);
  assert.ok(html.includes('#123456'));assert.ok(html.includes('#abcdef'));assert.ok(html.includes('#fedcba'));
});

test('cleared compositional hero resets to template image without resurrecting cleared item lists',()=>{
  const base={...getTemplateById('tmpl-start-blank'),heroImage:'https://images.example.com/default-hero.jpg'};
  const html=renderToStaticMarkup(renderTemplateLayout(mergeSiteWithTemplate(base,{heroImage:'',items:[],businessName:'Fixture studio'})));
  assert.ok(html.includes('https://images.example.com/default-hero.jpg'));assert.ok(html.includes('Fixture studio'));
});

test('published restaurant uses contact enquiries without promising automatic booking/SMS',()=>{
  const template=getTemplateById('tmpl-buka-bistro');
  const html=renderToStaticMarkup(renderTemplateLayout(mergeSiteWithTemplate(template,{businessName:'Fixture cafe',whatsapp:'0240000000'})));
  assert.ok(html.includes('Contact to Arrange Reservation'));assert.ok(html.includes('confirm availability'));
  assert.ok(!html.includes('Instant Online Booking'));assert.ok(!html.includes('Instant SMS'));assert.ok(!html.includes('Instant WhatsApp Confirmation'));
  assert.ok(!renderToStaticMarkup(renderTemplateLayout(template)).includes('Instant Online Booking'));
});

for(const template of WEBSITE_TEMPLATES.filter(template=>template.id!=='tmpl-start-blank'))test(`change to ${template.id} permits the editor's next full save and publish`,async()=>{
  const {site}=await create();
  const changed=await request(`websites/${site.id}/change-template`,'POST',{targetTemplateId:template.id,confirmed:true,expectedUpdatedAt:site.updated_at},'owner-token');
  assert.equal(changed.status,200);const migrated=(await changed.json()).site;
  for(const [key,value] of Object.entries(migrated.content_json))assert.doesNotThrow(()=>validateWebsiteContentPatch({[key]:value}),`${template.id}: migrated ${key} must satisfy the save contract`);
  const saved=await request(`websites/${site.id}`,'PATCH',{expectedUpdatedAt:migrated.updated_at,name:migrated.name,content:{...migrated.content_json,tagline:'Fixture after template change'},settings:migrated.settings_json},'owner-token');
  assert.equal(saved.status,200,JSON.stringify(await saved.clone().json()));
  assert.equal((await request(`websites/${site.id}/publish`,'POST',{},'owner-token')).status,200);
  const published=(await (await request(`public/sites/${site.slug}`)).json()).site;
  assert.equal(published.content.tagline,'Fixture after template change');assert.equal(published.template_id,template.id);
});
