/** PostgreSQL query-boundary tests. Every connect/query is mocked; no socket is opened. */
import assert from 'node:assert/strict';
import { test, before, after, beforeEach } from 'node:test';
import pg from 'pg';
import { WebsiteStore } from '../../db/websiteStore.js';
import { WebsiteAssetStore } from '../../db/websiteAssetStore.js';
import { WebsiteAnalyticsStore } from '../../db/websiteAnalyticsStore.js';
import { WebsiteCloudinary } from '../../services/websiteCloudinary.js';
import { createWebsiteComposition } from '../../../src/config/websiteBuilder.js';
const originalQuery=pg.Pool.prototype.query,originalConnect=pg.Pool.prototype.connect;
const originalInspect=WebsiteCloudinary.inspect,originalDestroy=WebsiteCloudinary.destroy;
const names=['DATABASE_URL','CLOUDINARY_CLOUD_NAME','CLOUDINARY_API_KEY','CLOUDINARY_API_SECRET'];
const env=Object.fromEntries(names.map(name=>[name,process.env[name]]));
let sites:any[],assets:any[],events:any[],audit:any[],snapshot:any,statements:{sql:string;values:any[]}[],fail:string;
const clone=<T>(value:T):T=>structuredClone(value);
before(()=>{
  assert.equal(process.env.NODE_ENV,'test');process.env.DATABASE_URL='postgresql://fixture.invalid/never-contacted';
  process.env.CLOUDINARY_CLOUD_NAME='fixture-cloud';process.env.CLOUDINARY_API_KEY='fake-key';process.env.CLOUDINARY_API_SECRET='fake-secret';
  pg.Pool.prototype.query=(async(sql:string,values:any[]=[])=>{
    statements.push({sql,values:clone(values)});
    if(sql==='BEGIN'){snapshot=clone({sites,assets,events,audit});return {rows:[]};}
    if(sql==='ROLLBACK'){({sites,assets,events,audit}=snapshot);return {rows:[]};}
    if(fail && sql.includes(fail))throw new Error('Mock transactional write failure');
    if(sql==='COMMIT' || sql.includes('pg_advisory_xact_lock'))return {rows:[]};
    if(sql.startsWith('SELECT COUNT(*) FROM website_sites'))return {rows:[{count:String(sites.filter(s=>s.slug===values[0]).length)}]};
    if(sql.startsWith('SELECT * FROM website_sites WHERE user_id'))return {rows:clone(sites.filter(s=>s.user_id===values[0]))};
    if(sql.startsWith('SELECT * FROM website_sites WHERE id'))return {rows:clone(sites.filter(s=>s.id===values[0]))};
    if(sql.startsWith('INSERT INTO website_sites')){const columns=['id','user_id','template_id','name','slug','status','content_json','settings_json','created_at','updated_at','published_at'];const row=Object.fromEntries(columns.map((key,n)=>[key,['content_json','settings_json'].includes(key)?JSON.parse(values[n]):values[n]]));sites.push(row);return {rows:[],rowCount:1};}
    if(sql.includes('UPDATE website_sites') && sql.includes('SET template_id')){const row=sites.find(s=>s.id===values[3] && s.user_id===values[4]);row.template_id=values[0];row.content_json=JSON.parse(values[1]);row.updated_at=values[2];return {rows:[],rowCount:1};}
    if(sql.includes('UPDATE website_sites') && sql.includes('SET name')){const row=sites.find(s=>s.id===values[4] && s.user_id===values[5]);row.name=values[0];row.content_json=JSON.parse(values[1]);row.settings_json=JSON.parse(values[2]);row.updated_at=values[3];return {rows:[],rowCount:1};}
    if(sql.includes('UPDATE website_sites') && sql.includes("status = 'draft'")){sites.find(s=>s.id===values[1]).status='draft';return {rows:[],rowCount:1};}
    if(sql.startsWith('DELETE FROM website_sites')){sites=sites.filter(s=>s.id!==values[0] || s.user_id!==values[1]);return {rows:[],rowCount:1};}
    if(sql.startsWith('SELECT * FROM website_assets WHERE id'))return {rows:clone(assets.filter(a=>a.id===values[0]))};
    if(sql.startsWith('SELECT * FROM website_assets WHERE website_id'))return {rows:clone(assets.filter(a=>a.website_id===values[0]))};
    if(sql.startsWith('SELECT * FROM website_assets'))return {rows:clone(assets)};
    if(sql.startsWith('INSERT INTO website_assets')){const columns=['id','website_id','user_id','provider','public_id','original_filename','mime','format','bytes','width','height','secure_url','delivery_url','status','expires_at','created_at','updated_at'];assets.push(Object.fromEntries(columns.map((key,n)=>[key,values[n]])));return {rows:[],rowCount:1};}
    if(sql.startsWith('UPDATE website_assets')){const row=assets.find(a=>a.id===values[10] && a.user_id===values[11]);['website_id','mime','format','bytes','width','height','secure_url','delivery_url','status','updated_at'].forEach((key,n)=>row[key]=values[n]);return {rows:[],rowCount:1};}
    if(sql.startsWith('INSERT INTO analytics_events')){events.push({event_name:values[1],metadata_json:JSON.parse(values[7])});return {rows:[],rowCount:1};}
    if(sql.includes('INSERT INTO admin_audit_log')){const row=Object.fromEntries(['id','admin_user_id','action','entity_type','entity_id','metadata_safe_json','created_at'].map((key,n)=>[key,values[n]]));audit.push(row);return {rows:[row],rowCount:1};}
    throw new Error(`Unexpected mocked SQL: ${sql}`);
  }) as any;
  pg.Pool.prototype.connect=(async function(this:pg.Pool){return {query:this.query.bind(this),release(){}};}) as any;
  WebsiteCloudinary.inspect=async publicId=>({public_id:publicId,resource_type:'image',type:'upload',format:'png',bytes:5000,width:500,height:400,secure_url:'ignored',version:3});
  WebsiteCloudinary.destroy=async()=>{throw new Error('Remote mutation is prohibited in this test');};
});
after(()=>{pg.Pool.prototype.query=originalQuery;pg.Pool.prototype.connect=originalConnect;WebsiteCloudinary.inspect=originalInspect;WebsiteCloudinary.destroy=originalDestroy;for(const name of names){if(env[name]===undefined)delete process.env[name];else process.env[name]=env[name];}});
beforeEach(()=>{sites=[];assets=[];events=[];audit=[];statements=[];fail='';});
const site=()=>WebsiteStore.createSite('owner',{template_id:'tmpl-start-blank',name:"Ama's Site"});
const asset=async(siteId:string)=>{const intent=await WebsiteAssetStore.reserve(siteId,'owner',{filename:'shop.png',mime:'image/png',bytes:6000});return WebsiteAssetStore.finalize(siteId,'owner',intent.assetId);};
test('creation locks owner inside transaction BEFORE checking site count, uses bound SQL',async()=>{const result=await site();const lock=statements.findIndex(s=>s.sql.includes('pg_advisory_xact_lock')),check=statements.findIndex(s=>s.sql.includes('WHERE user_id'));assert.equal(statements[0].sql,'BEGIN');assert.ok(lock<check);assert.deepEqual(statements[lock].values,['website:owner']);assert.equal(statements.at(-1)?.sql,'COMMIT');const insert=statements.find(s=>s.sql.startsWith('INSERT INTO website_sites'))!;assert.equal(insert.values[3],"Ama's Site");assert.ok(!insert.sql.includes("Ama's"));assert.equal((await WebsiteStore.findSiteById(result.site.id))?.content_json.businessName,"Ama's Site");});
test('Free re-creation checks the authoritative DB under the same owner lock',async()=>{const first=await site();const again=await WebsiteStore.createSite('owner',{template_id:'tmpl-legon-consult',name:'Second'});assert.equal(again.site.id,first.site.id);assert.equal(again.alreadyExists,true);assert.equal(sites.length,1);});
test('asset reservation and verified persistence map exact metadata to PostgreSQL columns',async()=>{const {site:created}=await site();const ready=await asset(created.id);assert.equal(assets[0].website_id,created.id);assert.equal(assets[0].user_id,'owner');assert.equal(assets[0].bytes,5000);assert.equal(assets[0].mime,'image/png');assert.equal(assets[0].width,500);assert.equal(assets[0].format,'png');assert.equal((await WebsiteAssetStore.list(created.id,'owner'))[0].id,ready.id);const insert=statements.find(s=>s.sql.startsWith('INSERT INTO website_assets'))!;assert.equal(insert.values[4],ready.public_id);assert.ok(insert.sql.includes('$17'));const reservationIndex=statements.findIndex(s=>s.sql.startsWith('INSERT INTO website_assets'));assert.ok(statements.slice(0,reservationIndex).some(s=>s.sql.includes('pg_advisory_xact_lock')));});
test('PostgreSQL JSONB roundtrip preserves contacts/social/items/composition/settings',async()=>{const {site:created}=await site();const composition=createWebsiteComposition(['header','hero','gallery','footer']);composition.sections[2].data.items=[{title:'Item',image:'https://example.com/item.png',text:'Description',price:'42'}];const updated=await WebsiteStore.updateSite(created.id,'owner',{content:{composition,email:'ama@example.com',phone:'0241111111',social:{instagram:'ama'},items:[{name:'Offer',desc:'Details',image:'https://example.com/offer.png'}]},settings:{primaryColor:'#123456'}});assert.deepEqual((await WebsiteStore.findSiteById(created.id))?.content_json,updated?.content_json);assert.equal((await WebsiteStore.findSiteById(created.id))?.settings_json.primaryColor,'#123456');});
test('template change is one transactional parameterized write preserving original identity and assets',async()=>{const {site:created}=await site();const ready=await asset(created.id);const current=await WebsiteStore.updateSite(created.id,'owner',{content:{heroImage:ready.secure_url!}});statements=[];const changed=await WebsiteStore.changeTemplate(created.id,'owner','tmpl-legon-consult',current!.updated_at);assert.equal(changed.id,created.id);assert.equal(changed.slug,created.slug);assert.equal(assets[0].website_id,created.id);assert.equal(statements[0].sql,'BEGIN');assert.equal(statements.at(-1)?.sql,'COMMIT');const write=statements.find(s=>s.sql.includes('SET template_id'))!;assert.deepEqual(write.values.slice(-2),[created.id,'owner']);assert.ok(!write.sql.includes('tmpl-legon-consult'));});
test('failed template DB write rolls back and never replaces the original',async()=>{const {site:created}=await site();fail='SET template_id';await assert.rejects(()=>WebsiteStore.changeTemplate(created.id,'owner','tmpl-legon-consult',created.updated_at),/Mock transactional/);assert.equal(statements.at(-1)?.sql,'ROLLBACK');assert.equal(sites[0].template_id,created.template_id);assert.deepEqual(sites[0].content_json,created.content_json);});
test('failed deletion rolls back asset detachment and site before any provider cleanup',async()=>{const {site:created}=await site();const ready=await asset(created.id);fail='DELETE FROM website_sites';await assert.rejects(()=>WebsiteStore.deleteSite(created.id,'owner'),/Mock transactional/);assert.equal(statements.at(-1)?.sql,'ROLLBACK');assert.equal(sites.length,1);assert.equal(assets[0].website_id,created.id);assert.equal(assets[0].status,'ready');assert.equal(assets[0].id,ready.id);});
test('successful deletion only detaches owned media and deletes exact owned website',async()=>{const {site:created}=await site();await asset(created.id);await WebsiteStore.createSite('other',{template_id:'tmpl-start-blank',name:'Other site'});await WebsiteStore.deleteSite(created.id,'owner');assert.equal(sites.length,1);assert.equal(sites[0].user_id,'other');assert.equal(assets[0].website_id,null);assert.equal(assets[0].status,'deleting');const write=statements.find(s=>s.sql.startsWith('DELETE FROM website_sites'))!;assert.deepEqual(write.values,[created.id,'owner']);assert.ok(!statements.some(s=>/DELETE FROM (users|orders|referral|marketplace)/.test(s.sql)));});
test('Admin unpublish and audit share a transaction; audit failure rolls back status',async()=>{const {site:created}=await site();sites[0].status='published';fail='INSERT INTO admin_audit_log';await assert.rejects(()=>WebsiteStore.forceUnpublish(created.id,'admin',created.slug));assert.equal(sites[0].status,'published');assert.equal(statements.at(-1)?.sql,'ROLLBACK');fail='';await WebsiteStore.forceUnpublish(created.id,'admin',created.slug);assert.equal(sites[0].status,'draft');assert.equal(audit[0].action,'website_admin_unpublished');assert.equal(statements.at(-1)?.sql,'COMMIT');});
test('analytics database failure is swallowed only for server action telemetry',async()=>{const {site:created}=await site();fail='INSERT INTO analytics_events';await WebsiteAnalyticsStore.action('website_created','owner',created.id,created.template_id);assert.equal(events.length,0);assert.equal(sites.length,1);});
