import assert from 'node:assert/strict';
import {test} from 'node:test';
import React from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import {readFileSync} from 'node:fs';
import {WEBSITE_TEMPLATES} from '../../../src/data/templates';
import {createWebsiteComposition} from '../../../src/config/websiteBuilder';
import {migrateWebsiteTemplate,websiteMigrationSummary} from '../../../src/utils/websiteTemplateMigration';
import {mergeSiteWithTemplate,renderTemplateLayout} from '../../../src/utils/templateRendererUtils';
import {bulkSellerPrices,sellerDrafts,sellerPriceError,type SellerBundle} from '../../../src/utils/websitePricing';
import type {SiteContent} from '../../../src/types';
const composition=createWebsiteComposition(['header','hero','products','gallery','testimonials','footer']);
for(const section of composition.sections)section.data={heading:'Old restaurant only',image:'https://example.test/restaurant.jpg',items:[{title:'Jollof',image:'https://example.test/food.jpg'}]};
const content:SiteContent={businessName:'Ama Business',logoUrl:'https://example.test/logo.png',phone:'0241234567',whatsapp:'0551234567',email:'ama@example.test',location:'Tema',social:{instagram:'ama'},tagline:'Restaurant food only',aboutText:'Restaurant story only',heroImage:'https://example.test/old-food.jpg',ctaLabel:'Book a table',ctaTarget:'https://example.test/restaurant-booking',items:[{id:'dish',name:'Jollof',image:'https://example.test/food.jpg'}],features:['Old restaurant only'],stats:[{label:'Meals',value:'100'}],composition};
for(const target of WEBSITE_TEMPLATES.filter(t=>t.id!=='tmpl-buka-bistro'))test(`cross-industry migration to ${target.id} preserves identity and resets semantic content`,()=>{
 const before=structuredClone(content),next=migrateWebsiteTemplate(content,'tmpl-buka-bistro',target.id);
 for(const key of ['businessName','logoUrl','phone','whatsapp','email','location','social'] as const)assert.deepEqual(next[key],content[key]);
 assert.equal(next.heroImage,'');assert.equal(next.tagline,'');assert.equal(next.aboutText,'');assert.equal(next.ctaTarget,'');
 assert.deepEqual(next.items,[]);assert.deepEqual(next.stats,[]);assert.deepEqual(next.features,[]);assert.deepEqual(content,before);
 const html=renderToStaticMarkup(renderTemplateLayout(mergeSiteWithTemplate(target,next)));
 for(const old of ['Jollof','old-food.jpg','restaurant.jpg','Restaurant food only','Restaurant story only','restaurant-booking'])assert.ok(!html.includes(old),old);
 assert.ok(html.includes('Ama Business'));assert.ok(html.includes('logo.png'));
});
test('same design preserves content and cloning does not mutate input',()=>{const next=migrateWebsiteTemplate(content,'tmpl-buka-bistro','tmpl-buka-bistro');assert.deepEqual(next,content);next.businessName='Other';assert.equal(content.businessName,'Ama Business');});
test('migration summary uses semantic compatibility and names actual target',()=>{const summary=websiteMigrationSummary('tmpl-buka-bistro','tmpl-glow-salon');assert.equal(summary.target.id,'tmpl-glow-salon');assert.equal(summary.compatible,false);assert.ok(summary.kept.includes('Uploaded media library'));assert.ok(summary.reset.includes('Cover & gallery image assignments'));});
const products:SellerBundle[]=[{id:'m1',network:'mtn',networkName:'MTN',dataAmount:'1GB',minimumMinor:465,wholesaleMinor:450,retailMinor:549,enabled:true,configured:true},{id:'t1',network:'telecel',networkName:'Telecel',dataAmount:'1GB',minimumMinor:865,wholesaleMinor:800,retailMinor:949,enabled:true,configured:true},{id:'a1',network:'airteltigo',networkName:'AirtelTigo',dataAmount:'1GB',minimumMinor:null,wholesaleMinor:null,retailMinor:0,enabled:false,configured:false}];
test('percentage markup rounds pesewas half up from authoritative minimum, not existing retail',()=>{assert.deepEqual(bulkSellerPrices(products,'mtn','percent','10'),[{id:'m1',retailMinor:512}]);assert.equal(bulkSellerPrices(products,'mtn','percent','2.50')[0].retailMinor,477);});
test('flat GHS markup adds exact pesewas to authoritative minimum',()=>{assert.deepEqual(bulkSellerPrices(products,'telecel','flat','1.00'),[{id:'t1',retailMinor:965}]);assert.equal(bulkSellerPrices(products,'mtn','flat','0.01')[0].retailMinor,466);});
test('bulk preview respects network scope, excludes unconfigured, and never mutates source/drafts',()=>{const before=structuredClone(products),drafts=sellerDrafts(products),snapshot=structuredClone(drafts);assert.equal(bulkSellerPrices(products,'all','percent','0').length,2);assert.deepEqual(bulkSellerPrices(products,'airteltigo','flat','1'),[]);assert.deepEqual(products,before);assert.deepEqual(drafts,snapshot);});
test('individual overrides remain valid after locally applying bulk prices',()=>{const drafts=sellerDrafts(products);for(const row of bulkSellerPrices(products,'mtn','percent','10'))drafts[row.id].price=(row.retailMinor/100).toFixed(2);drafts.m1.price='6.25';assert.equal(sellerPriceError(products[0],drafts.m1),'');assert.equal(products[0].retailMinor,549);});
test('minimum enforcement includes disabled nonzero overrides; disabled unset stays safe',()=>{for(const enabled of [true,false])assert.match(sellerPriceError(products[0],{enabled,price:'4.64'}),/Minimum selling price is GH₵4.65/);assert.equal(sellerPriceError(products[0],{enabled:false,price:''}),'');assert.match(sellerPriceError(products[0],{enabled:true,price:'5.001'}),/valid selling price/);});
for(const value of ['-1','NaN','1e3','0.001','10001'])test(`invalid percentage markup ${value} rejected`,()=>assert.throws(()=>bulkSellerPrices(products,'all','percent',value)));
test('selected template skips catalogue until Change selection is requested',()=>{const source=readFileSync('src/components/website/WebsiteSettingsControls.tsx','utf8');assert.match(source,/setTarget\(requestedTemplateId\)/);assert.match(source,/!target&&<div[^>]+aria-label="Choose a website design"/);assert.match(source,/Change selection/);});
test('pricing Apply remains local, explicit Save calls versioned authoritative endpoint',()=>{const source=readFileSync('src/components/website/WebsiteBundlePricing.tsx','utf8');const apply=source.slice(source.indexOf('Apply to')-400,source.indexOf('Apply to'));assert.ok(!apply.includes('websiteBusinessRequest'));assert.match(source,/expectedVersion:catalog.version/);assert.match(source,/Save Changes/);assert.match(source,/sellerPriceError/);assert.ok(!source.includes('Awaiting setup'));});
