import assert from 'node:assert/strict';
import {test,before,after,beforeEach} from 'node:test';
import express from 'express';
import {randomUUID,createHmac} from 'node:crypto';
import type {Server} from 'node:http';
import type {AddressInfo} from 'node:net';
import {apiRouter,handlePaystackWebhook} from '../../routes/api.js';
import {adminRouter} from '../../routes/adminApi.js';
import {WebsiteBusinessService as Business} from '../../services/websiteBusinessService.js';
import {WebsiteStore} from '../../db/websiteStore.js';
import {WebsiteAssetStore} from '../../db/websiteAssetStore.js';
import {WebsiteAnalyticsStore} from '../../db/websiteAnalyticsStore.js';
import {FinanceStore} from '../../db/financeStore.js';
import {FinanceService} from '../../services/financeService.js';
import {AuthStore} from '../../db/authStore.js';
import {OrdersStore} from '../../db/ordersStore.js';
import {ReferralStore} from '../../db/referralStore.js';
import {ReferralService} from '../../services/referralService.js';
import {PaystackServerService} from '../../services/paystackService.js';
import {FulfilmentService} from '../../services/fulfilmentService.js';
import {validateOrderPayment} from '../../services/paymentValidation.js';
import {minimumStorePrice,storeReserve,STORE_POLICY_DEFAULTS} from '../../../shared/storeEconomics.js';
import {readFileSync} from 'node:fs';
const originals={fetch:globalThis.fetch,init:PaystackServerService.initializeTransaction,verify:PaystackServerService.verifyTransaction,preflight:FulfilmentService.preflightCheck,resolve:FulfilmentService.getProvider().resolvePackage};
let server:Server,base:string,site:any,transaction:any,initCount:number,cost:number,initFail:boolean;
before(async()=>{assert.equal(process.env.NODE_ENV,'test');assert.equal(process.env.DATABASE_URL,undefined);const app=express();app.use(express.json({verify:(req,_res,body)=>{(req as any).rawBody=body;}}));app.post('/api/webhooks/paystack',handlePaystackWebhook);app.use('/api',apiRouter);app.use('/api/admin',adminRouter);server=await new Promise(r=>{const s=app.listen(0,'127.0.0.1',()=>r(s));});base=`http://127.0.0.1:${(server.address() as AddressInfo).port}`;});
after(async()=>{globalThis.fetch=originals.fetch;PaystackServerService.initializeTransaction=originals.init;PaystackServerService.verifyTransaction=originals.verify;FulfilmentService.preflightCheck=originals.preflight;FulfilmentService.getProvider().resolvePackage=originals.resolve;await new Promise<void>(r=>server.close(()=>r()));});
beforeEach(async()=>{
  assert.equal(process.env.DATABASE_URL,undefined);FinanceStore._reset();WebsiteStore.clearDevStore();WebsiteAssetStore.clearDevStore();WebsiteAnalyticsStore.clearDevStore();OrdersStore.clearDevStore();AuthStore._clearDevStore();ReferralStore._clearDevStore();process.env.PAYSTACK_SECRET_KEY='sk_test_fixture';cost=200;initCount=0;initFail=false;
  for(const role of ['owner','other','admin']){await AuthStore.createUser({id:role,name:role,email:`${role}@fixture.test`,phone:null,passwordHash:'fixture-only',role:role==='admin'?'admin':'customer'});await AuthStore.createSession(role,`${role}-token`);}
  globalThis.fetch=async()=>{throw Error('External network forbidden');};
  FulfilmentService.getProvider().resolvePackage=async()=>({resolved:{supplierCostMinor:cost,offerSlug:'fixture',sizeLabel:'1GB',network:'mtn'} as any});
  FulfilmentService.preflightCheck=async()=>({allowed:true,supplierCostMinor:cost});
  PaystackServerService.initializeTransaction=async params=>{transaction=params;initCount++;return {success:!initFail,reference:params.reference,accessCode:'fixture-access',authorizationUrl:'https://checkout.paystack.com/fixture'};};
  PaystackServerService.verifyTransaction=async reference=>({isVerified:true,status:'success',reference,amountPesewas:transaction.amountPesewas,currency:'GHS',metadata:transaction.metadata});
  site=(await WebsiteStore.createSite('owner',{template_id:'tmpl-data-reseller',name:'Fixture Store'})).site;site=await WebsiteStore.publishSite(site.id,'owner');
});
const request=(path:string,method='GET',body?:unknown,token='')=>originals.fetch(base+path,{method,headers:{...(body?{'Content-Type':'application/json'}:{}),...(token?{Authorization:`Bearer ${token}`}:{})},...(body?{body:JSON.stringify(body)}:{})});
const body=()=>({productId:'mtn-1gb',recipientPhone:'0241111111',customerEmail:'receipt@fixture.test',requestId:randomUUID()});
async function configure(){await Business.savePolicy('admin',{confirmed:true,expectedVersion:'unconfigured',enabled:true,reserveBps:300,reserveFixedMinor:10,withdrawalMinimumMinor:500,withdrawalFeeBps:300});await Business.saveWholesale('admin',{confirmed:true,expectedVersion:'empty',productId:'mtn-1gb',wholesaleMinor:300,enabled:true});await Business.savePrices(site.id,'owner',{expectedVersion:'empty',products:[{productId:'mtn-1gb',retailMinor:500,enabled:true}]});}
async function paid(delivered=false){await configure();const payment=await Business.initialize(site.id,body());await FulfilmentService.processPaidOrder(payment.reference,new Date().toISOString());const order=(await OrdersStore.findOrder(payment.reference))!;if(delivered)await OrdersStore.updateOrderStatus(order.id,'delivered',undefined,'fixture-supplier');return (await OrdersStore.findOrder(order.id))!;}
test('default policy safely disables checkout without invented wholesale',async()=>{assert.equal((await Business.catalog(site.id)).products.length,0);await assert.rejects(()=>Business.initialize(site.id,body()),/pricing needs/);assert.equal(initCount,0);});
test('explicit configured reserve required for activation',async()=>{await assert.rejects(()=>Business.savePolicy('admin',{confirmed:true,expectedVersion:'unconfigured',enabled:true,reserveBps:0,reserveFixedMinor:0,withdrawalMinimumMinor:500,withdrawalFeeBps:300}),/reserve/);});
for(const amount of [0,1,199])test(`unsafe wholesale ${amount} rejected`,async()=>{await assert.rejects(()=>Business.saveWholesale('admin',{confirmed:true,expectedVersion:'empty',productId:'mtn-1gb',wholesaleMinor:amount,enabled:true}));});
test('unknown supplier cost blocks wholesale and checkout',async()=>{cost=NaN;await assert.rejects(()=>configure(),/supplier cost/);await assert.rejects(()=>Business.initialize(site.id,body()),/unavailable/);assert.equal(initCount,0);});
test('minimum floor includes configured reserve with exact minor rounding',()=>{const policy={...STORE_POLICY_DEFAULTS,enabled:true,reserveBps:300,reserveFixedMinor:10};const floor=minimumStorePrice(300,policy);assert.ok(floor-storeReserve(floor,policy)>=300);assert.ok(floor-1-storeReserve(floor-1,policy)<300);});
test('below floor rejected; equal floor and above accepted',async()=>{await configure();const policy=(await Business.adminConfig()).policy,floor=minimumStorePrice(300,policy);let version=(await Business.catalog(site.id,'owner')).version;await assert.rejects(()=>Business.savePrices(site.id,'owner',{expectedVersion:version,products:[{productId:'mtn-1gb',retailMinor:floor-1,enabled:true}]}),/minimum/);for(const price of [floor,floor+100]){const result=await Business.savePrices(site.id,'owner',{expectedVersion:version,products:[{productId:'mtn-1gb',retailMinor:price,enabled:true}]});version=result.version;}});
test('concurrent seller edits reject stale revision',async()=>{await configure();const version=(await Business.catalog(site.id,'owner')).version;const results=await Promise.allSettled([510,520].map(retailMinor=>Business.savePrices(site.id,'owner',{expectedVersion:version,products:[{productId:'mtn-1gb',retailMinor,enabled:true}]})));assert.equal(results.filter(r=>r.status==='fulfilled').length,1);});
test('concurrent admin edits reject stale wholesale revision',async()=>{await configure();const version=(await Business.adminConfig()).products.find(p=>p.id==='mtn-1gb')!.wholesale!.version;const results=await Promise.allSettled([310,320].map(wholesaleMinor=>Business.saveWholesale('admin',{confirmed:true,expectedVersion:version,productId:'mtn-1gb',wholesaleMinor,enabled:true})));assert.equal(results.filter(r=>r.status==='fulfilled').length,1);});
for(const key of ['amount','retailMinor','ownerId','storeId','paymentMethod','referralCode'])test(`checkout tampering field ${key} rejected`,async()=>{await configure();await assert.rejects(()=>Business.initialize(site.id,{...body(),[key]:1}),/Unexpected/);assert.equal(initCount,0);});
test('guest checkout uses saved price and exact receipt email',async()=>{await configure();const result=await Business.initialize(site.id,body()),order=(await OrdersStore.findOrder(result.reference))!;assert.equal(result.amountPesewas,500);assert.equal(transaction.amountPesewas,500);assert.equal(transaction.email,'receipt@fixture.test');assert.equal(order.customer_email,transaction.email);assert.equal(order.user_id,null);assert.equal(order.store_context!.earningMinor,175);assert.equal(order.referrer_user_id,null);});
test('authenticated checkout retains customer identity without charging owner wallet',async()=>{await configure();const result=await Business.initialize(site.id,body(),'other');assert.equal((await OrdersStore.findOrder(result.reference))!.user_id,'other');assert.equal((await FinanceService.summary('owner')).walletMinor,0);});
test('duplicate concurrent checkout creates one durable order and one initialization',async()=>{await configure();const input=body();const results=await Promise.allSettled(Array.from({length:6},()=>Business.initialize(site.id,input)));assert.equal(initCount,1);assert.equal(OrdersStore.adminDevOrders().length,1);assert.ok(results.some(r=>r.status==='fulfilled'));});
test('request ID cannot be replayed with changed recipient/customer identity',async()=>{await configure();const input=body();await Business.initialize(site.id,input);await assert.rejects(()=>Business.initialize(site.id,{...input,recipientPhone:'0242222222'}),/request changed/);await assert.rejects(()=>Business.initialize(site.id,input,'other'),/request changed/);});
test('uncertain payment initialization is latched and never automatically repeated',async()=>{await configure();initFail=true;const input=body();await assert.rejects(()=>Business.initialize(site.id,input),/uncertain/);initFail=false;await assert.rejects(()=>Business.initialize(site.id,input),/uncertain/);assert.equal(initCount,1);});
test('supplier cost increase blocks negative platform margin before payment',async()=>{await configure();cost=301;await assert.rejects(()=>Business.initialize(site.id,body()),/pricing needs/);assert.equal(initCount,0);});
for(const mutation of [{amountPesewas:1},{currency:'USD'},{reference:'forged'},{metadata:{}},{metadata:{purpose:'website_store_order',store_id:'other',order_id:'other',product_id:'mtn-1gb'}}])test(`verified payment mutation rejected ${JSON.stringify(mutation)}`,async()=>{await configure();const result=await Business.initialize(site.id,body()),order=(await OrdersStore.findOrder(result.reference))!;assert.ok(validateOrderPayment(order,{isVerified:true,status:'success',reference:order.payment_reference,currency:'GHS',amountPesewas:order.amount,metadata:transaction.metadata,...mutation}));});
test('verified payment creates pending, not available earning',async()=>{const order=await paid();const summary=await Business.ownerSummary(site.id,'owner');assert.equal(summary.earnings.pendingMinor,175);assert.equal(summary.earnings.availableMinor,0);assert.equal(summary.orders[0].earningState,'pending');assert.equal(order.status,'queued');assert.equal(summary.ledger.length,0);});
test('definitive delivery releases earning once across duplicate recovery',async()=>{const order=await paid(true);await Promise.all(Array.from({length:8},()=>Business.syncOrder(order)));const summary=await Business.ownerSummary(site.id,'owner');assert.equal(summary.earnings.pendingMinor,0);assert.equal(summary.earnings.availableMinor,175);assert.equal(summary.orders[0].earningState,'available');assert.equal(summary.ledger.length,1);});
test('uncertain supplier remains pending and cannot be withdrawn',async()=>{const order=await paid();await OrdersStore.saveSupplierUncertainSubmission(order.id,'fixture timeout');const summary=await Business.ownerSummary(site.id,'owner');assert.equal(summary.earnings.pendingMinor,175);assert.equal(summary.earnings.availableMinor,0);await assert.rejects(()=>Business.withdraw(site.id,'owner',{confirmed:true,amountMinor:500,phone:'0241111111',network:'mtn',recipientName:'Owner',requestId:randomUUID()}),/Insufficient/);});
test('historical snapshots survive all later pricing changes',async()=>{const order=await paid(true),snapshot=structuredClone(order.store_context);const config=await Business.adminConfig();const {version,...policy}=config.policy;await Business.savePolicy('admin',{...policy,confirmed:true,expectedVersion:version,reserveBps:500});const prices=await Business.catalog(site.id,'owner');await Business.savePrices(site.id,'owner',{expectedVersion:prices.version,products:[{productId:'mtn-1gb',retailMinor:900,enabled:true}]});assert.deepEqual((await OrdersStore.findOrder(order.id))!.store_context,snapshot);assert.equal((await Business.ownerSummary(site.id,'owner')).earnings.availableMinor,175);});
test('failed pending sale cancels without spendable credit',async()=>{const order=await paid();await OrdersStore.updateOrderStatus(order.id,'failed','fixture failure');const summary=await Business.ownerSummary(site.id,'owner');assert.equal(summary.earnings.availableMinor,0);assert.equal(summary.earnings.pendingMinor,0);});
test('definitive refund appends reversal preserving original earning',async()=>{const order=await paid(true);await OrdersStore.updateOrderStatus(order.id,'refunded','fixture refund',undefined,undefined,{explicitReversal:true});const summary=await Business.ownerSummary(site.id,'owner');assert.equal(summary.earnings.availableMinor,0);assert.equal(summary.ledger.length,2);assert.equal(summary.earnings.lifetimeMinor,175);});
async function seedStore(amount=2000){await FinanceStore.transaction('owner',async tx=>{const row=await tx.create('store_sale',`store-sale:${randomUUID()}`,amount,{siteId:site.id,availableAt:new Date().toISOString()},'available');await tx.append(row,'store',amount,'Fixture store earning');});}
const withdrawal=(amountMinor=500)=>({confirmed:true,amountMinor,phone:'0241111111',network:'mtn',recipientName:'Fixture Owner',requestId:randomUUID()});
test('withdrawal snapshots independent policy and reserves only Store Earnings',async()=>{await seedStore();const row=await Business.withdraw(site.id,'owner',withdrawal(1000));assert.equal(row.payload.source,'Store Earnings');assert.equal(row.payload.feeMinor,30);assert.equal(row.payload.netMinor,970);assert.equal((row.payload as any).phone,undefined);const summary=await Business.ownerSummary(site.id,'owner');assert.equal(summary.earnings.availableMinor,1000);assert.equal(summary.earnings.reservedMinor,1000);assert.equal((await FinanceService.summary('owner')).earn.reservedMinor,0);assert.equal((await FinanceService.summary('owner')).walletMinor,0);});
test('minimum withdrawal rejected without reservation',async()=>{await seedStore();await assert.rejects(()=>Business.withdraw(site.id,'owner',withdrawal(499)),/Minimum/);assert.equal((await Business.ownerSummary(site.id,'owner')).earnings.availableMinor,2000);});
test('concurrent withdrawals cannot overdraw available store earnings',async()=>{await seedStore(1000);const results=await Promise.allSettled([Business.withdraw(site.id,'owner',withdrawal(800)),Business.withdraw(site.id,'owner',withdrawal(800))]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal((await Business.ownerSummary(site.id,'owner')).earnings.availableMinor,200);});
test('withdrawal reject releases Store Earnings without referral credit',async()=>{await seedStore();const row=await Business.withdraw(site.id,'owner',withdrawal());await FinanceService.withdrawalAction('admin',row.id,{confirmed:true,expectedState:'pending_review',action:'reject',reason:'Fixture destination mismatch'});assert.equal((await Business.ownerSummary(site.id,'owner')).earnings.availableMinor,2000);assert.equal((await FinanceService.summary('owner')).earn.availableMinor,0);});
test('manual payout transitions, stale actions, and paid replay are protected',async()=>{await seedStore();const row=await Business.withdraw(site.id,'owner',withdrawal());await FinanceService.withdrawalAction('admin',row.id,{confirmed:true,expectedState:'pending_review',action:'approve'});await assert.rejects(()=>FinanceService.withdrawalAction('admin',row.id,{confirmed:true,expectedState:'pending_review',action:'reject',reason:'stale'}),/state changed/);await FinanceService.withdrawalAction('admin',row.id,{confirmed:true,expectedState:'approved',action:'paid',reference:'fixture-momo'});await assert.rejects(()=>FinanceService.withdrawalAction('admin',row.id,{confirmed:true,expectedState:'approved',action:'paid',reference:'fixture-momo'}),/state changed/);assert.equal((await Business.ownerSummary(site.id,'owner')).earnings.withdrawnMinor,500);});
test('owner self-purchase never creates ordinary referral reward',async()=>{const order=await paid(true);assert.equal(await ReferralService.processOrderReward({...order,user_id:'owner',referrer_user_id:'owner'}),null);assert.equal(ReferralStore.adminDevSnapshot().ledger.length,0);});
test('public catalogue hides disabled bundles and internal economics',async()=>{await configure();const publicCatalog=await Business.catalog(site.id);assert.equal(publicCatalog.products.length,1);const text=JSON.stringify(publicCatalog);for(const value of ['wholesale','supplier','ownerId','reserve','secret'])assert.ok(!text.includes(value));});
for(const area of ['business','bundles'])test(`cross-owner ${area} access denied`,async()=>{const response=await request(`/api/websites/${site.id}/${area}`,'GET',undefined,'other-token');assert.equal(response.status,403);});
for(const route of ['reseller-config','reseller-policy','reseller-wholesale'])test(`Admin ${route} requires admin role`,async()=>{const response=await request(`/api/admin/website-builder/${route}`,route==='reseller-config'?'GET':'PUT',route==='reseller-config'?undefined:{},'owner-token');assert.equal(response.status,403);});
test('draft store and draft analytics remain private',async()=>{await WebsiteStore.unpublishSite(site.id,'owner');assert.equal((await request(`/api/websites/${site.id}/storefront`)).status,404);assert.equal((await request(`/api/websites/${site.id}/public-events`,'POST',{event:'site_view',visitorId:randomUUID(),sessionId:randomUUID()})).status,404);});
test('anonymous repeated views deduplicate; unique visitors are separate',async()=>{const input={event:'site_view',visitorId:randomUUID(),sessionId:randomUUID()};await Promise.all(Array.from({length:12},()=>WebsiteAnalyticsStore.ingestPublic(site.id,input)));await WebsiteAnalyticsStore.ingestPublic(site.id,{...input,sessionId:randomUUID()});const data=await WebsiteAnalyticsStore.ownerAnalytics(site.id,'owner');assert.equal(data.views,2);assert.equal(data.uniqueVisitors,1);assert.equal(data.conversion,null);});
for(const event of ['whatsapp_click','call_click','email_click','primary_cta_click','product_view','checkout_started'])test(`public harmless event ${event} accepted`,async()=>{assert.equal((await request(`/api/websites/${site.id}/public-events`,'POST',{event,visitorId:randomUUID(),sessionId:randomUUID()})).status,200);});
for(const event of ['paid_order','fulfilled_order','store_earning_available','refund'])test(`fabricated financial analytics ${event} rejected`,async()=>{assert.equal((await request(`/api/websites/${site.id}/public-events`,'POST',{event,visitorId:randomUUID(),sessionId:randomUUID()})).status,400);});
test('PII and arbitrary analytics metadata rejected',async()=>{for(const extra of [{email:'private@fixture.test'},{phone:'0241111111'},{url:'https://fixture.test/image'},{metadata:{paid:true}}])assert.equal((await request(`/api/websites/${site.id}/public-events`,'POST',{event:'site_view',visitorId:randomUUID(),sessionId:randomUUID(),...extra})).status,400);});
test('public client cannot mark a sale delivered or alter balances',async()=>{for(const path of ['store-earnings','deliver','adjustment'])assert.equal((await request(`/api/websites/${site.id}/${path}`,'POST',{},'owner-token')).status,404);});
test('frontend shares server-first payment hook and migration confirmation workflow',()=>{const hook=readFileSync('src/hooks/usePaystack.ts','utf8'),preview=readFileSync('src/components/website/TemplatePreviewModal.tsx','utf8'),builder=readFileSync('src/components/website/WebsiteBuilderPage.tsx','utf8');assert.ok(hook.includes('initializeStorePayment'));assert.ok(hook.includes('verifyPaymentOnServer(reference)'));assert.ok(preview.includes('res.alreadyExists&&res.site.template_id!==t.id'));assert.ok(preview.includes('requestedTemplateId={changeTarget}'));assert.ok(builder.includes('WebsiteBusinessDashboard'));});
test('signed duplicate webhook and callback race create one pending earning',async()=>{await configure();const result=await Business.initialize(site.id,body());const event={event:'charge.success',data:{reference:result.reference,status:'success',amount:500,currency:'GHS',metadata:transaction.metadata}};const raw=JSON.stringify(event),signature=createHmac('sha512','sk_test_fixture').update(raw).digest('hex');const webhook=()=>originals.fetch(base+'/api/webhooks/paystack',{method:'POST',headers:{'Content-Type':'application/json','x-paystack-signature':signature},body:raw});await Promise.all([webhook(),webhook(),request(`/api/payments/verify/${result.reference}`)]);const rows=await FinanceStore.transaction('owner',tx=>tx.operations());assert.equal(rows.filter(o=>o.kind==='store_sale').length,1);assert.equal((await Business.ownerSummary(site.id,'owner')).earnings.pendingMinor,175);});
test('unsigned managed store webhook is rejected even during tests',async()=>{await configure();const result=await Business.initialize(site.id,body());const response=await request('/api/webhooks/paystack','POST',{event:'charge.success',data:{reference:result.reference,status:'success',amount:500,currency:'GHS',metadata:transaction.metadata}});assert.equal(response.status,401);assert.equal((await OrdersStore.findOrder(result.reference))!.payment_status,'pending');});
test('withdrawn earning refund creates reconciliation rather than impossible balance',async()=>{const order=await paid(true);await seedStore(500);const withdrawalRow=await Business.withdraw(site.id,'owner',withdrawal(600));await FinanceService.withdrawalAction('admin',withdrawalRow.id,{confirmed:true,expectedState:'pending_review',action:'approve'});await FinanceService.withdrawalAction('admin',withdrawalRow.id,{confirmed:true,expectedState:'approved',action:'paid',reference:'fixture-momo'});await OrdersStore.updateOrderStatus(order.id,'refunded','fixture refund',undefined,undefined,{explicitReversal:true});const summary=await Business.ownerSummary(site.id,'owner');assert.equal(summary.earnings.availableMinor,75);assert.equal(summary.earnings.reconciliationRequired,true);assert.equal((await FinanceService.summary('owner')).restricted,true);});
test('reserved refund blocks payout; rejection then recovery appends reversal',async()=>{const order=await paid(true);await seedStore(500);const row=await Business.withdraw(site.id,'owner',withdrawal(600));await FinanceService.withdrawalAction('admin',row.id,{confirmed:true,expectedState:'pending_review',action:'approve'});await OrdersStore.updateOrderStatus(order.id,'refunded','fixture refund',undefined,undefined,{explicitReversal:true});await assert.rejects(()=>FinanceService.withdrawalAction('admin',row.id,{confirmed:true,expectedState:'approved',action:'paid',reference:'fixture-momo'}),/reconciliation/);await FinanceService.withdrawalAction('admin',row.id,{confirmed:true,expectedState:'approved',action:'reject',reason:'Refund must settle'});await Business.syncOrder((await OrdersStore.findOrder(order.id))!);const summary=await Business.ownerSummary(site.id,'owner');assert.equal(summary.earnings.availableMinor,500);assert.equal(summary.ledger.filter(x=>x.description==='Store sale reversal').length,1);});
test('recorded refund blocks payout even before delayed reversal effect',async()=>{const order=await paid(true);await seedStore(500);const row=await Business.withdraw(site.id,'owner',withdrawal(500));await FinanceService.withdrawalAction('admin',row.id,{confirmed:true,expectedState:'pending_review',action:'approve'});const deferred:Array<()=>Promise<void>>=[];await OrdersStore.updateOrderStatus(order.id,'refunded','fixture refund',undefined,undefined,{explicitReversal:true,afterCommit:deferred});await assert.rejects(()=>FinanceService.withdrawalAction('admin',row.id,{confirmed:true,expectedState:'approved',action:'paid',reference:'fixture-momo'}),/reconciliation/);for(const effect of deferred)await effect();});
test('template migration keeps store ledger and withdrawal access',async()=>{await paid(true);const current=(await WebsiteStore.findSiteById(site.id))!;const changed=await WebsiteStore.changeTemplate(site.id,'owner','tmpl-start-blank',current.updated_at);assert.equal(changed.id,site.id);assert.equal(changed.slug,site.slug);assert.equal((await Business.ownerSummary(site.id,'owner')).earnings.availableMinor,175);assert.equal((await Business.catalog(site.id)).products.length,0);});
test('cross-owner pricing and withdrawal writes do not mutate balances',async()=>{await configure();const pricing=await request(`/api/websites/${site.id}/bundles`,'PUT',{expectedVersion:'empty',products:[]},'other-token');assert.equal(pricing.status,403);const response=await request(`/api/websites/${site.id}/store-withdrawals`,'POST',withdrawal(),'other-token');assert.equal(response.status,403);});
test('customer tracking omits store economic and supplier details',async()=>{const order=await paid();const response=await (await request(`/api/orders/lookup/${order.public_reference}`)).json();const projection=JSON.stringify(response);for(const secret of ['wholesaleMinor','ownerId','supplier_cost','store_context','reserveMinor'])assert.ok(!projection.includes(secret));});
test('live production checkout requires live merchant configuration',async()=>{process.env.NODE_ENV='production';try{await assert.rejects(()=>Business.initialize(site.id,body()),/Live managed/);}finally{process.env.NODE_ENV='test';}});

async function withSupplier(response:any,work:(calls:()=>number)=>Promise<void>) {
  const provider=FulfilmentService.getProvider(),client=provider.client;
  const old={enabled:client.isFulfillmentEnabled,configured:client.isConfigured,post:client.createOrder,get:provider.getOrderStatus,test:FulfilmentService.isTestPaymentEnvironment};
  let count=0;
  client.isFulfillmentEnabled=()=>true;client.isConfigured=()=>true;FulfilmentService.isTestPaymentEnvironment=()=>false;
  client.createOrder=async()=>{count++;const order=OrdersStore.adminDevOrders().find(o=>o.status==='queued');assert.equal(order?.manual_review,true);assert.equal(order?.failure_reason,'supplier_submission_uncertain');if(response instanceof Error)throw response;return response;};
  provider.getOrderStatus=async()=>({success:true,status:'delivered',rawResponse:{status:'completed'}});
  try{await work(()=>count);}finally{client.isFulfillmentEnabled=old.enabled;client.isConfigured=old.configured;client.createOrder=old.post;provider.getOrderStatus=old.get;FulfilmentService.isTestPaymentEnvironment=old.test;}
}
for(const response of [Object.assign(new Error('timeout'),{isTimeout:true}),new Error('HTTP 500'),{success:false},{success:true,data:{}}])test(`ambiguous store POST ${JSON.stringify(response)||'error'} is never retried`,async()=>{
  await withSupplier(response,async calls=>{const order=await paid();assert.equal(order.manual_review,true);assert.equal(order.status,'queued');assert.equal(calls(),1);await FulfilmentService.processPaidOrder(order.payment_reference,new Date().toISOString());await Business.recoverEffects();assert.equal(calls(),1);assert.equal((await Business.ownerSummary(site.id,'owner')).earnings.availableMinor,0);assert.equal((await Business.publicOrder(site.id,order.public_reference)).manual_review,true);});
});
test('supplier success persists publicId and releases earning after confirmed delivery',async()=>{
  await withSupplier({success:true,data:{publicId:'fixture-public',status:'completed'}},async calls=>{const order=await paid();assert.equal(order.supplier_order_id,'fixture-public');assert.equal(order.status,'delivered');assert.equal(calls(),1);assert.equal((await Business.ownerSummary(site.id,'owner')).earnings.availableMinor,175);});
});
test('supplier publicId survives local submission write failure and GET recovers without POST',async()=>{
  const old=OrdersStore.saveSupplierSubmission;
  try{OrdersStore.saveSupplierSubmission=async()=>{throw new Error('fixture local state failure');};
    await withSupplier({success:true,data:{publicId:'fixture-recover',status:'processing'}},async calls=>{const order=await paid();assert.equal(order.manual_review,true);assert.equal(order.supplier_order_id,'fixture-recover');const updated=await FulfilmentService.refreshOrderStatusIfDue(order,true);assert.equal(updated.status,'delivered');assert.equal(updated.manual_review,false);assert.equal(calls(),1);assert.equal((await Business.ownerSummary(site.id,'owner')).earnings.availableMinor,175);});
  }finally{OrdersStore.saveSupplierSubmission=old;}
});
test('definitive supplier failure enters refund handling without an available earning',async()=>{
  await withSupplier({success:true,data:{publicId:'fixture-failed',status:'failed'}},async calls=>{const order=await paid();assert.equal(order.status,'refund_pending');assert.equal(calls(),1);assert.equal((await Business.ownerSummary(site.id,'owner')).earnings.availableMinor,0);});
});
test('store tracking rejects other-store references before provider access',async()=>{
  const order=await paid();assert.equal((await request(`/api/websites/unrelated/store-orders/${order.public_reference}`)).status,404);
  const response=await request(`/api/websites/${site.id}/store-orders/${order.public_reference}`);assert.equal(response.status,200);const text=JSON.stringify(await response.json());for(const secret of ['ownerId','wholesaleMinor','supplier_order_id','customer_email'])assert.ok(!text.includes(secret));
});
test('uncertain initialization returns existing safe tracking reference',async()=>{await configure();initFail=true;const result=await request(`/api/websites/${site.id}/store-checkout`,'POST',body());assert.equal(result.status,409);const data=await result.json();assert.match(data.existingOrderReference,/^MH-/);assert.equal((await Business.publicOrder(site.id,data.existingOrderReference)).status,'pending_payment');});
test('CTA capture excludes navigation and checkout controls',()=>{const source=readFileSync('src/services/websiteBusinessApi.ts','utf8');assert.ok(source.includes("target.tagName==='A'"));assert.ok(source.includes("return null;"));const storefront=readFileSync('src/components/website/ManagedDataStorefront.tsx','utf8');assert.ok(storefront.includes('/store-orders/${encodeURIComponent(ref)}'));assert.ok(!storefront.includes('lookupOrderOnServer'));});

test('durable uncertainty write failure prevents any supplier POST',async()=>{
  const old=OrdersStore.saveSupplierUncertainSubmission;
  try{OrdersStore.saveSupplierUncertainSubmission=async()=>{throw Error('fixture write unavailable');};await withSupplier({success:true,data:{publicId:'never-post'}},async calls=>{await paid();assert.equal(calls(),0);});}finally{OrdersStore.saveSupplierUncertainSubmission=old;}
});
test('reviewed paid store order cannot start a supplier POST',async()=>{
  await configure();const payment=await Business.initialize(site.id,body());await OrdersStore.markOrderPaid(payment.reference,new Date().toISOString(),'fixture verified');await OrdersStore.updateOrderReview((await OrdersStore.findOrder(payment.reference))!.id,true);await withSupplier({success:true,data:{publicId:'never-post'}},async calls=>{await FulfilmentService.processPaidOrder(payment.reference,new Date().toISOString());assert.equal(calls(),0);});
});
test('checkout checks the displayed total against initialization before opening payment',()=>{const source=readFileSync('src/hooks/usePaystack.ts','utf8');assert.ok(source.indexOf('initRes.amountPesewas!==options.store.expectedMinor')<source.indexOf('popup.resumeTransaction'));assert.ok(readFileSync('src/components/website/editor/WebsiteEditor.tsx','utf8').includes('onOpenPricing'));});

test('disabled nonzero under-minimum price is rejected without changing any saved row',async()=>{await configure();const catalog=await Business.catalog(site.id,'owner'),floor=catalog.products.find(p=>p.id==='mtn-1gb')!.minimumMinor!;await assert.rejects(()=>Business.savePrices(site.id,'owner',{expectedVersion:catalog.version,products:[{productId:'mtn-1gb',retailMinor:floor-1,enabled:false}]}),/minimum/);assert.equal((await Business.catalog(site.id,'owner')).version,catalog.version);assert.deepEqual((await Business.catalog(site.id,'owner')).products,catalog.products);});


test('public unconfigured catalogue reports empty version without exposing owner configuration',async()=>{
  const response=await request(`/api/websites/${site.id}/storefront`);assert.equal(response.status,200);
  const data=(await response.json()).data;assert.equal(data.version,'empty');assert.deepEqual(data.products,[]);
  const owner=await Business.catalog(site.id,'owner');assert.ok(owner.products.length>0);
  for(const key of ['wholesale','minimumMinor','eligible','policy'])assert.ok(!JSON.stringify(data).includes(key));
});

test('public catalogue retains exact configured network and price while disabled bundles stay hidden',async()=>{
  await configure();const response=await request(`/api/websites/${site.id}/storefront`);assert.equal(response.status,200);
  const data=(await response.json()).data;assert.equal(data.products.length,1);
  assert.equal(data.products[0].network,'mtn');assert.equal(data.products[0].retailMinor,500);
  const current=await Business.catalog(site.id,'owner');await Business.savePrices(site.id,'owner',{expectedVersion:current.version,products:[{productId:'mtn-1gb',retailMinor:500,enabled:false}]});
  assert.deepEqual((await Business.catalog(site.id)).products,[]);
});
