import React from 'react';
import { Users, MousePointerClick, ArrowRight } from 'lucide-react';
import type { PublicRewardRule, RewardLedgerItem } from '../../services/apiClient';
import { formatGhs } from '../../../shared/money';
import { describeReferralReward } from '../../utils/referralRewardCopy';
import { earnCount, earnServiceLabel, rewardStatuses, type EarnSummary } from '../../utils/earnExperience';

export function EarnMetrics({ summary, loading, stale }: { summary: EarnSummary | null; loading: boolean; stale: boolean }) {
  const count = (value: number | undefined) => loading ? 'Loading…' : earnCount(value);
  const metricCountClass = (value: number | undefined) => loading || value === undefined ? 'earn-metric-unknown' : undefined;
  return <section className="earn-section" aria-labelledby="earn-referrals"><div className="earn-section-heading"><h2 id="earn-referrals">Your referrals, at a glance</h2>{stale && <span className="earn-stale">Last available figures</span>}</div><dl className="earn-metrics">
    <div><dt><MousePointerClick size={18} aria-hidden="true" /> Referral visits</dt><dd className={metricCountClass(summary?.rawClicksCount)}>{count(summary?.rawClicksCount)}</dd></div>
    <div><dt><Users size={18} aria-hidden="true" /> Distinct browsers</dt><dd className={metricCountClass(summary?.uniqueVisitorsCount)}>{count(summary?.uniqueVisitorsCount)}</dd></div>
    <div><dt><Users size={18} aria-hidden="true" /> People who joined</dt><dd className={metricCountClass(summary?.referredCustomersCount)}>{count(summary?.referredCustomersCount)}</dd></div>
  </dl><details className="earn-metrics-explainer"><summary>About these figures</summary><p>Referral visits: Recorded link visits, including return visits.</p><p>Distinct browsers: Distinct stored visitor keys. Not verified individual people.</p><p>People who joined: Registered accounts linked directly to you. A purchase is not implied.</p></details><dl className="earn-reward-totals"><div><dt>Pending Rewards</dt><dd>{summary ? formatGhs(summary.pendingRewardsMinor) : loading ? 'Loading…' : 'Unavailable'}</dd><p>Recorded referral rewards awaiting approval.</p></div><div><dt>Total approved rewards</dt><dd>{summary ? formatGhs(summary.approvedRewardsMinor) : loading ? 'Loading…' : 'Unavailable'}</dd><p>Approved referral records. This is not your available balance.</p></div></dl><details className="earn-network"><summary>Explore your three-level network <span>{count(summary?.networkTotalCount)} members</span></summary><p>Direct referrals and the next two levels of linked accounts. Membership alone does not earn a commission.</p><dl>{[
    ['Level 1 · Direct', summary?.networkLevel1Count, 'Members referred by you.'],
    ['Level 2 · Indirect', summary?.networkLevel2Count, 'Members referred by your direct referrals.'],
    ['Level 3 · Indirect', summary?.networkLevel3Count, 'Members referred by Level 2.'],
  ].map(([label, value, description]) => <div key={String(label)}><dt>{label}</dt><dd>{count(value as number | undefined)}</dd><p>{description}</p></div>)}</dl></details></section>;
}

export function EarnRewardActivity({ ledger, loading, stale }: { ledger: RewardLedgerItem[] | null; loading: boolean; stale: boolean }) {
  return <section className="earn-section" aria-labelledby="earn-reward-activity"><div className="earn-section-heading"><h2 id="earn-reward-activity">Reward activity</h2><span className="earn-fine">Latest 50 records{stale ? ' · Last available activity' : ''}</span></div><p>Pending rewards are not spendable. Approved rewards are recorded earnings, not completed withdrawals.</p>
    {loading ? <p role="status">Loading reward activity…</p> : !ledger ? <p role="status">Reward activity is unavailable. Retry activity above.</p> : !ledger.length ? <div className="earn-empty"><h3>No rewards recorded yet</h3><p>Start by sharing your personal link. Eligible purchases can appear here once recorded. Visits alone do not earn money.</p><a className="earn-text-button" href="#earn-personal-link">Go to your referral link <ArrowRight size={16} aria-hidden="true" /></a></div> : <div className="earn-reward-list" tabIndex={0} role="region" aria-label="Latest reward records">{ledger.map(item => {
      const status = rewardStatuses[item.status];
      return <article key={item.id}><div className="earn-reward-main"><h3>{earnServiceLabel(item.service_type)}</h3><span className={`earn-status ${status.className}`}>{status.label}</span><strong className={item.status === 'approved' ? 'text-emerald-300' : item.status === 'pending' ? 'text-amber-300' : 'text-slate-400'}>{item.status === 'reversed' ? '−' : ''}{formatGhs(item.amount_minor)}</strong></div><p>{item.reason || status.explanation}</p><p className="earn-fine">{status.explanation}</p><div className="earn-reward-meta"><time dateTime={item.created_at}>{new Date(item.created_at).toLocaleDateString('en-GH', { day: 'numeric', month: 'short', year: 'numeric' })}</time>{item.reward_stage && item.reward_stage !== 'standard' && <span>{item.reward_stage === 'acquisition' ? 'First qualifying purchase' : 'Repeat qualifying purchase'}</span>}{item.network_level && <span>Level {item.network_level}</span>}</div></article>;
    })}</div>}
  </section>;
}

export function EarnRules({ rules, error, retry }: { rules: PublicRewardRule[] | null; error: boolean; retry: () => void }) {
  return <section className="earn-section" aria-labelledby="earn-rules"><h2 id="earn-rules">Current reward opportunities</h2>{error ? <p role="alert">Reward rules are unavailable. Eligibility cannot be confirmed. <button className="earn-text-button" onClick={retry}>Retry reward rules</button></p> : !rules ? <p role="status">Checking current reward rules…</p> : !rules.length ? <p>No reward rules are currently enabled for qualifying purchases. You can explore and share services, but a reward is not promised.</p> : <><p>These are the active reward rules. Eligible orders and account conditions still apply.</p><ul className="earn-rules-list">{rules.map(rule => <li key={rule.id}><h3>{earnServiceLabel(rule.service_type)}{rule.network ? ` · ${rule.network === 'airteltigo' ? 'AirtelTigo' : rule.network.toUpperCase()}` : ''}</h3><p>{describeReferralReward(rule)}</p>{rule.product_key && <p className="earn-fine">Selected products only.</p>}{rule.ends_at && <p className="earn-fine">Until {new Date(rule.ends_at).toLocaleDateString('en-GH')}</p>}</li>)}</ul><p className="earn-fine">Final rewards also depend on the service’s current reward policy and eligible order. Data rewards may use a separate margin-based policy rather than the published amount above. Your reward activity confirms the amount actually recorded.</p></> }</section>;
}

export function EarnHowItWorks() {
  return <section id="how-it-works-section" className="earn-section"><h2>How Mystery Earn works</h2><ol className="earn-steps"><li><span>1</span><div><h3>Get your personal link</h3><p>Create a free account. Your referral identity stays linked to your account.</p></div></li><li><span>2</span><div><h3>Share something useful</h3><p>Send your link to someone who could use Mystery Hub. Visits and registrations are tracked separately.</p></div></li><li><span>3</span><div><h3>Follow qualifying rewards</h3><p>Eligible completed purchases can earn rewards under the active reward rules. Review activity and Available Earnings before using funds.</p></div></li></ol></section>;
}
