import React from 'react';
import type { TemplateItem } from '../../../types';
import { WebsiteImageField } from './WebsiteImageField';
import { websiteTemplateItemFields } from '../../../config/websiteBuilder';
/** Edits existing template/store vocabulary without replacing the template's layout. */
export function WebsiteTemplateItemsControl({items,onChange,siteId,token,templateId}:{items:TemplateItem[];onChange:(items:TemplateItem[])=>void;siteId:string;token:string;templateId:string}) {
  const fields=websiteTemplateItemFields(templateId);
  return <div className="space-y-3 border-t border-slate-800 pt-4"><div className="flex justify-between items-center gap-2"><h3 className="text-sm font-semibold text-white">Template Items ({items.length}/50)</h3><button type="button" disabled={items.length>=50} onClick={()=>onChange([...items,{id:`item-${crypto.randomUUID()}`,name:'New item'}])} className="px-3 py-2 rounded-xl bg-emerald-500/15 text-emerald-300 text-xs disabled:opacity-40">Add Item</button></div><p className="text-xs text-slate-400">Edit the products, rooms, menu entries or services shown by your current template.</p>{items.map((item,index)=>{
    const update=(patch:Partial<TemplateItem>)=>onChange(items.map((value,n)=>n===index?{...value,...patch}:value));
    return <article key={item.id || index} className="rounded-xl p-3 border border-slate-800 space-y-3"><div className="flex justify-between gap-2"><strong className="text-xs text-slate-300">Item {index+1}</strong><button type="button" onClick={()=>onChange(items.filter((_,n)=>n!==index))} className="text-xs text-rose-300">Remove Item</button></div><div className="grid sm:grid-cols-2 gap-2">{(['name','price','category','tag'] as const).filter(field=>fields.includes(field)).map(field=><label key={field} className="text-xs text-slate-400">{field==='name'?'Name':field==='price'?'Price (GH₵)':field==='category'?'Category / filter':'Tag'}<input aria-label={`Template item ${index+1} ${field}`} maxLength={field==='name'?100:field==='category'?50:40} value={item[field] || ''} onChange={e=>update({[field]:e.target.value})} className="mt-1 block w-full p-2 rounded-lg bg-slate-900 border border-slate-800 text-white" /></label>)}</div><label className="text-xs text-slate-400 block">Description<textarea maxLength={300} value={item.desc || ''} onChange={e=>update({desc:e.target.value})} className="mt-1 block w-full p-2 rounded-lg bg-slate-900 border border-slate-800 text-white" /></label>{fields.includes('image') && <WebsiteImageField label={`Template item ${index+1} image`} value={item.image || ''} onChange={image=>update({image})} siteId={siteId} token={token} />}</article>;
  })}</div>;
}
