import React,{useEffect,useState} from 'react';
import { websiteBusinessRequest } from '../../../services/websiteBusinessApi';
import { formatGhs,parseGhs } from '../../../../shared/money';
const field='w-full min-h-11 p-3 bg-slate-900 border border-slate-700 rounded-lg';
const button='min-h-11 px-4 py-2 rounded-lg bg-slate-800 border border-slate-700 disabled:opacity-50';
export function AdminResellerControls({token,siteId}:{token:string;siteId?:string}) {
  const [data,setData]=useState<any>(null),[policy,setPolicy]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[open,setOpen]=useState(false);
  const refresh=async()=>{const next=await websiteBusinessRequest(siteId?`admin/website-builder/${siteId}/business`:'admin/website-builder/reseller-config',token);setData(next);if(!siteId)setPolicy({...next.policy,reserveFixed:(next.policy.reserveFixedMinor/100).toFixed(2),minimum:(next.policy.withdrawalMinimumMinor/100).toFixed(2)});};
  useEffect(()=>{if(siteId||open)void refresh().catch(e=>setError(e.message));},[siteId,token,open]);
  const run=async(work:()=>Promise<unknown>)=>{setBusy(true);setError('');try{await work();await refresh();}catch(e:any){setError(e.message);}finally{setBusy(false);}};
  return <section className="border-t border-slate-800 pt-4 space-y-4 min-w-0">
    {!siteId&&<button type="button" className={button} aria-expanded={open} onClick={()=>setOpen(!open)}>Managed reseller pricing & policy</button>}
    {error&&<p role="alert" className="text-rose-300 text-sm">{error}</p>}
    {(siteId||open)&&data&&<>
      {siteId?<><h3 className="font-bold">Business records</h3><div className="grid grid-cols-2 gap-3 text-sm">{[['Views',data.analytics.views],['Visitors',data.analytics.uniqueVisitors],['Checkout starts',data.analytics.checkoutStarts],['Paid orders',data.analytics.paidOrders],['Delivered',data.analytics.deliveredOrders],['Sales',formatGhs(data.analytics.salesMinor)],['Pending earnings',formatGhs(data.earnings.pendingMinor)],['Available earnings',formatGhs(data.earnings.availableMinor)],['Reserved',formatGhs(data.earnings.reservedMinor)],['Withdrawn',formatGhs(data.earnings.withdrawnMinor)]].map(([label,value])=><p key={String(label)}><span className="block text-xs text-slate-400">{label}</span>{value}</p>)}</div><p className="text-xs text-slate-400">Financial balances are ledger derived. Review Store Earnings withdrawals in Financial Control Room. Mark Paid records a manual payout; it does not send funds.</p>{data.orders.map((o:any)=><details key={o.id} className="border-b border-slate-800 py-3 text-sm"><summary className="break-all">{o.reference} · {o.status} · {o.recipient}</summary><p>Retail {formatGhs(o.snapshot.retailMinor)} · Wholesale {formatGhs(o.snapshot.wholesaleMinor)} · Reserve {formatGhs(o.snapshot.reserveMinor)} · Store earning {formatGhs(o.snapshot.earningMinor)}</p><p className="break-all text-xs text-slate-400">Policy {o.snapshot.policyVersion} · Wholesale {o.snapshot.wholesaleVersion} · Price {o.snapshot.priceVersion}</p>{['refunded','failed','cancelled'].includes(o.status)&&<button type="button" disabled={busy} className={button} onClick={()=>{const reason=window.prompt('Reconciliation reason (recover funds or release reservations first)');if(reason&&window.confirm('Reconcile this store earning reversal?'))void run(()=>websiteBusinessRequest(`admin/website-builder/store-orders/${o.id}/reconcile`,token,{confirmed:true,reason}));}}>Reconcile earning reversal</button>}</details>)}<h4 className="font-semibold">Store ledger</h4>{data.ledger.map((entry:any)=><p key={entry.id} className="text-xs">{entry.description} · {entry.delta_minor} pesewas · {entry.created_at}</p>)}</>:<>
        <p className="text-sm text-slate-400">Stores remain disabled until an explicit processing reserve and wholesale prices covering supplier cost are configured. These changes do not alter historical order economics.</p>
        <form className="grid sm:grid-cols-2 gap-3" onSubmit={event=>{event.preventDefault();if(!window.confirm('Apply this managed-store economics policy?'))return;void run(()=>websiteBusinessRequest('admin/website-builder/reseller-policy',token,{confirmed:true,expectedVersion:data.policy.version,enabled:policy.enabled,reserveBps:Number(policy.reserveBps),reserveFixedMinor:policy.reserveFixed==='0'||policy.reserveFixed==='0.00'?0:parseGhs(policy.reserveFixed),withdrawalMinimumMinor:parseGhs(policy.minimum),withdrawalFeeBps:Number(policy.withdrawalFeeBps)},'PUT'));}}>
          <label className="min-h-11 flex gap-2 items-center"><input type="checkbox" checked={policy.enabled} onChange={event=>setPolicy({...policy,enabled:event.target.checked})}/>Enable managed store payments</label>
          {([['reserveBps','Processing reserve (basis points)'],['reserveFixed','Fixed processing reserve (GH₵)'],['minimum','Store withdrawal minimum (GH₵)'],['withdrawalFeeBps','Store withdrawal fee (basis points)']] as const).map(([name,label])=><label key={name} className="text-sm">{label}<input className={field} inputMode="decimal" value={policy[name]} onChange={event=>setPolicy({...policy,[name]:event.target.value})}/></label>)}<button className={button} disabled={busy}>Save policy with confirmation</button>
        </form>
        <div className="grid sm:grid-cols-2 xl:grid-cols-3 gap-3">{data.products.map((p:any)=><WholesaleProduct key={p.id+data.policy.version+(p.wholesale?.version||'')} product={p} busy={busy} save={input=>run(()=>websiteBusinessRequest('admin/website-builder/reseller-wholesale',token,input,'PUT'))}/>)}</div>
      </>}
    </>}
  </section>;
}
function WholesaleProduct({product:p,busy,save}:{product:any;busy:boolean;save:(input:any)=>void}) {
  const [price,setPrice]=useState(p.wholesale?(p.wholesale.wholesaleMinor/100).toFixed(2):''),[enabled,setEnabled]=useState(p.wholesale?.enabled||false),[error,setError]=useState('');
  return <form className="border border-slate-800 rounded-lg p-3 space-y-3 min-w-0" onSubmit={event=>{event.preventDefault();setError('');try{const amount=parseGhs(price);if(!window.confirm(`Save wholesale for ${p.network.toUpperCase()} ${p.dataAmount}?`))return;save({confirmed:true,productId:p.id,expectedVersion:p.wholesale?.version||'empty',wholesaleMinor:amount,enabled});}catch(e:any){setError(e.message);}}}><strong>{p.network.toUpperCase()} {p.dataAmount}</strong><p className="text-xs text-slate-400">Current supplier cost: {p.supplierCostMinor===null?'Unavailable — activation blocked':formatGhs(p.supplierCostMinor)}</p><label className="block text-sm">Reseller wholesale (GH₵)<input className={field} value={price} inputMode="decimal" onChange={event=>setPrice(event.target.value)}/></label><label className="flex min-h-11 items-center gap-2"><input type="checkbox" checked={enabled} disabled={p.supplierCostMinor===null} onChange={event=>setEnabled(event.target.checked)}/>Enabled</label>{p.wholesale&&<p className="text-xs text-slate-400">Updated {new Date(p.wholesale.updatedAt).toLocaleString()}</p>}{error&&<p role="alert" className="text-rose-300 text-sm">{error}</p>}<button disabled={busy} className={button}>Save wholesale</button></form>;
}
