import { AdminResellerControls } from './AdminResellerControls';
import React, { useEffect, useRef, useState } from 'react';
import { getAdminWebsiteSummary, forceUnpublishWebsite } from '../../../services/apiClient';
import type { WebsiteAdminSummary, AdminWebsiteRow } from '../../../config/websiteAnalytics';
import { WEBSITE_TEMPLATES } from '../../../data/templates';
const title=(id:string)=>WEBSITE_TEMPLATES.find(t=>t.id===id)?.title || id;
export function AdminWebsiteBuilderSection({sessionToken}:{sessionToken:string}) {
  const [range,setRange]=useState('30'),[search,setSearch]=useState(''),[status,setStatus]=useState(''),[template,setTemplate]=useState(''),[offset,setOffset]=useState(0);
  const [data,setData]=useState<WebsiteAdminSummary | null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false),[refresh,setRefresh]=useState(0),[selected,setSelected]=useState<AdminWebsiteRow | null>(null),[confirmation,setConfirmation]=useState(''),[busy,setBusy]=useState(false);
  const dialog=useRef<HTMLDialogElement>(null);
  useEffect(()=>{setOffset(0);},[range,search,status,template]);
  useEffect(()=>{
    let current=true;setLoading(true);setError('');
    const timer=setTimeout(()=>{void getAdminWebsiteSummary(sessionToken,{range,search,status,template,offset}).then(result=>{if(current)setData(result);}).catch(e=>{if(current){setError(e.message);setData(null);}}).finally(()=>{if(current)setLoading(false);});},200);
    return ()=>{current=false;clearTimeout(timer);};
  },[sessionToken,range,search,status,template,offset,refresh]);
  useEffect(()=>{if(selected){setConfirmation('');dialog.current?.showModal();}},[selected]);
  return <section className="space-y-5 text-left min-w-0">
    <header><h1 className="text-2xl font-bold text-white">Website Builder</h1><p className="text-sm text-slate-400">Free website adoption and operational controls.</p></header>
    <div className="flex flex-wrap gap-2"><input aria-label="Search websites" placeholder="Name, owner, slug or site ID" value={search} onChange={e=>setSearch(e.target.value)} maxLength={100} className="p-2 rounded-xl bg-slate-900 border border-slate-700 min-w-0 flex-1" /><select aria-label="Website date range" value={range} onChange={e=>setRange(e.target.value)} className="p-2 rounded-xl bg-slate-900 border border-slate-700">{['7','30','90','all'].map(r=><option key={r} value={r}>{r==='all'?'All time':`${r} days`}</option>)}</select><select aria-label="Website status" value={status} onChange={e=>setStatus(e.target.value)} className="p-2 rounded-xl bg-slate-900 border border-slate-700"><option value="">All statuses</option><option value="draft">Draft</option><option value="published">Published</option></select><select aria-label="Website template" value={template} onChange={e=>setTemplate(e.target.value)} className="p-2 rounded-xl bg-slate-900 border border-slate-700 max-w-full"><option value="">All templates</option>{WEBSITE_TEMPLATES.map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select><button type="button" onClick={()=>setRefresh(n=>n+1)} className="px-3 py-2 rounded-xl bg-slate-800">Refresh</button></div>
    {error && <p role="alert" className="text-rose-300">{error}</p>}{loading && <p role="status" className="text-slate-400 text-sm">Loading websites…</p>}
    {data && <>
      <p className="text-xs text-slate-400">Project metrics and lists use creation date in the selected range; recent publications use publication date. Template/status/search filters apply to the project list.</p>
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-3">{[['Total Website Projects',data.metrics.total],['Draft Sites',data.metrics.draft],['Published Sites',data.metrics.published],['Free Sites',data.metrics.free]].map(([label,value])=><div key={label} className="p-4 bg-slate-900 border border-slate-800 rounded-2xl"><p className="text-xs text-slate-400">{label}</p><strong className="text-2xl text-white">{value}</strong></div>)}</div>
      <div className="p-4 rounded-2xl bg-slate-900 border border-slate-800 space-y-3"><h2 className="font-bold">Adoption funnel</h2><div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-5 gap-3">{[['Unique Builder Visitors',data.funnel.uniqueVisitors],['Template Preview Events',data.funnel.previews],['Build Start Events',data.funnel.buildStarts],['Site Creation Events',data.funnel.created],['Publication Events',data.funnel.published]].map(([label,value])=><div key={label} className="text-sm"><p className="text-xs text-slate-400">{label}</p><strong>{value}</strong></div>)}</div><p className="text-xs text-slate-400">Build Start → Created: {data.funnel.startToCreate===null?'No starts yet':`${data.funnel.startToCreate.toFixed(1)}%`} · Created → Published: {data.funnel.createToPublish===null?'No creations yet':`${data.funnel.createToPublish.toFixed(1)}%`}. Conversions count matched users/sites with ordered actions in this range. Raw events are not people; repeat publications count as events.</p></div>
      <div className="grid sm:grid-cols-2 gap-3">{[['Recently created',data.recentCreated],['Recently published',data.recentPublished]].map(([label,sites])=><div key={label as string} className="p-4 rounded-2xl border border-slate-800 bg-slate-900"><h2 className="font-bold mb-2">{label as string}</h2>{(sites as AdminWebsiteRow[]).length ? (sites as AdminWebsiteRow[]).map(site=><button type="button" key={site.id} onClick={()=>setSelected(site)} className="block text-sm text-emerald-300 py-1 break-all">{site.businessName || site.name}</button>) : <p className="text-xs text-slate-400">No sites in this range.</p>}</div>)}</div>
      <div className="p-4 rounded-2xl border border-slate-800 bg-slate-900"><h2 className="font-bold mb-3">Template performance</h2>{data.templates.length ? [...data.templates].sort((a,b)=>b.previews-a.previews || b.created-a.created).map(t=><div key={t.templateId} className="flex flex-wrap justify-between gap-2 border-t border-slate-800 py-2 text-xs"><strong>{title(t.templateId)}</strong><span className="text-slate-400">{t.previews} previews · {t.created} created · {t.projects} current projects · {t.published} published projects</span></div>) : <p className="text-xs text-slate-400">No template activity yet.</p>}</div>
      <p className="text-xs text-slate-400">Cloudinary configured: {data.media.configured?'Yes':'No'} · Free limit: {data.media.maxAssets} images / {Math.round(data.media.maxBytes/1024/1024)} MB each · {data.media.ready} ready / {data.media.tracked} tracked · {data.media.cleanupPending} pending cleanup</p>
      <div className="space-y-2">{data.sites.length ? data.sites.map(site=><article key={site.id} className="p-4 rounded-xl border border-slate-800 bg-slate-900 flex flex-wrap gap-3 justify-between"><div className="min-w-0"><h3 className="font-semibold break-words">{site.businessName || site.name}</h3><p className="text-xs text-slate-400 break-all">{site.ownerName} · {title(site.template_id)} · {site.status} · {site.assetCount} images</p><p className="text-xs text-slate-500">Created {new Date(site.created_at).toLocaleDateString()} · Updated {new Date(site.updated_at).toLocaleDateString()}</p></div><button type="button" onClick={()=>setSelected(site)} className="px-3 py-2 bg-slate-800 rounded-xl text-xs">Inspect Site</button></article>) : <p className="text-slate-400 text-sm">No websites match these filters.</p>}</div>
      <div className="flex justify-between gap-3 text-sm"><button type="button" disabled={!offset} onClick={()=>setOffset(n=>Math.max(0,n-data.limit))}>Previous</button><span>{data.total ? `${offset+1}–${Math.min(offset+data.limit,data.total)} of ${data.total}` : '0 sites'}</span><button type="button" disabled={offset+data.limit>=data.total} onClick={()=>setOffset(n=>n+data.limit)}>Next</button></div>
    </>}
    <AdminResellerControls token={sessionToken}/>
    {selected && <dialog ref={dialog} aria-labelledby="admin-website-title" onCancel={e=>{e.preventDefault();if(!busy)setSelected(null);}} className="fixed inset-0 m-auto w-[calc(100%-2rem)] max-w-xl max-h-[85dvh] overflow-auto rounded-2xl bg-[#0b131a] text-white border border-slate-700 p-5 backdrop:bg-black/70"><div className="flex justify-between gap-3"><h2 id="admin-website-title" className="font-bold">{selected.businessName || selected.name}</h2><button type="button" disabled={busy} onClick={()=>setSelected(null)}>Close</button></div><dl className="text-sm space-y-2 my-4 break-words">{[['Owner',selected.ownerName],['Site ID',selected.id],['Template',title(selected.template_id)],['Status',selected.status],['Created',selected.created_at],['Updated',selected.updated_at],['Published',selected.published_at || 'Not published'],['Images',selected.assetCount]].map(([label,value])=><div key={label}><dt className="text-slate-500 text-xs">{label}</dt><dd>{value}</dd></div>)}</dl>{selected.publicUrl ? <a href={selected.publicUrl} target="_blank" rel="noopener noreferrer" className="text-emerald-300 underline text-sm">Open Public Site</a> : <p className="text-slate-400 text-sm">Draft is private; no public URL.</p>}{selected.template_id==='tmpl-data-reseller' && <AdminResellerControls token={sessionToken} siteId={selected.id}/>}{selected.status==='published' && <div className="mt-4 pt-4 border-t border-slate-800 space-y-3"><p className="text-sm text-amber-300">Force Unpublish hides the public site without editing the owner’s content. This action is audited.</p><label className="block text-xs">Type {selected.slug} to confirm<input value={confirmation} onChange={e=>setConfirmation(e.target.value)} className="block w-full mt-2 p-3 bg-slate-900 border border-slate-700 rounded-xl" /></label><button type="button" disabled={busy || confirmation!==selected.slug} className="bg-rose-600 text-white px-4 py-2 rounded-xl disabled:opacity-40" onClick={async()=>{setBusy(true);setError('');try{await forceUnpublishWebsite(sessionToken,selected.id,confirmation);setSelected(null);setRefresh(n=>n+1);}catch(e:any){setError(e.message);}finally{setBusy(false);}}}>Confirm Force Unpublish</button></div>}{error && <p role="alert" className="text-rose-300 text-sm mt-3">{error}</p>}</dialog>}
  </section>;
}
