import React,{useEffect,useState} from 'react';
import {commercialRequest} from '../../../services/commercialApi';
import {formatGhs,parseGhs,percentMinor} from '../../../../shared/money';
import {AdminResellerControls} from './AdminResellerControls';
const field='min-h-11 w-full rounded-lg border border-slate-700 bg-slate-950 p-2';
const button='min-h-11 rounded-lg bg-emerald-700 px-4 py-2 disabled:opacity-50';
const cash=(value:number|null)=>value===null?'Unknown / not configured':formatGhs(value);
function auditChanges(a:any){
 try{const {previous,next}=JSON.parse(a.metadata_safe_json||'{}');if(!next)return [];
 const lines:string[]=[];for(const key of ['enabled','discountMinor','reserveBps','reserveFixedMinor','wholesaleMinor','withdrawalFeeBps'])if(previous?.[key]!==next[key]&&next[key]!==undefined)lines.push(`${key.replace(/([A-Z])/g,' $1')}: ${previous?.[key]??'unconfigured'} -> ${next[key]}${key.endsWith('Minor')?' pesewas':''}`);
 for(const [id,p] of Object.entries(next.products||{}) as [string,any][])if(JSON.stringify(previous?.products?.[id])!==JSON.stringify(p))lines.push(`${id}: retail ${cash(previous?.products?.[id]?.retailMinor??null)} -> ${cash(p.retailMinor)}, available ${String(p.enabled)}, reseller suggestion ${cash(p.recommendedMinor)}`);
 return lines;}catch{return [];}
}
export function AdminCommercialSection({token}:{token:string}) {
 const [data,setData]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const [bps,setBps]=useState('0'),[fixed,setFixed]=useState('0'),[discount,setDiscount]=useState('1'),[enabled,setEnabled]=useState(true);
 const previewDiscount=(()=>{try{return parseGhs(discount);}catch{return null;}})();
 const acquisitionPreview=(p:any)=>{if(previewDiscount===null||p.supplierCostMinor===null||!data.prices.reserveConfigured)return null;const total=p.retailMinor-previewDiscount;if(total<=0)return null;const rule=p.firstReferralRule;const requested=data.dataReferralPolicy?.enabled&&data.dataReferralPolicy.mode==='stage_margin_percent'?p.firstReferralRewardMinor:rule?.type==='fixed_minor'?rule.minor??0:rule?.bps!=null?percentMinor(total,rule.bps):0;const reward=data.dataReferralPolicy?.enabled&&data.dataReferralPolicy.mode==='stage_margin_percent'?requested:requested<=total?requested:0;return total-p.supplierCostMinor-percentMinor(total,data.prices.reserveBps)-data.prices.reserveFixedMinor-reward;};
 const refresh=async()=>{const r=await commercialRequest('admin/commercial',token);setData(r);setBps(String(r.prices.reserveBps));setFixed((r.prices.reserveFixedMinor/100).toFixed(2));setDiscount((r.offer.discountMinor/100).toFixed(2));setEnabled(r.offer.enabled);};
 useEffect(()=>{void refresh().catch(e=>setError(e.message));},[token]);
 const submit=(create:()=>any)=>{try{void save(create());}catch(e:any){setError(e.message);}};
 const save=async(body:any)=>{if(!window.confirm('Change future commercial pricing? Historical orders stay unchanged. Negative welcome contribution is an intentional acquisition subsidy.'))return;setBusy(true);setError('');try{await commercialRequest('admin/commercial',token,{...body,confirmed:true});await refresh();}catch(e:any){setError(e.message);}finally{setBusy(false);}};
 return <section className="space-y-5 min-w-0"><h2 className="text-xl font-bold">Commercial Pricing & Welcome Offer</h2>{error&&<p role="alert" className="text-rose-300">{error}</p>}{!data?<p>Loading prices and offer settings…</p>:<>
 <p className="text-sm text-slate-400">Future direct prices only. Supplier cost is live provider authority. Reseller wholesale and owner retail remain separate. Unknown cost/contribution is not a profit estimate.</p>
 <form className="grid sm:grid-cols-3 gap-3" onSubmit={e=>{e.preventDefault();submit(()=>({kind:'pricing',expectedVersion:data.prices.version,configureReserve:true,reserveBps:Number(bps),reserveFixedMinor:/^0(?:\.0{1,2})?$/.test(fixed.trim())?0:parseGhs(fixed),products:[]}));}}>
  <label>Direct processing reserve (basis points)<input className={field} type="number" value={bps} onChange={e=>setBps(e.target.value)} min={0} max={9999}/></label><label>Fixed reserve (GH₵)<input className={field} value={fixed} onChange={e=>setFixed(e.target.value)}/></label><button disabled={busy} className={button}>Save direct reserve</button>
 </form>
 {data.dataReferralPolicy?.enabled&&data.dataReferralPolicy.mode==='stage_margin_percent'&&<p className="text-sm">Data referrals: first {data.dataReferralPolicy.acquisitionBps/100}% of normal contribution before Welcome; recurring {data.dataReferralPolicy.recurringBps/100}% of actual contribution. Unknown cost or reserve stops the reward, not checkout.</p>}
 {!data.prices.reserveConfigured&&<p className="text-amber-300">Direct reserve is unconfigured. Contribution after payment costs cannot yet be estimated.</p>}
 <form className="space-y-3 rounded-xl border border-slate-700 p-4" onSubmit={e=>{e.preventDefault();submit(()=>({kind:'offer',expectedVersion:data.offer.version,enabled,discountMinor:parseGhs(discount),services:['data'],requirement:'unique_phone'}));}}>
  <h3 className="font-bold">Welcome Offer</h3>{previewDiscount!==null&&data.products.filter((p:any)=>p.id==='mtn-1gb').map((p:any)=><p key={p.id}>MTN 1GB example: {cash(p.retailMinor)} regular - {cash(previewDiscount)} discount = {cash(p.retailMinor-previewDiscount)} customer total</p>)}{enabled&&previewDiscount!==null&&data.products.some((p:any)=>acquisitionPreview(p)!==null&&acquisitionPreview(p)!<0)&&<p role="alert" className="text-rose-300 font-bold">Warning: this promotion plus an eligible first referral reward creates negative expected contribution for at least one package. Saving deliberately authorizes an acquisition subsidy.</p>}<label className="flex gap-2"><input type="checkbox" checked={enabled} onChange={e=>setEnabled(e.target.checked)}/>Enabled for direct Data</label><label className="block">Welcome discount (GH₵)<input className={field} value={discount} onChange={e=>setDiscount(e.target.value)}/></label>
  <p className="text-sm">Eligibility: signed-in buyer, unique Ghana account phone, no previous qualifying direct purchase or redeemed benefit. No OTP ownership claim. Reseller stores, Airtime, AFA and Marketplace excluded.</p><p className="text-xs">Last changed: {data.offer.updatedAt||'Launch default'}</p><button disabled={busy} className={button}>Save welcome offer</button>
 </form>
 <div className="grid lg:grid-cols-2 gap-4">{data.products.map((p:any)=><form key={p.id} className="rounded-xl border border-slate-700 p-4 space-y-2" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);submit(()=>({kind:'pricing',expectedVersion:data.prices.version,reserveBps:data.prices.reserveBps,reserveFixedMinor:data.prices.reserveFixedMinor,products:[{productId:p.id,retailMinor:parseGhs(String(f.get('retail'))),recommendedMinor:f.get('recommended')?parseGhs(String(f.get('recommended'))):null,enabled:f.get('enabled')==='on'}]}));}}>
  <h3 className="font-bold">{p.networkName} {p.dataAmount}</h3><div className="grid grid-cols-2 gap-2 text-sm">{[['Supplier cost',p.supplierCostMinor],['Current direct retail',p.retailMinor],['Gross spread',p.spreadMinor],['Payment reserve',p.reserveMinor],['Direct contribution',p.contributionMinor],['Welcome total',p.discountedMinor],['Welcome contribution',p.promoContributionMinor],['Eligible first referral reward',p.firstReferralRewardMinor],['Contribution after first referral',p.acquisitionContributionMinor],['Recurring referral estimate',p.recurringReferralRewardMinor],['Retained recurring contribution',p.recurringContributionMinor],['Reseller wholesale',p.wholesaleMinor],['Safe reseller floor',p.safeResellerFloor]].map(([label,value])=><p key={String(label)}><span className="block text-slate-400">{label}</span>{cash(value as number|null)}</p>)}</div>
  {p.contributionMinor!==null&&p.contributionMinor<0&&<p role="alert" className="text-rose-300 font-bold">Warning: regular retail does not cover supplier cost plus the configured reserve.</p>}<p className="text-sm">Price per GB: GH₵{p.pricePerGb.toFixed(2)}</p>{p.promoContributionMinor!==null&&p.promoContributionMinor<0&&<p role="alert" className="text-amber-300">Welcome offer has negative expected contribution: an explicit acquisition subsidy.</p>}
  {p.acquisitionContributionMinor!==null&&p.acquisitionContributionMinor<0&&<p role="alert" className="text-amber-300">Promotion plus first referral has negative contribution: an intentional acquisition subsidy, not a blocked reward.</p>}
  <label className="block">Future direct retail (GH₵)<input key={p.retailMinor} name="retail" className={field} defaultValue={(p.retailMinor/100).toFixed(2)}/></label><label className="block">Recommended reseller retail (optional, GH₵)<input key={String(p.recommendedMinor)} name="recommended" className={field} defaultValue={p.recommendedMinor===null?'':(p.recommendedMinor/100).toFixed(2)}/></label><label className="flex gap-2"><input key={String(p.enabled)} name="enabled" type="checkbox" defaultChecked={p.enabled}/>Direct product available</label><button disabled={busy} className={button}>Save future price</button>
 </form>)}</div>
 <AdminResellerControls token={token}/><h3 className="font-bold">Recent pricing and offer changes</h3>{data.audit.map((a:any)=><details key={a.id} className="text-sm break-words"><summary>{a.created_at} · {a.action} · Admin {a.admin_user_id} · {a.entity_id}</summary>{auditChanges(a).map((line:string,i:number)=><p key={i}>{line}</p>)}</details>)}
 </>}</section>;
}
