import React,{useEffect,useMemo,useState} from 'react';
import {adminEarnRequest,type EarnOverview,type EarnReferrer,type EarnDetail,type EarnLedgerRow} from '../../../services/apiClient';
import type {EarnPage} from '../../../../server/types/adminEarn';
import {AdminEarnRules} from './AdminEarnRules';
import {AdminEarnDialog,EarnPager,earnButton,earnInput,earnMoney} from './AdminEarnUi';

const labels:Record<string,string>={rawClicks:'Raw capture events',uniqueVisitors:'Unique visitors',referredCustomers:'People referred (period)',lifetimeReferredCustomers:'People referred (lifetime)',
  firstConversions:'First-purchase conversions',repeatConversions:'Repeat qualifying conversions',qualifyingOrders:'Qualifying orders',convertedCustomers:'Converted relationships',
  paidRevenueMinor:'Referral paid revenue',deliveredRevenueMinor:'Referral delivered revenue',pendingRewardsMinor:'Pending rewards',approvedRewardsMinor:'Approved rewards',reversedRewardsMinor:'Reversed rewards',
  rewardExpenseMinor:'Reward expense (approved)',grossMarginMinor:'Gross margin (known costs only)',costKnownOrders:'Orders with known supplier cost'};
function Metrics({metrics}:{metrics:EarnOverview['metrics']}) {return <div className="grid grid-cols-2 md:grid-cols-3 xl:grid-cols-4 gap-3">{Object.entries(metrics).filter(([key,value])=>key in labels&&typeof value==='number').map(([key,value])=><div key={key} className="p-3 rounded-xl bg-[#0f171d] border border-slate-800"><p className="text-xs text-slate-400">{labels[key]}</p><p className="font-bold text-lg break-words mt-1">{key.endsWith('Minor')?earnMoney(value):value.toLocaleString()}</p></div>)}</div>;}
function Ledger({data}:{data:EarnPage<EarnLedgerRow>}) {return <div className="space-y-3">{data.items.length===0&&<p className="text-slate-400">No matching ledger entries.</p>}{data.items.map(row=><article key={row.id} className="p-3 rounded-xl bg-slate-900 border border-slate-800 text-xs space-y-1">
  <div className="flex justify-between flex-wrap gap-2"><strong>{row.referrerName} · {earnMoney(row.amountMinor)}</strong><span>{row.status} · {row.stage}</span></div>
  <p className="break-all">Ledger: {row.id} · Order: {row.orderReference||'No linked order'} · {row.service}</p><p>{row.reason}</p>
  <p className="text-slate-400">Created {new Date(row.createdAt).toISOString()} · Approved {row.approvedAt?new Date(row.approvedAt).toISOString():'—'} · Reversed {row.reversedAt?new Date(row.reversedAt).toISOString():'—'}</p>
</article>)}</div>;}
export const AdminMysteryEarnSection:React.FC<{sessionToken:string;initialReferrerId?:string|null;onOpenCustomer:(id:string)=>void}>=({sessionToken,initialReferrerId,onOpenCustomer})=>{
  const [view,setView]=useState<'leaderboard'|'rules'|'ledger'>('leaderboard');const [period,setPeriod]=useState('30d');const [start,setStart]=useState('');const [end,setEnd]=useState('');
  const [overview,setOverview]=useState<EarnOverview|null>(null);const [board,setBoard]=useState<EarnPage<EarnReferrer>|null>(null);const [ledger,setLedger]=useState<EarnPage<EarnLedgerRow>|null>(null);
  const [search,setSearch]=useState('');const [sort,setSort]=useState('conversions');const [page,setPage]=useState(1);const [giveaway,setGiveaway]=useState(false);
  const [excludeDisabled,setExcludeDisabled]=useState(false);const [excludeSuspended,setExcludeSuspended]=useState(false);const [excludeZero,setExcludeZero]=useState(false);
  const [status,setStatus]=useState('');const [service,setService]=useState('');const [stage,setStage]=useState('');const [referrer,setReferrer]=useState('');const [order,setOrder]=useState('');
  const [selected,setSelected]=useState<string|null>(initialReferrerId||null);const [detail,setDetail]=useState<EarnDetail|null>(null);const [detailPage,setDetailPage]=useState(1);const [detailLoading,setDetailLoading]=useState(false);
  const [overviewError,setOverviewError]=useState('');const [error,setError]=useState('');const [detailError,setDetailError]=useState('');const [notice,setNotice]=useState('');const [loading,setLoading]=useState(false);const [refresh,setRefresh]=useState(0);
  const [confirmStatus,setConfirmStatus]=useState(false);const [busy,setBusy]=useState(false);
  const range=useMemo(()=>({period,...(period==='custom'?{start,end}:{})}),[period,start,end]); const validRange=period!=='custom'||!!(start&&end);
  useEffect(()=>{setSelected(initialReferrerId||null);setDetailPage(1);},[initialReferrerId]);
  useEffect(()=>{setPage(1);},[period,start,end,search,sort,excludeDisabled,excludeSuspended,excludeZero,status,service,stage,referrer,order,view]);
  useEffect(()=>{if(!validRange){setOverview(null);return;}const controller=new AbortController();setOverview(null);
    adminEarnRequest<{overview:EarnOverview}>(sessionToken,'overview',range,undefined,'GET',controller.signal).then(r=>setOverview(r.overview))
      .catch(e=>{if(e.name!=='AbortError')setOverviewError(e.message);});return()=>controller.abort();},[sessionToken,range,validRange,refresh]);
  useEffect(()=>{if(view==='rules'||!validRange)return;const controller=new AbortController();setLoading(true);setError('');setBoard(null);setLedger(null);
    const timer=setTimeout(()=>{const params=view==='leaderboard'?{...range,q:search,sort,page,limit:20,excludeDisabled,excludeSuspended,excludeZero}:{...range,page,limit:20,status,service,stage,referrer,order};
      adminEarnRequest<EarnPage<EarnReferrer>|EarnPage<EarnLedgerRow>>(sessionToken,view,params,undefined,'GET',controller.signal)
        .then(data=>{if(view==='leaderboard')setBoard(data as EarnPage<EarnReferrer>);else setLedger(data as EarnPage<EarnLedgerRow>);})
        .catch(e=>{if(e.name!=='AbortError')setError(e.message);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});},200);
    return()=>{clearTimeout(timer);controller.abort();};},[sessionToken,view,range,validRange,search,sort,page,excludeDisabled,excludeSuspended,excludeZero,status,service,stage,referrer,order,refresh]);
  useEffect(()=>{setDetailPage(1);},[selected,range]);
  useEffect(()=>{if(!selected||!validRange)return;const controller=new AbortController();setDetail(null);setDetailError('');setDetailLoading(true);
    adminEarnRequest<{detail:EarnDetail}>(sessionToken,`referrers/${encodeURIComponent(selected)}`,{...range,page:detailPage,limit:10},undefined,'GET',controller.signal)
      .then(r=>setDetail(r.detail)).catch(e=>{if(e.name!=='AbortError')setDetailError(e.message);}).finally(()=>{if(!controller.signal.aborted)setDetailLoading(false);});return()=>controller.abort();},[sessionToken,selected,range,validRange,detailPage,refresh]);
  const copy=async()=>{if(!board)return;try{const clean=(s:string)=>s.replace(/[\t\r\n\u0000-\u001f]/g,' ');
    const text=[`Giveaway shortlist · ${period} · UTC · sorted by ${sort} · page ${page}`,...board.items.map(row=>`${row.rank}. ${clean(row.name)} | ${row.code} | conversions ${row.qualifyingOrders} | first ${row.firstConversions} | converted relationships ${row.convertedCustomers} | revenue ${earnMoney(row.deliveredRevenueMinor)}`)].join('\n');
    await navigator.clipboard.writeText(text);setNotice(`Copied ${board.items.length} shortlisted users from this page. No prize was awarded.`);}catch{setError('Clipboard unavailable. Select and copy the ranking manually.');}};
  const toggleStatus=async()=>{if(!detail)return;setBusy(true);setDetailError('');try{await adminEarnRequest(sessionToken,`referrers/${encodeURIComponent(detail.referrer.userId)}/status`,{},
    {enabled:!detail.referrer.enabled,confirm:true},'PATCH');setConfirmStatus(false);setRefresh(n=>n+1);}catch(e){setDetailError(e instanceof Error?e.message:'Could not update profile.');}finally{setBusy(false);}};
  return <div className="space-y-5">
    <div className="flex flex-wrap justify-between items-center gap-3"><div><h2 className="text-xl sm:text-2xl font-bold">Mystery Earn Control Room</h2><p className="text-xs text-slate-400">Direct referrals · Server-derived metrics · UTC periods</p></div><button className={earnButton} onClick={()=>setRefresh(n=>n+1)}>Refresh</button></div>
    <div className="flex flex-wrap items-end gap-3"><label className="text-xs">Period<select className={earnInput} value={period} onChange={e=>setPeriod(e.target.value)}><option value="today">Today</option><option value="7d">Last 7 days</option><option value="30d">Last 30 days</option><option value="all">All time</option><option value="custom">Custom range</option></select></label>
      {period==='custom'&&<><label className="text-xs">Start date (UTC)<input className={earnInput} type="date" value={start} onChange={e=>setStart(e.target.value)}/></label><label className="text-xs">End date (inclusive UTC)<input className={earnInput} type="date" value={end} onChange={e=>setEnd(e.target.value)}/></label></>}
    </div>
    {!validRange&&<p className="text-amber-300 text-sm">Choose both custom dates to load the selected period.</p>}
    {overviewError&&<p role="alert" className="text-red-400 text-sm">Overview: {overviewError}</p>}{overview&&<><div className="grid grid-cols-2 gap-3"><div className="p-3 rounded-xl border border-slate-800 bg-[#0f171d]">Referral profiles (lifetime)<strong className="block text-xl">{overview.lifetimeProfiles}</strong></div><div className="p-3 rounded-xl border border-slate-800 bg-[#0f171d]">Enabled profiles (lifetime)<strong className="block text-xl">{overview.lifetimeEnabledProfiles}</strong></div></div><Metrics metrics={overview.metrics}/></>}
    <p className="text-xs text-slate-400">Conversions are paid/delivered purchases, classified using lifetime relationship + service history. Guest relationships require a stable attribution. Revenue excludes cancelled/refunded/failed orders. Rewards use ledger creation date and current status; expense is approved liability, not cash withdrawals. Gross margin excludes unknown costs and does not deduct rewards.</p>
    <div className="flex flex-wrap gap-2">{(['leaderboard','rules','ledger'] as const).map(tab=><button key={tab} className={`${earnButton} ${view===tab?'text-[#00c365] border-[#00c365]':''}`} onClick={()=>setView(tab)}>{tab==='leaderboard'?'Leaderboard / Giveaway':tab==='rules'?'Reward Rules':'Reward Ledger'}</button>)}</div>
    {error&&<p role="alert" className="text-red-400 text-sm">{error}</p>}{notice&&<p role="status" className="text-[#00c365] text-sm">{notice}</p>}
    {view==='rules'?<AdminEarnRules sessionToken={sessionToken} refreshKey={refresh}/>:view==='leaderboard'?<div className="space-y-3">
      <div className="flex flex-wrap gap-3"><label className="flex-1 min-w-48 text-xs">Find referrer<input className={earnInput} maxLength={200} placeholder="Name, email, phone or referral code" value={search} onChange={e=>setSearch(e.target.value)}/></label>
        <label className="text-xs">Rank by<select className={earnInput} value={sort} onChange={e=>setSort(e.target.value)}><option value="conversions">Most qualifying conversions</option><option value="firstConversions">Most first-time conversions</option><option value="convertedCustomers">Most successful referred relationships</option><option value="deliveredRevenueMinor">Most referral revenue</option><option value="approvedRewardsMinor">Most approved rewards</option><option value="referredCustomers">Most people referred</option><option value="uniqueVisitors">Most unique visitors</option></select></label></div>
      <div className="flex flex-wrap items-center gap-3"><button className={earnButton} onClick={()=>{setGiveaway(!giveaway);if(!giveaway){setExcludeDisabled(true);setExcludeSuspended(true);setExcludeZero(true);setSort('convertedCustomers');}}}>{giveaway?'Exit Giveaway Ranking':'Giveaway Ranking'}</button>
        {giveaway&&<button className={earnButton} disabled={loading||!board?.items.length} onClick={()=>void copy()}>Copy shortlist (this page)</button>}
        <label className="text-xs min-h-10 flex items-center gap-2"><input type="checkbox" checked={excludeDisabled} onChange={e=>setExcludeDisabled(e.target.checked)}/>Exclude disabled accounts</label>
        <label className="text-xs min-h-10 flex items-center gap-2"><input type="checkbox" checked={excludeSuspended} onChange={e=>setExcludeSuspended(e.target.checked)}/>Exclude suspended profiles</label>
        <label className="text-xs min-h-10 flex items-center gap-2"><input type="checkbox" checked={excludeZero} onChange={e=>setExcludeZero(e.target.checked)}/>Exclude zero conversions</label></div>
      {giveaway&&<p className="text-xs text-amber-300">Ranking only. No random winner, money or data award. Successful referrals count distinct qualifying relationships, including stable guest attributions.</p>}
      {loading?<p className="text-slate-400">Loading ranking…</p>:board&&<><div className="overflow-x-auto rounded-2xl border border-slate-800"><table className="w-full min-w-[1100px] text-xs"><thead className="bg-slate-900 text-slate-400"><tr>{['Rank','Referrer / Code','Visitors','Raw clicks','People referred','First','Repeat','Delivered revenue','Approved rewards','Conversion rate','Signals'].map(h=><th key={h} className="p-3 text-left">{h}</th>)}</tr></thead><tbody>{board.items.map(row=><tr key={row.userId} className="border-t border-slate-800"><td className="p-3">{row.rank}</td><td className="p-3"><button className="min-h-10 text-left text-[#00c365]" onClick={()=>{setSelected(row.userId);setDetailPage(1);}}>{row.name}<span className="block text-slate-400">{row.code}</span></button></td>
        <td className="p-3">{row.uniqueVisitors}</td><td className="p-3">{row.rawClicks}</td><td className="p-3">{row.referredCustomers}</td><td className="p-3">{row.firstConversions}</td><td className="p-3">{row.repeatConversions}</td><td className="p-3">{earnMoney(row.deliveredRevenueMinor)}</td><td className="p-3">{earnMoney(row.approvedRewardsMinor)}</td><td className="p-3">{row.conversionRate}%</td><td className="p-3 text-amber-300">{row.signals.join(' · ')||'—'}</td></tr>)}</tbody></table></div>
        {board.items.length===0&&<p className="text-slate-400">No matching referrers.</p>}<EarnPager page={page} total={board.total} limit={board.limit} onPage={setPage}/></>}
      <p className="text-xs text-slate-500">Conversion rate = converted relationships / unique visitors in the period; this is an activity ratio, not a tracked cohort funnel. Signals are informational and never trigger suspension.</p>
    </div>:<div className="space-y-3"><div className="grid grid-cols-2 md:grid-cols-3 gap-3">
      <label className="text-xs">Status<select className={earnInput} value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option>{['pending','approved','rejected','reversed'].map(x=><option key={x}>{x}</option>)}</select></label>
      <label className="text-xs">Service<select className={earnInput} value={service} onChange={e=>setService(e.target.value)}><option value="">All services</option>{['data','airtime','instant_bundle','marketplace','website_builder','manual_adjustment'].map(x=><option key={x}>{x}</option>)}</select></label>
      <label className="text-xs">Reward stage<select className={earnInput} value={stage} onChange={e=>setStage(e.target.value)}><option value="">All stages</option>{['standard','acquisition','recurring'].map(x=><option key={x}>{x}</option>)}</select></label>
      <label className="text-xs">Referrer user ID<input className={earnInput} maxLength={64} value={referrer} onChange={e=>setReferrer(e.target.value)}/></label><label className="text-xs">Order reference<input className={earnInput} maxLength={128} value={order} onChange={e=>setOrder(e.target.value)}/></label>
    </div>{loading?<p>Loading ledger…</p>:ledger&&<><Ledger data={ledger}/><EarnPager page={page} total={ledger.total} limit={ledger.limit} onPage={setPage}/></>}<p className="text-xs text-slate-400">Read-only ledger inspection. No amount edits, credits or deletion.</p></div>}
    {selected&&<AdminEarnDialog title="Referrer detail" busy={busy} onClose={()=>{setSelected(null);setConfirmStatus(false);}}>
      {detailLoading&&<p>Loading referrer…</p>}{detailError&&<p role="alert" className="text-red-400">{detailError}</p>}{detail&&<div className="space-y-4"><div className="space-y-1 text-sm"><h4 className="font-bold">{detail.referrer.name}</h4><p className="break-all">{detail.referrer.email||'No email'} · {detail.referrer.phone||'No phone'}</p><p>Account: {detail.referrer.accountStatus} · Code: {detail.referrer.code} · Profile: {detail.referrer.enabled?'Active':'Suspended'}</p></div>
        <div className="flex flex-wrap gap-2"><button className={earnButton} onClick={()=>onOpenCustomer(detail.referrer.userId)}>Open Customer profile</button><button className={earnButton} onClick={()=>setConfirmStatus(true)}>{detail.referrer.enabled?'Suspend referral profile':'Resume referral profile'}</button><button className={earnButton} onClick={()=>{setReferrer(detail.referrer.userId);setView('ledger');setSelected(null);}}>Inspect full ledger</button></div>
        {confirmStatus&&<div className="p-4 border border-amber-500/40 rounded-xl space-y-3"><p>{detail.referrer.enabled?'Suspend new captures, new bindings and future reward credits? History and earned rewards stay intact.':'Resume future captures and eligible rewards? Orders delivered during suspension will not be back-paid.'}</p><button className={earnButton} disabled={busy} onClick={()=>void toggleStatus()}>{busy?'Updating…':'Confirm profile status'}</button><button className={`${earnButton} ml-2`} disabled={busy} onClick={()=>setConfirmStatus(false)}>Cancel</button></div>}
        <Metrics metrics={detail.referrer}/><h4 className="font-bold">Recent referred customers (lifetime)</h4>{detail.customers.items.map(customer=><article key={customer.id} className="p-3 bg-slate-900 rounded-xl text-xs space-y-1"><strong>{customer.name}</strong><p>{customer.email||'—'} · {customer.phone||'—'}</p><p>Bound {customer.boundAt?new Date(customer.boundAt).toISOString():'—'}</p><p>First qualifying order: {customer.firstOrder||'None'} · Latest: {customer.latestOrder||'None'}</p></article>)}
        <EarnPager page={detailPage} total={detail.customers.total} limit={detail.customers.limit} onPage={setDetailPage} disabled={busy}/><h4 className="font-bold">Recent ledger entries (selected period)</h4><Ledger data={detail.ledger}/>
      </div>}
    </AdminEarnDialog>}
  </div>;
};
